const sources = {
  xss: { label: 'OWASP · Cross Site Scripting Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html', note: '출력 컨텍스트, safe sink, sanitization, CSP의 역할과 한계를 확인합니다.' },
  dom: { label: 'OWASP · DOM-based XSS Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html', note: '브라우저 안의 source와 sink를 추적하는 방식을 확인합니다.' },
  wstg: { label: 'OWASP · Web Security Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/', note: '관찰 근거와 재시험을 남기는 테스트·보고서 기준으로 사용합니다.' },
}

const reportEvidenceScenario = {
  statements: [
    { id: 'fact', label: '합성 게시글 미리보기에서 고정 마커가 HTML 구조로 해석되는 DOM 변화를 확인했다.' },
    { id: 'impact', label: '권한 있는 사용자가 이 화면을 볼 때 페이지 기능과 DOM 데이터에 영향을 줄 가능성이 있어 추가 확인이 필요하다.' },
    { id: 'condition', label: '영향 판단에는 피해자 역할, 노출된 기능, HttpOnly와 CSP 설정을 별도로 확인해야 한다.' },
    { id: 'root-cause', label: '저장된 제목을 텍스트 노드가 아닌 `innerHTML` 경로로 렌더링한다.' },
    { id: 'control', label: '일반 텍스트 제목은 `textContent`로 출력하고, 제한된 HTML이 필요한 기능은 별도 정화 정책을 적용한다.' },
    { id: 'retest', label: '일반 제목, 문법 문자가 포함된 텍스트, 빈 값, 저장 후 재조회 경로를 수정 전과 같은 기준으로 비교한다.' },
  ],
  categories: [
    { id: 'fact', label: '관찰 사실' },
    { id: 'impact', label: '영향 판단' },
    { id: 'condition', label: '전제 조건' },
    { id: 'root-cause', label: '근본 원인' },
    { id: 'control', label: '수정 방향' },
    { id: 'retest', label: '재시험 계획' },
  ],
  reflection: {
    prompt: '위 문장 중 하나를 골라, 왜 그것이 관찰 사실 또는 영향 판단인지 근거를 60자 이상으로 설명하세요.',
    minimumLength: 60,
  },
}

export const week4LessonMeta = Object.freeze({
  'w4-nature': {
    title: '검색어는 언제 HTML이 되는가',
    summary: 'HTML, DOM, origin을 짧게 복습한 뒤 일반 텍스트가 해석형 출력 지점에서 구조가 되는 순간을 봅니다.',
    duration: 55,
    archetype: '원리 해설형',
    learningQuestion: '일반 텍스트를 보여 주는 검색 결과에서 브라우저가 값을 HTML로 읽게 되는 순간은 언제인가?',
    observableOutcome: '태그·속성·텍스트 노드·DOM을 구분하고 textContent와 innerHTML이 만드는 결과 차이를 설명한다.',
    prerequisiteConceptIds: [],
    newConceptIds: ['html-tag', 'html-attribute', 'text-node', 'html-parser', 'dom-node', 'origin'],
    evidenceObjects: ['합성 검색 코드', '요청·응답·DOM 흐름도'],
    failurePoint: '일반 텍스트를 해석형 HTML API에 전달하는 출력 단계',
    impactConditions: ['같은 출처 문맥', '사용자가 해당 페이지를 보는 상황'],
    controls: ['textContent', '프레임워크 기본 escaping'],
    retestMatrix: ['일반 텍스트', '문법 문자', '빈 값'],
    transferGate: ['태그·속성·텍스트 노드를 구분한다.', '해석형 출력 지점을 한 곳 표시한다.'],
  },
  'w4-types': {
    title: '세 경로는 어디서 갈라지는가',
    summary: '반사형·저장형·DOM 기반 XSS를 이름이 아니라 데이터가 이동하는 시간과 위치로 비교합니다.',
    duration: 55,
    archetype: '사례 판정형',
    learningQuestion: '서버 응답과 실행 후 DOM을 함께 볼 때 세 XSS 경로는 어디에서 달라지는가?',
    observableOutcome: '세 흐름에서 source, 저장 여부, browser interpretation 위치를 표와 증거로 구분한다.',
    prerequisiteConceptIds: ['dom-node', 'server-response'],
    newConceptIds: ['server-response', 'live-dom'],
    evidenceObjects: ['합성 요청', '저장 기록', '응답 원문', '실행 후 DOM'],
    failurePoint: '각 경로의 해석형 출력 단계',
    impactConditions: ['입력 전달 또는 저장', '피해자의 렌더링'],
    controls: ['출력 경로의 데이터/코드 분리'],
    retestMatrix: ['현재 요청', '저장 후 재조회', 'fragment 기반 경로'],
    transferGate: ['응답 원문과 live DOM을 구분한다.'],
  },
  'w4-taint': {
    title: '값이 도착한 곳보다, 지나간 경로를 읽는다',
    summary: 'source, transform, interpreting sink를 한 흐름에서 추적해 실패 지점과 안전한 분기를 고릅니다.',
    duration: 65,
    archetype: '흐름 추적형',
    learningQuestion: 'URL의 값이 브라우저에서 구조로 해석될 때, 어느 줄이 실제로 약속을 깨는가?',
    observableOutcome: '코드와 흐름도에서 source·transform·sink·context를 각각 표시하고 안전한 분기를 제안한다.',
    prerequisiteConceptIds: ['html-parser', 'text-node'],
    newConceptIds: ['xss-source', 'data-transform', 'interpreting-sink', 'safe-sink'],
    evidenceObjects: ['합성 JavaScript 코드', 'source-to-sink 흐름도'],
    failurePoint: 'interpreting sink에 신뢰 수준이 불명확한 값을 전달하는 단계',
    impactConditions: ['해석형 sink', '출력 컨텍스트'],
    controls: ['safe sink', '컨텍스트별 출력 처리'],
    retestMatrix: ['마커', '일반 문법 문자', '수정 뒤 DOM'],
    transferGate: ['source와 sink를 코드에서 각각 찾는다.'],
  },
  'w4-context': {
    title: '같은 문자열도 놓인 자리에 따라 다르게 읽힌다',
    summary: 'HTML 본문, 인용된 속성, URL, JavaScript 문자열의 문법 차이가 방어 선택을 바꾸는 이유를 봅니다.',
    duration: 70,
    archetype: '원리 해설형',
    learningQuestion: '문자열이 같아도 HTML 본문과 URL 속성에서 같은 방어를 적용하면 왜 부족할 수 있는가?',
    observableOutcome: '출력 컨텍스트를 네 가지로 구분하고 각 위치에서 데이터로 남게 하는 첫 선택을 설명한다.',
    prerequisiteConceptIds: ['html-attribute', 'interpreting-sink'],
    newConceptIds: ['output-context', 'contextual-output-encoding'],
    evidenceObjects: ['네 가지 출력 위치', '수정 전·후 코드'],
    failurePoint: '문맥을 구분하지 않고 공통 문자열 처리만 적용하는 설계',
    impactConditions: ['브라우저 파서 규칙', '속성 또는 URL의 허용 범위'],
    controls: ['컨텍스트별 encoding', 'URL allowlist', '위험한 위치 회피'],
    retestMatrix: ['본문', '속성', 'URL', 'JS data'],
    transferGate: ['출력 컨텍스트 네 가지를 구분한다.'],
  },
  'w4-impact': {
    title: '실행된 사실과 영향 판단은 다른 문장이다',
    summary: '같은 XSS 관찰도 사용자 역할, 기능, 데이터, 브라우저 통제에 따라 다른 영향을 가질 수 있음을 보고서 관점에서 판정합니다.',
    duration: 50,
    archetype: '사례 판정형',
    learningQuestion: '고정된 무해한 실행 표시를 본 뒤, 무엇을 확인해야 영향 범위를 판단할 수 있는가?',
    observableOutcome: '관찰 사실, 영향 판단, 전제, 미확인을 증거 보드에서 분리해 적는다.',
    prerequisiteConceptIds: ['origin', 'same-origin-policy'],
    newConceptIds: ['observation-inference', 'impact-conditions'],
    evidenceObjects: ['합성 XSS 관찰 결과', '사용자 역할·통제 조건 카드'],
    failurePoint: '해석형 sink가 남은 렌더링 경로',
    impactConditions: ['사용자 권한', '기능 범위', 'DOM 데이터', 'HttpOnly', 'CSP'],
    controls: ['근본 수정', '보완 통제 검토'],
    retestMatrix: ['권한별 화면', '보호 속성', '수정 후 관찰'],
    transferGate: ['사실과 판단을 다른 문장으로 쓴다.'],
  },
  'w4-defense': {
    title: '막는 위치가 다르면, 남는 위험도 다르다',
    summary: '텍스트 전용 출력, 제한된 HTML 정화, URL 검증, CSP를 근본 수정과 보완 통제로 나눠 비교합니다.',
    duration: 70,
    archetype: '방어·재시험형',
    learningQuestion: 'HTML이 필요 없는 화면과 제한된 서식이 필요한 화면은 왜 다른 방어를 선택해야 하는가?',
    observableOutcome: '근본 수정과 보완 통제를 구분하고, 수정 후 재시험 매트릭스를 작성한다.',
    prerequisiteConceptIds: ['output-context', 'safe-sink'],
    newConceptIds: ['html-sanitization-policy', 'csp'],
    evidenceObjects: ['수정 전·후 코드', '방어 계층 지도', '재시험 행렬'],
    failurePoint: '문자열 블랙리스트나 CSP만으로 해석형 sink를 남기는 설계',
    impactConditions: ['허용 HTML 요구', '정책 구성', '브라우저 지원'],
    controls: ['safe sink', 'sanitization policy', 'URL allowlist', 'CSP'],
    retestMatrix: ['정상 텍스트', '문법 문자', '다른 렌더링 경로', '정책 적용'],
    transferGate: ['CSP가 원인 수정이 아니라는 이유를 설명한다.'],
  },
  'w4-validation': {
    title: '수정 뒤에는 무엇을 증거로 남길까',
    summary: 'XSS Finding을 관찰 사실, 영향, 전제, 원인, 수정, 재시험으로 분해하고 문장을 근거에 맞춰 배치합니다.',
    duration: 60,
    archetype: '도구 관찰형',
    learningQuestion: '수정 전후를 비교한 뒤, 보고서에 어떤 문장을 어떤 근거와 함께 남겨야 하는가?',
    observableOutcome: '보고서 문장을 여섯 범주로 분류하고 정상·실패·경계·다른 경로 재시험을 제안한다.',
    prerequisiteConceptIds: ['observation-inference', 'impact-conditions', 'csp'],
    newConceptIds: ['retest-and-regression'],
    evidenceObjects: ['합성 Finding 문장', '수정 전·후 DOM', '재시험 행렬'],
    failurePoint: '근거 없이 영향을 단정하거나 수정 뒤 정상 기능을 확인하지 않는 기록',
    impactConditions: ['관찰 범위', '사용자 역할', '보호 장치'],
    controls: ['근본 수정 기록', '회귀 시험', '마스킹'],
    retestMatrix: ['정상', '문법 문자', '경계값', '다른 경로'],
    transferGate: ['내부 XSS lab 결과를 source·sink·context와 함께 기록한다.'],
  },
})

export const week4LessonBlocks = Object.freeze({
  'w4-nature': [
    { type: 'question', variant: 'lead', title: '검색어는 글자인데, 왜 페이지 구조가 될 수 있을까?', body: '검색 화면에 일반 문장을 넣었을 때 글자가 그대로 보이지 않고 일부가 사라진다면, 입력값이 이상한지부터 단정하지 마세요. 먼저 브라우저가 그 값을 글자로 보았는지, HTML 구조로 읽었는지를 구분해야 합니다.' },
    { type: 'concept-ref', variant: 'prerequisite', title: '시작 전 5분 복습', intro: '아래 다섯 개는 외부 문서를 열지 않고 이 페이지에서 바로 확인할 수 있는 선수 개념입니다.', conceptIds: ['html-tag', 'html-attribute', 'text-node', 'dom-node', 'origin'] },
    { type: 'explanation', variant: 'narrative', title: '문서 구조와 일반 글자는 다른 역할을 한다', paragraphs: [
      'HTML은 브라우저에게 문서의 구조를 알려 주는 언어입니다. 제목, 문단, 링크처럼 화면을 구성하는 표식이 있고, 그 표식 사이에는 사람이 읽을 문장이 들어갑니다. 검색어, 댓글, 프로필 이름처럼 사용자가 입력한 값은 대개 후자입니다. 서비스가 원하는 결과는 그 값을 화면에 보여 주는 일이지, 그 값이 새 태그나 속성을 만들게 하는 일이 아닙니다.',
      '브라우저는 받은 HTML을 읽어 DOM(Document Object Model)이라는 트리로 만듭니다. 태그, 속성, 텍스트는 DOM에서 서로 다른 노드와 값으로 남습니다. 페이지가 처음 로드된 뒤 JavaScript가 DOM을 바꿀 수도 있으므로, 서버가 보낸 원문과 현재 화면의 DOM은 항상 같은 것은 아닙니다.',
      'XSS는 "특수문자를 썼다"는 사건이 아닙니다. 일반 데이터가 어떤 경로를 거쳐 브라우저의 HTML 또는 코드 해석기에 전달되는 구조적 문제입니다. 따라서 먼저 정상 모델을 세웁니다. 일반 텍스트를 출력하는 기능이라면 입력은 시작부터 끝까지 텍스트 노드로 남아야 합니다.',
      '출처(origin)는 브라우저가 문서를 나누는 기본 경계입니다. 취약한 페이지 안에서 코드가 해석되면, 그 코드는 그 페이지의 DOM과 사용자가 가진 기능 문맥에서 동작할 수 있습니다. 이는 동일 출처 정책이 사라졌다는 뜻이 아니라, 취약한 페이지의 문맥 안에서 문제가 생긴다는 뜻입니다.',
    ] },
    { type: 'diagram', variant: 'boundary', title: '요청에서 화면까지, 어느 단계가 문법을 읽는가', body: '이 그림은 입력이 텍스트로 남는 정상 경로와 HTML 파서로 넘어가는 경로를 비교합니다. 실패 지점은 입력칸이 아니라 해석형 출력으로 갈라지는 곳입니다.', nodes: ['URL query · 사용자 데이터', '애플리케이션 · 문장 구성', 'textContent 또는 innerHTML 선택', 'HTML parser를 거친 DOM 또는 텍스트 노드', '브라우저 화면'] },
    { type: 'code', variant: 'before-after', language: 'JavaScript', title: '마지막 한 줄이 바꾸는 결과', description: '두 예시는 같은 `query` 값을 사용합니다. 어느 줄이 값을 HTML로 다시 읽게 하는지 비교하세요.', code: 'const query = new URLSearchParams(location.search).get(\'q\') ?? \'\'\n\n// 일반 텍스트 출력: 값은 text node로 남는다.\nresults.textContent = `검색어: ${query}`\n\n// 해석형 출력: 값이 HTML fragment로 파싱될 수 있다.\nresults.innerHTML = `검색어: ${query}`', annotations: ['두 줄의 입력 source와 문자열 조합은 같다.', '`textContent`는 일반 텍스트를 표시하는 목적에 맞는 출력 지점이다.', '`innerHTML`을 선택하면 브라우저의 HTML parser가 값에 관여하므로, 출력 컨텍스트를 다시 검토해야 한다.'] },
    { type: 'checkpoint', variant: 'prediction', id: 'w4-nature-check-01', title: '다음 결과를 예측해 보세요', prompt: '일반 텍스트를 보여 주는 검색 결과에서, 사용자의 값을 HTML parser에 넘기지 않으려면 어떤 선택이 가장 먼저 적절한가?', options: ['문자열 블랙리스트를 계속 늘린다.', '텍스트 전용 출력 지점을 사용한다.', 'CSP만 설정한다.'], answer: 1, explanation: '텍스트 전용 출력은 값이 HTML 구조로 해석되는 경로를 없앱니다. 블랙리스트와 CSP는 해석형 출력 지점이 남는 문제를 근본적으로 바꾸지 못하거나 보완 통제에 머뭅니다.' },
    { type: 'misconception', variant: 'contrast', title: '여기서 자주 섞이는 두 가지', items: ['`HTML을 화면에 표시한다`와 `사용자 값을 HTML로 해석한다`는 같은 말이다 → 전자는 문서 구조를 렌더링하는 일이고, 후자는 외부 값을 새 구조로 만들 수 있는 별도 선택이다.', '`HttpOnly`가 있으면 XSS는 문제가 아니다 → HttpOnly는 일부 쿠키 읽기를 제한할 뿐, 취약한 페이지 안에서 값이 해석되는 원인을 바꾸지 않는다.'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.xss] },
    { type: 'summary', title: '이 모듈의 결론', bullets: ['일반 텍스트 기능의 기대 결과는 입력이 텍스트 노드로 남는 것이다.', 'XSS의 핵심 질문은 값이 어디에서 HTML 또는 코드로 해석되는가이다.', '다음 모듈에서는 같은 값을 반사·저장·DOM 경로로 나눠 증거와 함께 비교한다.'] },
  ],
  'w4-types': [
    { type: 'case', variant: 'worked-example', title: '같은 마커, 서로 다른 세 장면', body: '합성 서비스에는 검색어를 즉시 응답에 넣는 페이지, 제목을 저장했다가 목록에 다시 그리는 게시판, URL fragment를 JavaScript가 읽어 화면을 바꾸는 페이지가 있습니다. 세 페이지에 같은 고정 마커가 보였다고 해서 같은 유형이라고 판단할 수는 없습니다.', facts: ['검색 페이지는 현재 요청의 query를 같은 응답에 넣는다.', '게시판은 작성 시점과 다른 사용자의 목록 렌더링 시점 사이에 저장 단계를 둔다.', 'fragment 값은 HTTP 요청 원문에 없을 수 있고, 브라우저 코드가 실행 후 DOM에 반영할 수 있다.'] },
    { type: 'diagram', variant: 'flow', title: '세 경로는 해석 전에 갈라진다', body: '유형 이름을 외우기보다 source가 저장되는지, 서버 응답에 있는지, 브라우저 안에서 새 DOM을 만드는지를 따라가세요.', nodes: ['Reflected · query → 응답 → 렌더링', 'Stored · 작성값 → 저장소 → 재조회 → 렌더링', 'DOM-based · fragment 또는 client data → JavaScript → live DOM'] },
    { type: 'explanation', variant: 'deep-dive', title: '반사, 저장, DOM 기반을 데이터의 수명으로 읽기', paragraphs: [
      '반사형 XSS에서는 현재 요청의 값이 서버 응답에 포함되는 흐름을 먼저 확인합니다. 이 경우에는 요청, 응답 원문, 값이 놓인 HTML 문법을 같은 시점의 증거로 비교할 수 있습니다. 누군가가 어떤 링크를 클릭해야 한다는 사실은 영향 조건일 수 있지만, 유형을 결정하는 유일한 기준은 아닙니다.',
      '저장형 XSS에서는 입력이 게시글, 프로필, 지원 티켓처럼 저장된 뒤 다른 화면에서 다시 출력됩니다. 저장된 값이 있다는 사실만으로 실행이 확정되는 것은 아닙니다. 작성 화면, 저장소, 조회 화면 중 어디가 해석형 출력을 사용했는지와 누가 그 화면을 보게 되는지를 분리해야 합니다.',
      'DOM 기반 XSS에서는 서버 응답 원문에 입력이 없을 수 있습니다. URL fragment, 브라우저 저장소, API 응답 같은 값이 JavaScript를 거쳐 live DOM에 들어갈 수 있기 때문입니다. 이때는 View Source만으로 결론을 내리지 않고, client-side source와 sink, 실행 뒤 DOM을 함께 봅니다.',
    ] },
    { type: 'comparison', variant: 'decision-matrix', title: '유형을 가르는 관찰 근거', columns: ['경로', '먼저 확인할 증거', '아직 확인할 것'], rows: [
      ['반사형 후보', '현재 요청 값과 서버 응답 원문', '값이 어떤 HTML 문맥에 출력되는지'],
      ['저장형 후보', '작성값, 저장 기록, 나중의 조회 화면', '다른 사용자·역할이 실제로 보는지'],
      ['DOM 기반 후보', 'client-side source, JavaScript, live DOM', '서버 응답·API 값 중 실제 source가 무엇인지'],
    ] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-types-check-01', title: '증거만으로 먼저 고르기', prompt: '서버 응답 원문에는 고정 마커가 없고, 페이지가 로드된 뒤 JavaScript가 만든 DOM에만 마커가 보입니다. 우선 조사할 경로는?', options: ['DOM 기반 흐름', '저장형 흐름만', 'SQL 질의 흐름'], answer: 0, explanation: '실행 후 DOM에만 값이 생겼다는 사실은 client-side source와 sink를 먼저 보게 하는 근거입니다. 다만 실제 source가 무엇인지는 JavaScript와 데이터 응답을 더 확인해야 확정할 수 있습니다.' },
    { type: 'concept-ref', variant: 'reference', title: '증거를 읽을 때 쓰는 용어', intro: '응답 원문과 실행 후 DOM을 같은 것으로 보지 않기 위해 아래 개념을 다시 확인하세요.', conceptIds: ['server-response', 'live-dom', 'dom-node'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.dom, sources.wstg] },
  ],
  'w4-taint': [
    { type: 'question', variant: 'prediction', title: '코드에서 첫 줄과 마지막 줄 중 어디가 더 중요할까?', body: 'URL에서 값을 읽는 줄을 찾았다고 해서 취약점이 확정되지는 않습니다. 그 값이 어떤 변환을 거쳐 마지막에 어느 API로 전달되는지까지 따라가야 합니다.' },
    { type: 'code', variant: 'annotated', language: 'JavaScript', title: '검색어가 DOM에 도착하는 여섯 단계', description: '이 코드는 고정 교육용 흐름입니다. 각 줄이 source, transform, sink 중 어디에 해당하는지 읽어 보세요.', code: 'const raw = location.search                         // 1. 브라우저가 가진 URL\nconst query = new URLSearchParams(raw).get(\'q\') ?? \'\' // 2. source 읽기\nconst label = `검색어: ${query}`                       // 3. 문자열 transform\nconst panel = document.querySelector(\'#results\')     // 4. DOM 대상 선택\npanel.innerHTML = label                                 // 5. interpreting sink\n// 수정: panel.textContent = label                       // 6. text sink', annotations: ['source는 값의 출발점이며, 이 자체가 실행을 뜻하지는 않습니다.', '문자열 결합과 DOM 대상 선택은 transform 또는 중간 처리입니다.', '실패 지점은 일반 텍스트가 필요한 기능에서 `innerHTML`이 값을 HTML로 해석하게 하는 마지막 단계입니다.', '수정은 입력을 지우는 일이 아니라, 값이 텍스트로 남도록 최종 출력 계약을 바꾸는 일입니다.'] },
    { type: 'diagram', variant: 'flow', title: 'source에서 browser interpretation까지', body: '흐름을 끊어 읽으면 필터가 있는지에만 시선이 갑니다. 이 그림은 값이 어느 경계에서 문법으로 바뀌는지를 보여 줍니다.', nodes: ['URL query · source', 'URLSearchParams · decode/parse', '문자열 조합 · transform', 'innerHTML · interpreting sink', 'HTML parser · browser interpretation', 'live DOM · 관찰 대상'] },
    { type: 'evidence-board', variant: 'source-sink', title: '지금 코드에서 확정된 것과 아직 모르는 것', sections: [
      { label: '관찰', items: ['값은 `location.search`에서 읽힌다.', '`panel.innerHTML`이 최종 출력 API다.'] },
      { label: '해석', items: ['일반 텍스트 목적이라면 해석형 sink가 실패 지점이 될 수 있다.'] },
      { label: '전제', items: ['실제 화면이 HTML 구조를 입력으로 받을 필요가 없는 기능이어야 한다.'] },
      { label: '미확인', items: ['다른 렌더링 경로가 같은 값을 다시 HTML로 출력하는지', '권한 있는 화면에서 같은 코드가 쓰이는지'] },
    ] },
    { type: 'explanation', variant: 'narrative', title: '중간 필터가 있어도 마지막 문맥을 확인하는 이유', paragraphs: [
      'source와 sink 사이에는 decode, validate, template rendering, 저장, 문자열 조합처럼 많은 변환이 있습니다. 어떤 단계가 값을 검사했다는 사실만으로 최종 출력이 안전하다고 결론 내리면 안 됩니다. 검사한 값과 브라우저가 읽는 값의 문맥·순서가 다를 수 있기 때문입니다.',
      'safe sink는 값을 "신뢰한다"고 선언하는 API가 아닙니다. 일반 텍스트 기능에서 그 값을 HTML 문법으로 읽지 않겠다는 출력 계약입니다. 반대로 제한된 HTML을 지원해야 하는 기능이라면 텍스트 API만으로 요구를 충족할 수 없으므로, 허용 구조를 정한 정화 정책이 별도로 필요합니다.',
      '이 흐름을 기록하면 보고서의 원인 문장도 구체적으로 바뀝니다. "필터가 약하다"보다 "query 값이 HTML 본문 컨텍스트의 interpreting sink로 전달되어 텍스트가 아닌 마크업으로 해석될 수 있다"가 재시험 가능한 설명입니다.',
    ] },
    { type: 'checkpoint', variant: 'short-answer', id: 'w4-taint-check-01', title: '실패 지점을 한 문장으로 적기', prompt: '위 코드에서 source, transform, interpreting sink를 각각 하나씩 적고, 일반 텍스트 기능에서 무엇을 바꿔야 하는지 80자 이상으로 설명하세요.', placeholder: '예: source는 ..., transform은 ..., sink는 ...이며 ...' },
    { type: 'concept-ref', variant: 'reference', title: '경로를 표시할 때 쓰는 개념', intro: '이 용어들은 이후 SQLi의 코드/데이터 경계와 AI 보안의 prompt/tool 경계에도 다시 나옵니다.', conceptIds: ['xss-source', 'data-transform', 'interpreting-sink', 'safe-sink'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.dom, sources.xss] },
    { type: 'summary', title: '코드에서 남길 네 가지 표시', bullets: ['source는 값이 들어온 지점이다.', 'transform은 값의 문법·수명·형태를 바꾼 중간 단계다.', 'sink는 값이 최종적으로 해석되거나 표시되는 위치다.', '일반 텍스트 기능은 safe sink로 출력 계약을 분명히 한다.'] },
  ],
  'w4-context': [
    { type: 'concept-ref', variant: 'prerequisite', title: '문법 위치를 구분하는 두 단어', intro: '출력 컨텍스트와 컨텍스트별 인코딩은 "특수문자 처리"라는 한 덩어리가 아닙니다. 먼저 어떤 파서가 값을 읽는지 봅니다.', conceptIds: ['output-context', 'contextual-output-encoding'] },
    { type: 'explanation', variant: 'deep-dive', title: '값이 같은데 방어가 달라지는 이유', paragraphs: [
      '브라우저는 HTML 본문의 텍스트, 따옴표로 감싼 속성 값, URL 값, JavaScript 문자열을 서로 다른 규칙으로 읽습니다. 따라서 "입력에 특수문자가 있다"는 말만으로는 필요한 방어를 정할 수 없습니다. 값이 실제로 놓이는 문법 위치와 기능 요구를 먼저 알아야 합니다.',
      'HTML 본문에서 일반 문장을 보여 주는 가장 단순한 선택은 텍스트 노드로 넣는 것입니다. 속성 값은 허용된 속성 이름을 코드에서 고정하고 값만 설정하는 방식이 더 낫습니다. URL은 인코딩뿐 아니라 허용할 protocol과 목적지를 검토해야 하며, JavaScript 문자열 안에 외부 값을 직접 붙이는 설계는 가능한 한 피해야 합니다.',
      'CSS와 HTML comment처럼 안전하게 다루기 어려운 문법 위치도 있습니다. 이 위치에서는 "더 좋은 escape"를 찾기보다 신뢰할 수 없는 값을 넣지 않는 설계를 우선합니다. 컨텍스트는 지식 퀴즈가 아니라, 값이 코드와 데이터의 경계를 넘는지 판단하는 도구입니다.',
    ] },
    { type: 'comparison', variant: 'decision-matrix', title: '네 가지 출력 위치에서 먼저 묻는 질문', columns: ['출력 위치', '브라우저가 읽는 것', '첫 방어 선택'], rows: [
      ['HTML 본문', '텍스트 또는 HTML 구조', '텍스트 전용 출력 또는 HTML context encoding'],
      ['따옴표 속성 값', '속성의 값', '안전한 속성명을 고정하고 속성 값 처리'],
      ['URL 값', '이동할 주소와 protocol', 'URL 파싱 뒤 허용 scheme·목적지 검증'],
      ['JavaScript 데이터', '문자열 또는 코드 문법', 'inline 조합을 피하고 구조화된 데이터 전달'],
    ] },
    { type: 'code', variant: 'before-after', language: 'JavaScript', title: '링크 목적지는 HTML body와 다른 판단이 필요하다', description: '두 코드는 모두 링크를 다룹니다. 하지만 URL 값은 텍스트 출력과 달리 이동할 목적지와 protocol을 먼저 검토해야 합니다.', code: 'const next = readTrainingValue()\n\n// 값이 곧바로 링크 목적지가 된다.\nnextLink.href = next\n\n// URL을 해석한 뒤 교육용 허용 범위만 선택한다.\nconst url = new URL(next, location.origin)\nif ([\'http:\', \'https:\'].includes(url.protocol)) {\n  nextLink.href = url.href\n}', annotations: ['문자열을 HTML 본문에 넣는 문제와 URL 목적지를 허용하는 문제는 같지 않습니다.', '실제 서비스에서는 허용 origin, 상대 경로, redirect 정책 같은 추가 요구를 기능에 맞게 정해야 합니다.', '이 교육 예시는 외부 링크를 열지 않고 판단 결과만 설명합니다.'] },
    { type: 'misconception', variant: 'contrast', title: '같은 단어로 부르면 놓치는 차이', items: ['`escaping`, `encoding`, `sanitization`, `validation`은 모두 입력 필터다 → 출력 인코딩은 문맥에서 데이터를 표시하는 방식이고, 정화는 제한된 HTML 정책이며, validation은 허용할 데이터 형태를 정하는 별도 통제다.', 'HTML escape를 한 번 적용하면 URL과 JavaScript에도 안전하다 → 파서와 문법 위치가 다르므로 값이 들어갈 자리를 먼저 구분해야 한다.'] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-context-check-01', title: '수정 방향 고르기', prompt: '사용자가 입력한 "다음 페이지" 값을 링크의 목적지에 넣는 기능을 검토할 때, HTML body 인코딩만으로 충분하지 않은 가장 직접적인 이유는?', options: ['링크는 화면에 보이지 않기 때문', 'URL 값에는 허용할 protocol과 목적지를 따로 판단해야 하기 때문', '모든 링크는 무조건 제거해야 하기 때문'], answer: 1, explanation: 'URL은 브라우저가 이동할 목적지를 해석하는 문맥입니다. 값이 HTML 속성 안에 들어간다는 사실만으로 허용할 protocol·origin·redirect 정책이 정해지지는 않습니다.' },
    { type: 'retest', variant: 'context-matrix', title: '컨텍스트별 수정 뒤 비교할 항목', intro: '재시험은 한 개의 눈에 띄는 문자열만 넣어 보는 일이 아닙니다. 각 출력 위치에서 정상 기능과 문법 경계를 함께 확인합니다.', rows: [
      { label: 'HTML 본문', check: '일반 한글과 문법 문자가 텍스트로 남는가', expected: 'DOM 구조가 늘지 않고 화면 문장만 바뀜' },
      { label: '속성 값', check: '고정된 안전 속성의 값이 의도대로 보이는가', expected: '새 이벤트 속성·태그가 생기지 않음' },
      { label: 'URL', check: '허용된 상대·HTTPS 주소만 기능을 유지하는가', expected: '허용 밖 목적지는 안전하게 거부 또는 기본 경로 사용' },
      { label: 'JavaScript 데이터', check: '구조화된 데이터 전달 뒤 같은 화면 상태가 유지되는가', expected: 'inline 코드 조합 없이 값이 데이터로 처리됨' },
    ] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.xss] },
  ],
  'w4-impact': [
    { type: 'case', variant: 'report-review', title: '합성 Finding의 첫 문장을 검토해 보자', body: '"게시글 제목에서 XSS가 발생하므로 모든 사용자의 계정이 탈취된다." 이 문장은 관찰, 영향, 전제를 한꺼번에 섞고 있습니다. 제목이 해석형 sink에 도달했다는 사실은 원인 조사에 중요하지만, 영향을 판단하려면 누가 그 화면을 보는지와 그 화면이 어떤 데이터·행동에 닿는지를 더 확인해야 합니다.' },
    { type: 'evidence-board', variant: 'impact', title: '보고서에는 서로 다른 칸이 필요하다', sections: [
      { label: '관찰 사실', items: ['합성 게시글 목록에서 고정 마커가 텍스트가 아닌 DOM 구조로 표시됐다.', '렌더링 코드는 저장된 제목을 `innerHTML`에 전달한다.'] },
      { label: '영향 판단', items: ['해당 화면을 보는 사용자의 페이지 기능과 DOM 데이터에 영향을 줄 가능성이 있다.'] },
      { label: '전제 조건', items: ['피해자 역할과 접근 가능한 기능', 'DOM에 존재하는 민감 데이터', 'HttpOnly·CSP 같은 보호 설정'] },
      { label: '미확인 항목', items: ['실제 운영 환경의 사용자 역할 분포', '다른 화면의 같은 렌더링 경로', '보호 정책의 정확한 적용 범위'] },
    ] },
    { type: 'explanation', variant: 'narrative', title: '영향은 기능과 권한 위에서만 판단할 수 있다', paragraphs: [
      'XSS는 브라우저에서 값이 해석되는 문제이므로, 실행 여부를 확인하는 무해한 증거가 출발점이 됩니다. 하지만 그것만으로 어떤 데이터가 노출됐는지, 어떤 요청이 수행됐는지, 어느 사용자까지 영향을 받는지는 알 수 없습니다. 보고서에서는 확인한 화면 변화와 가능한 후속 영향을 다른 문장으로 씁니다.',
      '사용자 역할은 중요한 조건입니다. 관리자나 운영자가 자주 보는 화면이라면 영향 범위를 넓게 검토해야 하지만, 역할 이름만으로 영향이 확정되지는 않습니다. 그 역할이 실제로 할 수 있는 행동, 페이지에 표시되는 데이터, 서버가 별도로 인가를 다시 검사하는지를 근거로 봅니다.',
      '`HttpOnly`는 JavaScript에서 특정 쿠키를 읽는 일을 제한할 수 있고, CSP는 허용되지 않은 스크립트·리소스 실행을 줄일 수 있습니다. 둘 다 영향 조건에 기록할 수 있지만, 해석형 sink가 남아 있다는 원인을 없애는 통제는 아닙니다. 어떤 통제가 무엇을 줄이는지 정확히 쓰는 것이 과장과 과소평가를 함께 막습니다.',
    ] },
    { type: 'concept-ref', variant: 'reference', title: '영향 문장을 쓰기 전에 확인할 개념', intro: '아래 개념은 "실행됐다"는 사실을 곧바로 "모든 데이터가 유출됐다"는 결론으로 바꾸지 않게 합니다.', conceptIds: ['origin', 'same-origin-policy', 'observation-inference', 'impact-conditions'] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-impact-check-01', title: '사실과 판단을 분리하기', prompt: '다음 중 합성 XSS 보고서에서 관찰 사실에 가장 가까운 문장은?', options: ['모든 계정이 탈취될 수 있다.', '관리자 화면이므로 최고 심각도다.', '고정 마커가 저장된 제목 경로를 거쳐 live DOM에서 구조로 나타났다.'], answer: 2, explanation: '마커가 어느 데이터 경로와 DOM 결과에서 관찰됐는지는 직접 증거입니다. 계정 영향과 심각도는 역할·기능·보호 장치를 추가로 검토한 판단이어야 합니다.' },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.xss, sources.wstg] },
  ],
  'w4-defense': [
    { type: 'explanation', variant: 'narrative', title: '방어는 입력을 지우는 일이 아니라 출력 계약을 고치는 일', paragraphs: [
      '사용자 입력을 일반 글자로 보여 주는 기능이라면 가장 좋은 출발점은 해석형 HTML API를 사용하지 않는 것입니다. 프레임워크의 기본 escaping을 유지하고 `textContent`처럼 값이 텍스트로 남는 출력 지점을 사용하면, 브라우저가 입력을 마크업으로 다시 읽는 경로를 줄일 수 있습니다.',
      '제목과 댓글처럼 일반 텍스트만 필요한 기능과, 서식 있는 문서처럼 제한된 HTML이 필요한 기능은 요구가 다릅니다. 후자의 경우에는 어떤 태그와 속성을 허용할지 명시한 sanitization policy가 필요합니다. 정화는 모든 문자열을 똑같이 삭제하는 블랙리스트가 아니라, 제품 기능에 맞는 허용 구조를 관리하는 일입니다.',
      'URL은 허용 protocol과 목적지를, JavaScript 데이터는 inline 문자열 결합을 피하는 전달 방식을 따로 검토합니다. CSP, Cookie 속성, WAF는 영향 완화·탐지에 도움이 될 수 있지만, 텍스트를 HTML로 해석하는 원인 자체를 수정한 사실과 구분해야 합니다.',
    ] },
    { type: 'comparison', variant: 'before-after', title: '근본 수정과 보완 통제를 같은 칸에 넣지 않기', columns: ['통제', '무엇을 바꾸는가', '남는 확인'], rows: [
      ['safe sink 또는 framework escaping', '값이 HTML 문법으로 해석되는 출력 경로', '다른 renderer와 raw HTML escape hatch'],
      ['sanitization policy', '필요한 제한 HTML의 허용 구조', '정화 뒤 변형, 라이브러리 업데이트, 허용 목록'],
      ['URL allowlist', '이동 가능한 목적지와 protocol 범위', 'redirect 정책과 상대 경로 처리'],
      ['CSP·Cookie 속성·WAF', '일부 실행·노출 영향 또는 탐지', '근본 sink가 제거됐는지 별도 재시험'],
    ] },
    { type: 'diagram', variant: 'boundary', title: '수정 뒤에도 세 겹으로 확인한다', body: '그림은 하나의 제품에 세 종류의 통제가 서로 다른 질문에 답한다는 점을 보여 줍니다. 가장 안쪽의 출력 계약이 바뀌지 않으면 바깥 통제만으로 완료라고 쓰지 않습니다.', nodes: ['근본 수정 · safe sink 또는 정책화된 HTML', '보완 통제 · CSP·Cookie 속성·URL 정책', '운영 확인 · 로그·코드 리뷰·회귀 시험'] },
    { type: 'misconception', variant: 'contrast', title: '차단됐다는 화면이 곧 수정 완료는 아니다', items: ['CSP가 고정 PoC 표시를 막았으니 취약점도 사라졌다 → CSP는 보완 통제일 수 있습니다. 여전히 해석형 sink가 남아 있는지 코드와 DOM으로 확인해야 합니다.', '문자열 블랙리스트를 추가하면 안전한 출력이 된다 → 입력의 표면 표현을 늘려 막는 방식은 문법 위치와 새 경로를 보장하지 못합니다.'] },
    { type: 'retest', variant: 'regression', title: '수정 결과를 확인하는 네 가지 비교', intro: '같은 무해한 입력 범주를 수정 전과 수정 후에 비교합니다. 재시험은 실행 표시가 사라지는지와 기능이 남는지를 함께 봅니다.', rows: [
      { label: '정상 기능', check: '일반 제목·댓글이 기존처럼 표시·저장되는가', expected: '기능과 레이아웃이 유지됨' },
      { label: '문법 문자', check: '꺾쇠·따옴표가 포함된 일반 문장이 텍스트로 남는가', expected: '새 DOM 구조나 이벤트 경로가 생기지 않음' },
      { label: '저장·재조회', check: '작성 후 다른 목록·상세 화면에서 같은 정책이 적용되는가', expected: 'renderer 사이에 보호 차이가 없음' },
      { label: '보완 통제', check: 'CSP 등 정책이 기대한 제한을 제공하는가', expected: '근본 수정과 별개로 정책 결과를 기록함' },
    ] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-defense-check-01', title: '수정 우선순위 판단', prompt: '일반 텍스트만 보여 주는 프로필 이름 화면에서 가장 직접적인 근본 수정은?', options: ['CSP에 규칙 하나만 추가한다.', '프로필 이름을 textContent 또는 프레임워크 기본 escaping 경로로 출력한다.', '차단 문자열 목록을 두 배로 늘린다.'], answer: 1, explanation: '기능이 HTML을 요구하지 않는다면 해석형 출력 지점을 텍스트 전용 경로로 바꾸는 것이 원인을 직접 다룹니다. CSP와 필터는 남는 위험을 줄일 수 있지만, 그 자체로 출력 계약을 바꾸지는 않습니다.' },
    { type: 'concept-ref', variant: 'reference', title: '방어 선택을 위한 보충 개념', intro: '같은 "방어"라는 말 안에 서로 다른 목적이 섞이지 않도록 아래 개념을 연결해 둡니다.', conceptIds: ['safe-sink', 'html-sanitization-policy', 'csp', 'retest-and-regression'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.xss] },
  ],
  'w4-validation': [
    { type: 'question', variant: 'lead', title: '수정했다는 말을, 다른 사람이 다시 확인할 수 있게 쓰려면?', body: '좋은 Finding은 공격 문자열을 많이 적은 문서가 아닙니다. 어떤 화면에서 어떤 데이터 경로를 관찰했고, 무엇은 아직 판단하지 않았으며, 무엇을 바꾸고 어떻게 재시험했는지가 분리돼 있어야 합니다.' },
    { type: 'explanation', variant: 'narrative', title: '보고서는 여섯 문장을 서로 다른 칸에 둔다', paragraphs: [
      '첫째는 관찰 사실입니다. 어느 endpoint 또는 화면에서 고정 마커가 어떤 source와 sink를 거쳐 live DOM에 나타났는지를 적습니다. 둘째는 영향 판단입니다. 그 흐름이 특정 사용자 역할과 기능에서 어떤 결과로 이어질 수 있는지, 그리고 그 판단을 위해 어떤 전제가 필요한지를 따로 씁니다.',
      '셋째는 근본 원인입니다. "필터가 약함"처럼 표현하지 말고, 값이 어느 컨텍스트의 interpreting sink에 전달됐는지 적습니다. 넷째는 수정 방향이고, 일반 텍스트·제한 HTML·URL처럼 기능 요구에 맞는 통제를 제안합니다. 다섯째와 여섯째는 재시험 결과와 미확인 항목입니다. 수정 뒤 정상 기능까지 확인했는지, 아직 보지 못한 화면이나 역할은 무엇인지 남깁니다.',
      '이 분리는 보안 문서만을 위한 형식이 아닙니다. 개발자는 어떤 코드를 바꿔야 하는지, QA는 무엇을 회귀 시험해야 하는지, 운영자는 어떤 로그와 정책을 확인해야 하는지를 같은 기록에서 찾을 수 있습니다.',
    ] },
    { type: 'evidence-board', variant: 'report-template', title: '합성 XSS Finding의 증거 지도', sections: [
      { label: '관찰', items: ['입력: 저장된 게시글 제목', 'sink: 목록 renderer의 `innerHTML`', 'context: HTML body', '결과: 고정 마커가 live DOM 구조로 나타남'] },
      { label: '영향 판단', items: ['목록을 보는 사용자 문맥에서 UI·DOM·기능 영향 가능성을 추가 평가'] },
      { label: '수정·재시험', items: ['textContent로 출력 경로 변경', '정상 제목·문법 문자·저장 후 재조회·다른 화면 비교'] },
      { label: '미확인', items: ['운영 환경의 역할별 노출 범위', 'raw HTML 기능의 별도 정책 여부'] },
    ] },
    { type: 'retest', variant: 'report', title: 'Finding에 붙일 재시험 표', intro: '재시험은 "수정됨" 한 줄이 아니라 입력·경로·기대 결과를 나란히 남기는 증거입니다.', rows: [
      { label: '정상 입력', check: '일반 제목 저장·목록 표시', expected: '기존 기능이 유지됨' },
      { label: '문법 문자', check: '일반 텍스트로 출력되는지', expected: 'DOM 구조가 추가되지 않음' },
      { label: '다른 renderer', check: '상세·최근 목록·관리 화면', expected: '같은 출력 정책이 적용됨' },
      { label: '미확인 범위', check: '테스트하지 못한 역할·환경 기록', expected: '추정과 사실이 섞이지 않음' },
    ] },
    { type: 'practice-link', variant: 'readiness', title: '문장을 근거에 맞춰 배치해 보기', body: '아래 내부 활동에서는 합성 Finding 문장을 관찰 사실, 영향 판단, 전제, 원인, 수정, 재시험으로 직접 분류합니다. 이 활동을 마친 뒤에만 내부 XSS sandbox와 허가된 외부 Lab으로 넘어갑니다.', labIds: ['w4-report-evidence', 'w4-reflected'] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-validation-check-01', title: '재시험 범위 고르기', prompt: '목록 renderer를 textContent로 수정한 뒤, 회귀 확인에 반드시 포함할 조합은?', options: ['수정한 화면에서 고정 마커 하나만 다시 본다.', '일반 제목, 문법 문자가 든 텍스트, 저장 후 재조회, 다른 renderer를 비교한다.', '보고서 제목만 바꾼다.'], answer: 1, explanation: '수정 뒤에는 취약한 경로가 사라졌는지와 정상 기능이 유지되는지를 모두 확인해야 합니다. 저장 후 재조회와 다른 renderer를 보지 않으면 같은 데이터가 다른 경로에서 다시 해석될 수 있습니다.' },
    { type: 'concept-ref', variant: 'reference', title: '마지막으로 연결할 개념', intro: 'Week 04 SQLi에서도 이 구분을 그대로 사용합니다. 값과 코드의 경계가 어디서 깨졌는지, 무엇을 증거로 확인했는지부터 적습니다.', conceptIds: ['observation-inference', 'impact-conditions', 'retest-and-regression'] },
    { type: 'sources', title: '근거와 다음 학습', items: [sources.wstg, sources.xss] },
    { type: 'summary', title: 'Week 03을 마치기 전 확인할 것', bullets: ['source·transform·sink·context를 한 흐름에 표시했다.', '관찰 사실과 영향 판단을 다른 문장으로 썼다.', '근본 수정과 CSP 같은 보완 통제를 구분했다.', '정상·문법 문자·다른 renderer를 포함한 재시험을 계획했다.'] },
  ],
})

export const week4ReportEvidenceScenario = reportEvidenceScenario
