const sources = {
  kisa: { label: 'KISA 아카데미 · 사이버보안 직무 소개', url: 'https://academy.kisa.or.kr/cont/job/jobGuide.do', note: '직무 분류와 역할 설명을 확인하는 공식 진로 가이드입니다.' },
  nistRmf: { label: 'NIST SP 800-37 Rev. 2 · Risk Management Framework', url: 'https://csrc.nist.gov/pubs/sp/800/37/r2/final', note: '시스템 수명주기에서 보안·프라이버시 위험을 관리하는 공식 문서입니다.' },
  nistZeroTrust: { label: 'NIST SP 800-207 · Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Zero Trust를 제품명이 아닌 설계 원칙으로 읽기 위한 공식 문서입니다.' },
  nistPrivacy: { label: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: '프라이버시 위험을 조직의 의사결정과 연결하는 공식 프레임워크입니다.' },
  cisaVdp: { label: 'CISA · Vulnerability Disclosure Policy Template', url: 'https://www.cisa.gov/vulnerability-disclosure-policy-template', note: '제보와 허가 범위를 문서화할 때 참고하는 공개 정책 템플릿입니다.' },
  nistGlossary: { label: 'NIST CSRC Glossary', url: 'https://csrc.nist.gov/glossary', note: '보안 용어를 공식 정의와 함께 다시 확인할 수 있습니다.' },
  nistCsF: { label: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: '조직 보안 업무의 Govern, Identify, Protect, Detect, Respond, Recover 흐름을 확인합니다.' },
}

export const week0LessonBlocks = Object.freeze({
  'w0-platform': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '플래그를 찾았다는 기록과, 왜 그 결과가 나왔는지 설명할 수 있다는 기록은 무엇이 다를까?' },
    { type: 'explanation', title: '완료와 이해는 다른 신호다', paragraphs: [
      'SecTrack의 읽음 표시는 자료를 열어 본 사실이고, 실습 완료 표시는 정해진 활동을 끝낸 사실입니다. 둘 다 중요하지만, 명령의 입력과 출력이 왜 연결되는지 설명하는 숙련 근거나 아직 확신하지 못한다는 복습 표시는 별도로 남깁니다.',
      '학습 기록은 정답을 길게 복사하는 문서가 아닙니다. 어떤 환경에서, 어떤 명령이나 입력을 사용했고, 무엇을 관찰했으며, 그 관찰로부터 어떤 결론을 냈는지를 분리합니다. 이 분리는 이후 Linux 조사 노트와 취약점 Finding의 기본 형식이 됩니다.',
    ] },
    { type: 'comparison', title: '학습 상태를 섞지 않기', columns: ['기록', '말해 주는 사실', '말해 주지 않는 것'], rows: [
      ['읽음', '교재를 열어 읽었다.', '원리를 설명하거나 적용할 수 있는지'],
      ['실습 완료', '정해진 교육 활동의 결과를 제출했다.', '원인과 영향의 연결을 이해했는지'],
      ['자기 설명', '현재 언어로 원리를 설명했다.', '외부 검증 없이 항상 정확한지'],
      ['확신도·복습', '다시 봐야 할 위치를 표시했다.', '점수나 감점의 근거'],
    ] },
    { type: 'code', title: '관찰 기록의 최소 단위', language: 'text', code: '환경: CodeCureLAB training shell\n입력: file /srv/codecurelab/app/NOTICE\n관찰: UTF-8 text로 표시됨\n가설: 실행 파일이 아니라 사람이 읽는 공지 파일일 수 있음\n결론: 권한과 실제 위치를 추가로 확인하기 전에는 파일 역할을 단정하지 않음', annotations: ['관찰은 명령이 실제로 보여 준 값이다.', '가설과 결론에는 아직 확인하지 않은 조건을 남긴다.'] },
    { type: 'case', title: 'CodeCureLAB에서 마스킹이 필요한 이유', body: '교육용 접근 로그에도 계정 식별자, 세션 식별자, 파일 이름처럼 맥락에 따라 민감할 수 있는 값이 들어갈 수 있습니다. 기록을 공유할 때에는 필요한 사실만 남기고 인증정보와 개인정보를 지웁니다.', facts: ['Cookie, Authorization, API key, 비밀번호는 원문을 기록하지 않는다.', '학생 번호·이메일·실제 파일명은 필요할 때도 일부를 [REDACTED] 처리한다.', '시간, 명령, 상태 코드, 마스킹된 식별자는 재현성을 유지하는 데 도움이 된다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['힌트를 열었으니 실패했다 → 힌트는 막힌 지점을 기록하는 정보이며, 다음에 스스로 풀기 위한 단서다.', 'AI가 그럴듯하게 설명했으니 사실이다 → 원문 출력과 공식 문서로 확인하기 전에는 가설로 둔다.'] },
    { type: 'checkpoint', id: 'w0-platform-check-01', title: '관찰과 해석 구분', prompt: '`ls -l` 결과에 `-rw-r-----`가 보였다는 문장으로 가장 알맞은 분류는?', options: ['관찰', '영향 결론', '수정 완료'], answer: 0, explanation: '명령 출력에 실제로 나타난 문자열은 관찰입니다. 누가 읽을 수 있는지와 위험 평가는 그 다음 해석 단계입니다.' },
    { type: 'checkpoint', id: 'w0-platform-check-02', title: '기록 고치기', prompt: '“토큰이 보였고 취약하다”라는 메모를 관찰과 다음 확인 항목이 드러나게 다시 써 보세요.', mode: 'short-answer', placeholder: '예: 응답 헤더에 [REDACTED] 형태의 식별자가 보였다. 값의 성격과 노출 범위는 ...' },
    { type: 'warning', title: '공유 전 확인', body: '실제 계정, 다음 단계 비밀번호, 세션 값, Authorization 헤더, API key, 개인정보를 캡처나 코드 블록에 넣지 마세요. 이 과정의 실습은 고정된 로컬 데이터만 사용합니다.' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '관제 분석가, 취약점 진단자, 개발 보안 엔지니어는 모두 “무엇을 봤는가”와 “그래서 무엇을 의미하는가”를 분리해 기록합니다. 근거가 없는 결론은 수정 우선순위와 재시험을 흐리게 만듭니다.' },
    { type: 'practice-link', title: '다음 활동', body: 'ROE를 판별한 뒤 현재 관심 직무를 표시합니다.', labIds: ['w0-roe', 'w0-map'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.nistGlossary, sources.cisaVdp] },
    { type: 'summary', title: '핵심 정리', bullets: ['완료, 숙련, 확신도, 복습은 같은 기록이 아니다.', '환경·입력·관찰·가설·결론을 분리하면 나중에 재검토할 수 있다.', 'AI 답변은 원문 출력과 공식 문서로 검증하는 가설이다.'] },
  ],
  'w0-ethics': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '공개된 웹사이트를 볼 수 있다는 사실은 보안 테스트 권한과 왜 다른가?' },
    { type: 'explanation', title: '기술보다 먼저 확인할 것', paragraphs: [
      '보안 테스트의 출발점은 명시적 허가입니다. 인터넷에 공개되었다는 사실, 회사 이름을 알고 있다는 사실, 교육 과제를 받고 있다는 사실만으로 실제 서비스나 계정에 요청할 권한이 생기지 않습니다.',
      'Rules of Engagement(ROE)는 대상과 계정뿐 아니라 시간, 허용 기법, 금지 기법, 중단 조건, 비상 연락, 증거 처리 방법을 합의한 문서입니다. 하나라도 불명확하면 “안전할 것 같다”라고 추정하지 않고 담당자에게 확인합니다.',
    ] },
    { type: 'comparison', title: '소유권, 접근 가능성, 테스트 허가', columns: ['상황', '바로 실행해도 되는가', '이유'], rows: [
      ['공개 검색 페이지가 보임', '아니오', '공개 접근은 취약점 검증·자동화 요청 허가가 아니다.'],
      ['내가 만든 로컬 컨테이너', '조건부 가능', '자신의 환경이라도 데이터·네트워크 범위를 확인한다.'],
      ['CTF에 제공된 인스턴스', '지침 안에서 가능', '플랫폼의 계정·시간·대상 범위가 허가의 근거다.'],
      ['사내 테스트 계획서에 대상과 시간 명시', '명시 범위에서 가능', '허용 기법과 중단 조건을 함께 따른다.'],
    ] },
    { type: 'code', title: 'ROE 범위 카드 예시', language: 'text', code: '대상: CodeCureLAB training simulator\n계정: 제공된 demo-user만 사용\n시간: 수업 중 지정된 세션\n허용: 고정된 입력·출력 관찰\n금지: 외부 요청, 실제 계정, 데이터 반출\n중단: 예상 밖의 실제 정보가 보이면 즉시 중단·담당자 확인', annotations: ['대상만 적은 문서는 충분한 ROE가 아니다.', '시간·계정·방법·중단·증거 처리를 함께 확인한다.'] },
    { type: 'timeline', title: 'ROE를 읽는 순서', items: [
      { title: '대상과 소유자', body: '호스트, 애플리케이션, API, 계정이 무엇이며 누가 허가했는지 확인한다.' },
      { title: '시간과 방법', body: '테스트 가능한 시간, 허용 요청량, 허용된 도구와 기법을 확인한다.' },
      { title: '금지와 중단 조건', body: '서비스 영향, 데이터 다운로드, 타인 계정, 사회공학 등 금지 범위와 즉시 중단할 신호를 읽는다.' },
      { title: '증거와 연락', body: '최소 증거, 마스킹, 보관·폐기 방법, 긴급 연락 경로를 확인한다.' },
    ] },
    { type: 'case', title: 'CodeCureLAB 연습 범위', body: '이 사이트의 Linux shell, HTTP, DOM 실습은 브라우저 안의 고정 데이터와 시뮬레이터만 다룹니다. “CodeCureLAB”이라는 이름을 실제 도메인이나 시스템에 대입해 요청하지 않습니다.', facts: ['허용: 제공된 명령, 카드, 미리보기 안에서 상태를 관찰하기', '확인 필요: 외부 링크·외부 교육 플랫폼으로 이동하기 전 해당 플랫폼 약관 확인', '금지: 실제 계정·실제 기관·외부 호스트를 대상으로 같은 절차를 반복하기'] },
    { type: 'warning', title: '최소 영향과 최소 증거', body: '정상 동작을 바꾸거나 데이터를 더 많이 모으는 방식은 “증명”이 아닙니다. 교육·제보·사내 진단 모두 필요한 최소 범위에서 멈추고, 개인 정보와 인증정보는 마스킹합니다.' },
    { type: 'misconception', title: '자주 하는 혼동', items: ['범위에 도메인이 있으니 모든 서브도메인과 계정이 포함된다 → 대상, 경로, 계정, 시간, 기법을 각각 확인해야 한다.', '침해를 일으키지 않았으니 허가 없이 검사해도 된다 → 허가 여부는 영향의 크기와 별개인 선행 조건이다.'] },
    { type: 'checkpoint', id: 'w0-ethics-check-01', title: 'ROE 판별', prompt: '“테스트 계정 A로 오늘 14:00~16:00에 제공된 training.example만 확인한다. 데이터 내려받기는 금지”라는 문장에 없는 핵심 항목은?', options: ['비상 연락·중단 조건', '테스트 계정', '시간 범위'], answer: 0, explanation: '대상·계정·시간·데이터 제한은 보이지만, 문제가 생겼을 때 누가 중단을 결정하고 연락받는지는 빠져 있습니다.' },
    { type: 'checkpoint', id: 'w0-ethics-check-02', title: '확인이 필요한 상황', prompt: '교육 플랫폼에서 새 URL을 발견했지만 해당 URL이 과제 인스턴스인지 확실하지 않습니다. 실행 전에 무엇을 확인할지 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '취약점 진단, Red Team, 버그바운티, 사고 대응은 서로 다른 허가 모델을 갖습니다. 좋은 보고서는 기술 결과뿐 아니라 대상·시간·증거 처리·제약을 기록해 결과의 해석 범위를 분명히 합니다.' },
    { type: 'practice-link', title: '다음 활동', body: '허용, 금지, 담당자 확인 필요 문장을 직접 분류합니다.', labIds: ['w0-roe'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.cisaVdp, sources.kisa] },
    { type: 'summary', title: '핵심 정리', bullets: ['공개 접근은 테스트 허가가 아니다.', 'ROE는 대상·계정·시간·기법·금지·중단·연락·증거 처리를 함께 정한다.', '범위가 불명확하면 실행하지 않고 확인한다.'] },
  ],
  'w0-language': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '취약점이 하나 발견됐다는 사실만으로 왜 위험의 크기와 수정 우선순위를 정할 수 없을까?' },
    { type: 'explanation', title: '위험은 약점 하나의 별명이 아니다', paragraphs: [
      '자산은 보호할 가치가 있는 데이터, 서비스, 사람, 평판, 운영 능력입니다. 위협은 자산에 손해를 줄 수 있는 사건이나 행위자이고, 취약점은 위협이 이용할 수 있는 설계·구현·운영상의 약점입니다. 익스플로잇은 그 약점을 실제 동작으로 이용하는 방법이나 코드입니다.',
      '위험은 보통 가능성과 영향의 관계로 판단합니다. 같은 파일 권한 오류라도 파일의 내용, 접근 가능한 주체, 방어 통제, 실제 사용 경로에 따라 위험이 달라집니다. 통제를 적용한 뒤에도 남는 잔여 위험과, 같은 조건에서 수정이 효과가 있었는지 보는 재시험까지 기록해야 사슬이 닫힙니다.',
    ] },
    { type: 'diagram', title: 'CodeCureLAB 위험 사슬', body: '하나의 단어를 외우기보다 앞 단계가 다음 단계를 가능하게 하는지 읽습니다.', nodes: ['자산: 학생 프로필', '위협: 탈취 계정', '취약점: 객체 인가 누락', '악용 조건: 다른 학생 ID를 요청', '영향: 개인정보 열람', '위험: 가능성·영향 평가', '통제: 서버 객체 인가', '잔여 위험·재시험'] },
    { type: 'comparison', title: '비슷하지만 다른 말', columns: ['비교', '왼쪽', '오른쪽'], rows: [
      ['위협과 취약점', '손해를 줄 수 있는 사건·행위자', '그 위협이 이용할 수 있는 약점'],
      ['취약점과 위험', '약한 설계·구현·운영 상태', '가능성과 영향을 포함한 의사결정 대상'],
      ['통제와 제품', '위험을 줄이는 기술·절차·조직 조치', '통제를 구현할 수 있는 한 도구'],
      ['증상과 근본 원인', '현재 보이는 오류나 결과', '그 결과를 만든 구조적 이유'],
    ] },
    { type: 'terminal', sourceType: 'educational-reconstruction', title: '관찰에서 위험으로 너무 빨리 뛰지 않기', command: '$ ls -l /srv/codecurelab/uploads\n-rw-r--r-- 1 app app 2034 assignment-brief.pdf', output: '# 관찰\n기타 사용자에게 읽기 권한이 있다.\n\n# 아직 확인하지 않은 것\n파일에 개인정보가 있는가?\n서버에 로그인 가능한 기타 사용자가 있는가?\n웹 서비스가 이 경로를 직접 노출하는가?', annotations: ['권한 문자열은 약점의 가능성을 보여 주는 관찰이다.', '자산·접근 경로·통제가 확인되기 전에는 영향과 위험을 단정하지 않는다.'] },
    { type: 'case', title: '통제는 위험을 “없애는 버튼”이 아니다', body: 'CodeCureLAB가 객체 인가 검사를 추가해도 운영자 계정 탈취, 로그 노출, 잘못된 역할 설정 같은 다른 경로는 남을 수 있습니다. 그래서 통제의 위치, 적용 범위, 실패 시 행동, 재시험 조건을 함께 적습니다.', facts: ['예방 통제: 서버가 요청자와 대상 객체의 관계를 검증한다.', '탐지 통제: 반복된 권한 거부와 이상 조회를 기록해 검토한다.', '대응·복구 통제: 세션 무효화와 접근 검토 절차를 준비한다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['CVE가 있으면 항상 높은 위험이다 → 설치 여부, 노출 경로, 통제, 자산 가치를 같이 봐야 한다.', '통제를 적용했으니 위험은 0이다 → 통제 범위 밖의 경로와 실패 가능성은 잔여 위험으로 남는다.'] },
    { type: 'checkpoint', id: 'w0-language-check-01', title: '용어 연결', prompt: '“관리자 기능에 서버 측 객체 인가가 없다”에 가장 가까운 용어는?', options: ['취약점', '자산', '재시험'], answer: 0, explanation: '서버 측 인가 누락은 위협이 이용할 수 있는 설계·구현상의 약점입니다.' },
    { type: 'checkpoint', id: 'w0-language-check-02', title: '위험 사슬 작성', prompt: '과제 업로드 기능 하나를 골라 자산, 위협, 취약점, 통제, 재시험을 한 줄씩 연결해 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: 'GRC는 위험과 통제의 우선순위를 정하고, AppSec은 코드와 설계에서 원인을 줄이며, SOC·IR은 탐지와 대응의 근거를 남깁니다. 용어 사슬을 공유하면 각 직무가 같은 문제를 다른 산출물로 다룰 수 있습니다.' },
    { type: 'practice-link', title: '다음 활동', body: '직무 지도에서 관심 역할과 필요한 기초 개념을 연결합니다.', labIds: ['w0-map'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.nistRmf, sources.nistGlossary] },
    { type: 'summary', title: '핵심 정리', bullets: ['위협은 손해를 줄 수 있는 사건·행위자이고, 취약점은 이용 가능한 약점이다.', '위험 평가는 자산, 노출, 가능성, 영향, 통제를 함께 본다.', '통제 적용 뒤에는 잔여 위험과 재시험 조건을 남긴다.'] },
  ],
  'w0-goals': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '로그인에 성공한 사용자가 다른 학생의 과제를 열지 못하게 하는 일은 왜 인증이 아니라 인가의 문제일까?' },
    { type: 'explanation', title: '보안 목표를 기능에 붙이기', paragraphs: [
      '기밀성은 허가되지 않은 공개를 막고, 무결성은 허가되지 않은 변경을 막거나 추적하며, 가용성은 필요한 사용자가 필요한 시점에 서비스를 이용할 수 있게 합니다. CIA는 서로 경쟁할 수 있습니다. 예를 들어 긴급 복구 계정은 가용성을 돕지만 기밀성과 책임추적성을 약화시킬 수 있어 별도 통제가 필요합니다.',
      '식별은 “나는 누구다”라고 주장하는 단계, 인증은 그 주장을 확인하는 단계, 인가는 확인된 주체에게 어떤 행동을 허용할지 결정하는 단계입니다. 책임추적성은 중요한 행동을 나중에 검토할 수 있게 만드는 성질입니다.',
    ] },
    { type: 'diagram', title: '요청을 판단하는 신뢰 경계', nodes: ['브라우저의 사용자 입력', 'Cookie·자격 증명 제시', '서버 인증', '서버 객체 인가', '업무 처리·로그 기록', '응답과 DOM 갱신'] },
    { type: 'comparison', title: '식별, 인증, 인가, 책임추적성', columns: ['개념', '질문', 'CodeCureLAB 예'], rows: [
      ['식별', '누구라고 주장하는가?', 'student-102라는 사용자 이름을 입력한다.'],
      ['인증', '그 주장에 근거가 있는가?', '비밀번호·MFA 등으로 로그인 주체를 확인한다.'],
      ['인가', '이 행동을 허용할 것인가?', 'student-102가 assignment-7을 읽어도 되는지 서버가 검사한다.'],
      ['책임추적성', '나중에 무엇을 검토할 수 있는가?', '누가 언제 어떤 결과 코드로 요청했는지 마스킹된 로그를 남긴다.'],
    ] },
    { type: 'code', title: '안전한 실패의 예', language: 'text', code: 'if (!canReadAssignment(request.user, assignmentId)) {\n  audit.log("assignment.read.denied", { user: request.user.id, assignmentId })\n  return response.status(403).send("Access denied")\n}', annotations: ['클라이언트가 보낸 사용자 ID나 버튼 상태를 권한 근거로 믿지 않는다.', '서버가 요청 주체와 대상 객체를 다시 확인한다.', '거부 사실은 기록하되 인증정보와 개인정보를 로그에 복사하지 않는다.'] },
    { type: 'case', title: '한 기능을 CIA로 읽기', body: '과제 업로드 기능은 파일을 올리는 화면 하나처럼 보이지만, 개인정보가 담긴 첨부 파일과 제출 시점, 피드백의 변경 이력, 마감 직전 서비스 가용성을 함께 다룹니다.', facts: ['기밀성: 제출 파일을 해당 학생·교직원만 보게 한다.', '무결성: 제출자와 제출 시점, 피드백 변경을 검토 가능하게 한다.', '가용성: 마감 시간에 정상 사용자에게 서비스가 계속 제공되게 한다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['로그인만 하면 권한 검사가 끝난다 → 로그인 뒤에도 각 데이터와 기능마다 인가 판단이 필요하다.', 'Zero Trust는 특정 보안 제품이다 → 요청마다 주체·장치·상황을 확인하고 최소 권한을 적용하는 설계 원칙이다.'] },
    { type: 'checkpoint', id: 'w0-goals-check-01', title: '인증과 인가', prompt: '정상적으로 로그인한 학생이 다른 학생의 과제 URL을 요청했을 때 서버가 확인해야 하는 것은?', options: ['해당 과제에 대한 객체 인가', '브라우저 색상 설정', 'DNS 캐시'], answer: 0, explanation: '로그인 성공은 인증 결과입니다. 특정 대상에 대한 허용 여부는 서버의 객체 인가 판단입니다.' },
    { type: 'checkpoint', id: 'w0-goals-check-02', title: '통제 고르기', prompt: 'CodeCureLAB의 관리자 공지 수정 기능에 최소 권한과 책임추적성을 함께 적용하는 방법을 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: 'IAM, AppSec, 클라우드 보안, 개인정보보호, 감사는 서로 다른 위치에서 인증·인가·로그·신뢰 경계를 검토합니다. 설계 리뷰에서는 “누가, 어떤 근거로, 어떤 대상에, 어느 서버에서”가 반복 질문이 됩니다.' },
    { type: 'practice-link', title: '다음 활동', body: '직무 지도에서 설계·검증·탐지 역할이 같은 통제를 어떻게 다르게 다루는지 살펴봅니다.', labIds: ['w0-map'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.nistZeroTrust, sources.nistRmf] },
    { type: 'summary', title: '핵심 정리', bullets: ['CIA는 기밀성·무결성·가용성을 기능과 자산에 연결해 읽는 틀이다.', '식별·인증·인가는 순서가 다른 개념이며 서버 인가는 매 요청의 대상과 함께 확인한다.', '최소 권한, 기본 거부, 심층 방어, 안전한 실패는 함께 적용한다.'] },
  ],
  'w0-flow': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '취약점을 찾는 사람, 수정하는 사람, 탐지하는 사람, 감사하는 사람은 어떻게 같은 위험을 다른 산출물로 다룰까?' },
    { type: 'explanation', title: '기업 보안은 한 번의 점검으로 끝나지 않는다', paragraphs: [
      '보안 업무는 공격과 방어라는 두 단어보다 넓습니다. 사업과 서비스 요구가 정해지면 보안 기획·GRC·개인정보 담당자가 요구사항과 위험 기준을 정리하고, 아키텍처·제품보안·클라우드·IAM 담당자가 통제를 설계합니다. 개발과 운영 중에는 취약점 진단과 코드 검토, 탐지 운영, 사고 대응, 감사, 재시험이 이어집니다.',
      'Offensive와 Defensive는 상대를 이기는 팀 이름이 아니라 관점입니다. Offensive는 허가된 범위에서 공격 경로와 영향을 검증하고, Defensive는 예방·탐지·분석·대응·복구를 운영합니다. Purple은 두 관점의 관찰을 규칙, 설계, 훈련으로 연결하는 협업입니다.',
    ] },
    { type: 'timeline', title: 'CodeCureLAB 보안 업무 수명주기', items: [
      { title: '서비스 요구와 자산 정리', body: '공지·프로필·과제·관리자 기능, 개인정보, 가용성 목표를 적는다.' },
      { title: '위험·요구사항·설계', body: 'GRC·개인정보·아키텍처 담당자가 인가, 로그, 보유 기간, 신뢰 경계를 검토한다.' },
      { title: '구현과 검증', body: '개발·AppSec·취약점 진단이 코드, 설정, 교육 환경에서 통제의 동작을 확인한다.' },
      { title: '운영과 탐지', body: 'SOC·플랫폼·클라우드 담당자가 정상 기준선과 이상 신호를 비교한다.' },
      { title: '대응·복구·개선', body: '사고 대응과 포렌식이 증거를 보존하고 제한·복구·원인 분석·재발 방지를 연결한다.' },
      { title: '감사와 재시험', body: '수정된 통제와 운영 절차가 같은 조건에서 실제로 작동하는지 다시 확인한다.' },
    ] },
    { type: 'comparison', title: '직무 관점과 대표 산출물', columns: ['관점', '핵심 질문', '대표 산출물'], rows: [
      ['GRC·개인정보', '무엇을 보호하고 어떤 기준을 따를까?', '정책, 위험평가, 처리 기준, 감사 증적'],
      ['Security Engineering·AppSec', '어디에 어떤 통제를 구현할까?', '위협 모델, 설계 검토, 수정안, 가드레일'],
      ['Offensive·진단', '허가 범위에서 어떤 경로가 실제로 가능한가?', 'PoC, 영향 분석, Finding, 재시험 결과'],
      ['Defensive·SOC·IR', '무엇을 탐지하고 어떻게 제한·복구할까?', '탐지 규칙, 타임라인, 플레이북, 사후 개선'],
    ] },
    { type: 'code', title: 'Finding이 개선으로 이어지는 기록', language: 'text', code: '관찰: 요청 주체와 과제 소유자의 관계를 서버가 확인하지 않음\n영향 가설: 허가되지 않은 과제 조회 가능성\n수정 책임: 애플리케이션 팀\n검증 기준: 다른 사용자 과제 요청은 403, 본인 과제 요청은 정상 응답\n재시험: 수정 후 두 조건과 인접 기능을 확인', annotations: ['발견 사실, 영향 가설, 수정 책임, 검증 기준을 한 문장으로 섞지 않는다.', '재시험 기준은 수정 전에 합의할수록 결과가 명확해진다.'] },
    { type: 'case', title: '한 Finding이 이어지는 방식', body: 'CodeCureLAB 과제 조회에서 서버 인가가 빠졌다는 가상의 Finding은 하나의 팀만의 일이 아닙니다. 진단자는 재현 조건과 영향을 기록하고, 개발자는 서버 측 검사를 추가하며, 운영자는 거부·오류 로그를 관찰하고, GRC는 위험 수용 여부와 재시험 증적을 검토합니다.', facts: ['같은 사실도 직무마다 산출물과 책임 범위가 다르다.', '역할 이름보다 반복 업무와 남기는 결과물을 먼저 비교한다.', '재시험은 처음 Finding을 낸 사람만의 의무가 아니라 통제 검증의 마지막 연결이다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['Red Team은 취약점 목록만 만드는 직무다 → 공격 경로와 방어 공백을 허가 범위에서 검증하고 개선 근거를 남긴다.', 'Blue Team은 도구 알림만 보는 직무다 → 예방·탐지·분석·대응·복구와 개선을 지속적으로 운영한다.'] },
    { type: 'checkpoint', id: 'w0-flow-check-01', title: '산출물 연결', prompt: '수정 후 같은 조건으로 다시 확인한 결과를 가장 직접적으로 남기는 산출물은?', options: ['재시험 결과', '서비스 로고', '개발 일정표'], answer: 0, explanation: '재시험은 수정 전과 같은 조건, 필요한 회귀 조건에서 통제가 효과가 있었는지 남기는 검증 기록입니다.' },
    { type: 'checkpoint', id: 'w0-flow-check-02', title: '역할 나누기', prompt: 'CodeCureLAB의 “로그에 세션 식별자가 남는다”는 관찰을 GRC, 개발 보안, SOC가 각각 어떤 다음 행동으로 다룰지 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: 'KISA의 공식 직무 가이드는 보안제품 개발, 악성코드 분석, 컨설팅, 보안관리, CISO, 포렌식, 사고 대응 등 서로 다른 역할을 소개합니다. 직무 탐색에서는 도구 이름보다 실제 업무, 협업 대상, 대표 산출물을 함께 보는 편이 정확합니다.' },
    { type: 'practice-link', title: '다음 활동', body: '직무 지도에서 한 역할을 골라 연결된 개념과 결과물을 확인합니다.', labIds: ['w0-map'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.kisa, sources.nistCsF] },
    { type: 'summary', title: '핵심 정리', bullets: ['보안 업무는 요구사항·설계·검증·운영·대응·재시험으로 이어진다.', 'Offensive, Defensive, Purple은 기술 목록이 아니라 검증과 개선의 관점이다.', '직무는 이름보다 실제 업무와 산출물로 비교한다.'] },
  ],
  'w0-system': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '브라우저의 버튼 클릭이 파일, 네트워크, 프로세스, 메모리와 어떻게 이어지며 Week 1~3의 어디에서 다시 만나게 될까?' },
    { type: 'explanation', title: '다음 주차를 위한 얕은 시스템 지도', paragraphs: [
      '프로그램은 CPU가 실행하는 명령의 집합이고, 프로세스는 실행 중인 프로그램이 사용하는 메모리, 파일, 네트워크 연결 같은 자원의 단위입니다. 사용자 프로그램은 운영체제 커널에 직접 하드웨어를 다루라고 명령하지 않고, 시스템 호출을 통해 파일·네트워크·메모리 작업을 요청합니다.',
      '파일 시스템은 경로와 메타데이터로 파일을 구성하고, 권한은 어떤 사용자와 그룹이 읽기·쓰기·실행할 수 있는지 제한합니다. 브라우저는 네트워크 요청으로 응답을 받아 HTML을 DOM으로 만들고 JavaScript를 실행합니다. 여기서는 전체 구현을 외우지 않고, 어느 층에서 관찰할 수 있는지만 잡습니다.',
    ] },
    { type: 'diagram', title: 'CodeCureLAB의 관찰 지점', nodes: ['브라우저: URL·Cookie·DOM', '네트워크: HTTP 요청·응답', 'Linux 프로세스: 앱·로그', '파일 시스템: 설정·업로드·권한', '커널: 파일·소켓·메모리 작업'] },
    { type: 'terminal', title: 'Linux에서 프로세스와 파일을 각각 보기', command: '$ file /srv/codecurelab/app/server\n$ ps -o pid,user,comm -C codecurelab-app', output: '/srv/codecurelab/app/server: ELF 64-bit LSB pie executable\n  PID USER     COMMAND\n 4242 app      codecurelab-app', annotations: ['`file`은 내용의 형식을 추정해 보여 주며, 권한이나 안전성을 판정하지 않는다.', '`ps`는 실행 중인 프로세스 정보를 보지만 파일의 전체 내용을 보여 주지는 않는다.'] },
    { type: 'comparison', title: 'Week 1~3에서 다시 만나는 층', columns: ['층', '이번에 알아둘 질문', '연결 주차'], rows: [
      ['파일 시스템', '경로는 어디서 시작하고 권한은 누구에게 적용되는가?', 'Week 1·2 Linux'],
      ['프로세스·소켓', '어떤 프로그램이 파일과 네트워크를 사용하는가?', 'Week 1·6~8'],
      ['HTTP·브라우저', '요청·응답·Cookie·DOM은 어디에서 바뀌는가?', 'Week 2·3·4'],
      ['메모리·CPU', '실행 상태와 주소 공간은 어떻게 나뉘는가?', 'Week 6~9 Pwn'],
    ] },
    { type: 'case', title: '한 요청의 여러 흔적', body: '학생이 공지를 열면 브라우저는 HTTP 요청을 만들고, Linux 애플리케이션 프로세스가 설정과 데이터에 접근해 응답을 만들며, 접근 로그에 최소한의 운영 기록을 남깁니다. Week 1은 경로·파일·권한·로그 기초를, Week 2는 HTTP와 DOM을 더 깊게 봅니다.', facts: ['같은 사건을 브라우저, HTTP 원문, 프로세스, 로그, 파일 권한에서 서로 다르게 관찰할 수 있다.', '한 층의 출력만으로 다른 층의 상태를 추정하지 않는다.', '민감한 값은 어느 층의 기록에서도 마스킹한다.'] },
    { type: 'warning', title: '이 모듈의 범위', body: '이 과정은 프로세스 조작, 권한 상승, 메모리 공격을 여기서 수행하지 않습니다. Week 1~2는 관찰과 안전한 기초 모델에 집중하고, 시스템·Pwn 심화는 Week 6 이후의 허가된 교육 환경에서 다룹니다.' },
    { type: 'misconception', title: '자주 하는 혼동', items: ['파일이 실행 가능하니 실행 중이다 → 파일의 권한·형식과 실행 중인 프로세스는 다른 사실이다.', '브라우저 화면에 안 보이니 서버도 값을 모른다 → HTTP 요청, 서버 처리, 로그, DOM은 서로 다른 관찰 지점이다.'] },
    { type: 'checkpoint', id: 'w0-system-check-01', title: '관찰 지점 고르기', prompt: '실행 중인 애플리케이션의 프로세스 이름과 PID를 확인하려면 무엇을 먼저 보는가?', options: ['프로세스 목록', 'HTML DOM', '파일 확장자만'], answer: 0, explanation: 'PID와 실행 중인 명령은 프로세스 목록에서 관찰합니다. 파일 형식이나 DOM은 다른 층의 정보입니다.' },
    { type: 'checkpoint', id: 'w0-system-check-02', title: '층 나누기', prompt: '“브라우저에서 공지 목록이 갱신됐다”는 사건을 파일 시스템, HTTP, DOM 관찰로 각각 한 줄씩 나눠 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '침해사고 분석, Linux 운영, AppSec, 포렌식, 취약점 진단은 모두 같은 시스템을 다른 층에서 봅니다. 다음 실습에서는 “지금 본 값이 어느 층의 사실인가”를 기록하는 습관을 만듭니다.' },
    { type: 'practice-link', title: '다음 활동', body: 'Week 1에서는 가상 Linux 환경에서 경로, 파일, 권한의 출력을 직접 읽습니다.', labIds: ['w1-treasure'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.nistRmf, sources.kisa] },
    { type: 'summary', title: '핵심 정리', bullets: ['프로세스, 파일 시스템, 네트워크, 브라우저는 서로 다른 관찰 층이다.', '사용자 프로그램은 시스템 호출을 통해 커널의 파일·네트워크 자원을 사용한다.', 'Week 1~3은 경로·권한·로그·HTTP·DOM을 차례로 연결한다.'] },
  ],
})
