const sources = {
  coreutils: { label: 'GNU Coreutils Manual', url: 'https://www.gnu.org/software/coreutils/manual/html_node/', note: '권한, 스트림, 텍스트 처리 명령의 공식 설명입니다.' },
  findutils: { label: 'GNU Findutils Manual', url: 'https://www.gnu.org/software/findutils/manual/', note: 'find, xargs와 안전한 파일명 처리 옵션을 확인합니다.' },
  curl: { label: 'curl man page', url: 'https://curl.se/docs/manpage.html', note: 'curl 옵션과 HTTP 전송 동작을 확인합니다.' },
  git: { label: 'Git Documentation', url: 'https://git-scm.com/docs', note: '작업 트리, staging, commit, history의 공식 문서입니다.' },
  chrome: { label: 'Chrome DevTools · Network', url: 'https://developer.chrome.com/docs/devtools/network', note: '브라우저가 실제로 만든 요청·응답을 보는 공식 안내입니다.' },
  burp: { label: 'PortSwigger Burp Suite Documentation', url: 'https://portswigger.net/burp/documentation/desktop/tools/proxy', note: 'Proxy와 Repeater를 허가된 범위에서 사용하는 공식 문서입니다.' },
  gnuBash: { label: 'GNU Bash Reference Manual', url: 'https://www.gnu.org/software/bash/manual/', note: '리다이렉션과 파이프의 셸 해석을 확인합니다.' },
}

const blockSet = ({ id, question, explanation, terminal, comparison, caseBody, facts, misconception, checks, work, labs, sourceItems, summary, warning }) => [
  { type: 'question', title: '이 모듈이 답할 질문', body: question },
  { type: 'explanation', title: '핵심 원리', paragraphs: explanation },
  { type: 'terminal', title: terminal.title, command: terminal.command, output: terminal.output, annotations: terminal.annotations },
  { type: 'comparison', title: comparison.title, columns: comparison.columns, rows: comparison.rows },
  { type: 'case', title: '사례', body: caseBody, facts },
  { type: 'misconception', title: '자주 하는 혼동', items: misconception },
  { type: 'checkpoint', id: `${id}-check-01`, title: checks[0].title, prompt: checks[0].prompt, options: checks[0].options, answer: checks[0].answer, explanation: checks[0].explanation, answerGuide: checks[0].answerGuide || checks[0].explanation },
  { type: 'checkpoint', id: `${id}-check-02`, title: checks[1].title, prompt: checks[1].prompt, mode: 'short-answer', placeholder: checks[1].placeholder, answerGuide: checks[1].answerGuide || '예시 답: 앞의 명령 형식과 출력 예시를 기준으로 대상, 확인한 값, 다음 검증 순서를 포함합니다.' },
  ...(warning ? [{ type: 'warning', title: warning.title, body: warning.body }] : []),
  { type: 'work-context', title: '보안 업무에서의 사용', body: work },
  { type: 'practice-link', title: '다음 활동', body: '관찰값과 해석을 분리해 다음 교육 실습에 적용합니다.', labIds: labs },
  { type: 'sources', title: '공식 참고자료', items: sourceItems },
  { type: 'summary', title: '핵심 정리', bullets: summary },
]

export const week2LessonBlocks = Object.freeze({
  'w2-permissions': blockSet({
    id: 'w2-permissions',
    question: '권한 문자열 `-rw-r-----`를 보고 누가 무엇을 할 수 있는지, 그리고 왜 더 넓은 권한이 항상 해결책이 아닌지 어떻게 설명할까?',
    explanation: ['권한 문자열은 파일 유형 뒤에 소유자·그룹·기타의 `rwx`를 세 글자씩 표시합니다. 숫자 표기는 `r=4`, `w=2`, `x=1`을 각 주체별로 더한 값입니다. 예를 들어 `640`은 소유자 6(`rw-`), 그룹 4(`r--`), 기타 0(`---`)입니다.', '`chmod`는 모드 비트를 바꾸고, `chown`·`chgrp`는 소유 주체를 바꿉니다. `umask`는 새 항목의 기본 권한에서 제거할 비트를 뜻합니다. `sudo`는 오류를 피하는 만능 명령이 아니라 승인된 관리 작업을 명시적으로 수행할 때만 사용합니다. SUID·SGID·Sticky Bit는 존재와 목적을 식별하되 이 과정에서는 권한 상승 실습으로 확장하지 않습니다.'],
    terminal: { title: '기호 권한을 숫자 권한으로 읽기', command: '$ stat -c "%a %A %U %G %n" /srv/codecurelab/uploads\n750 drwxr-x--- app uploaders /srv/codecurelab/uploads\n$ stat -c "%a %A %U %G %n" /srv/codecurelab/uploads/brief.pdf', output: '640 -rw-r----- app uploaders /srv/codecurelab/uploads/brief.pdf', annotations: ['750은 소유자 `rwx`, 그룹 `r-x`, 기타 `---`입니다.', '파일과 디렉터리에서 `x`의 의미가 다르므로 대상 유형을 함께 읽습니다.', '소유자·그룹 변경은 서비스 계정과 운영 절차에 영향을 줄 수 있습니다.'] },
    comparison: { title: '권한 관련 명령의 역할', columns: ['명령', '바꾸는 것', '확인할 점'], rows: [['`chmod 640 file`', '권한 비트', '필요한 읽기·쓰기·실행만 남는가?'], ['`chown app file`', '소유 사용자', '서비스 프로세스가 실제로 어떤 계정으로 실행되는가?'], ['`chgrp uploaders file`', '소유 그룹', '그룹 구성원과 업무 책임이 맞는가?'], ['`umask 027`', '새 항목 기본 모드에서 제거할 비트', '기본값이 파일·디렉터리 생성 방식과 맞는가?']] },
    caseBody: 'CodeCureLAB의 과제 파일은 앱 계정이 쓰고 업로더 그룹이 필요한 작업을 하며, 기타 사용자는 접근하지 못하도록 설계할 수 있습니다. “모든 사용자가 쓰게” 하는 수정은 장애를 잠시 피할 수 있어도 파일 교체·삭제와 감사 범위를 넓힙니다.',
    facts: ['권한 변경 전에는 실제 소유자·그룹·서비스 계정·경로를 확인한다.', '허용과 거부를 각각 테스트해 최소 권한이 작동하는지 본다.', '특수 권한 비트는 목적과 위험을 문서화하고 승인된 환경에서만 변경한다.'],
    misconception: ['`777`이면 권한 문제를 해결한다 → 필요한 주체 외에도 모든 사용자의 변경 가능 범위를 넓힌다.', '소유자가 root면 안전하다 → 실제 서비스 계정, 그룹, 실행 경로와 접근 필요성을 같이 본다.'],
    checks: [{ title: '숫자 권한', prompt: '`750`에서 그룹이 할 수 있는 행동은?', options: ['읽기와 경로 탐색', '읽기와 쓰기', '어떤 접근도 할 수 없음'], answer: 0, explanation: '가운데 5는 `r-x`입니다. 디렉터리라면 목록 읽기와 경로 탐색에 관여합니다.' }, { title: '수정안 작성', prompt: '과제 파일을 앱이 쓰고 담당 교직원 그룹이 읽으며 기타 사용자는 접근하지 못하게 하는 권한·검증 계획을 적어 보세요.' }],
    work: 'Linux 권한은 클라우드 IAM, 데이터베이스 권한, 애플리케이션 인가와 같은 최소 권한 원칙을 다른 층에서 구현한 사례입니다. 운영 변경에는 승인, 영향, 되돌림, 허용·거부 재시험이 필요합니다.', labs: ['w2-permission-lab'], sourceItems: [sources.coreutils], summary: ['권한은 파일 유형과 소유자·그룹·기타를 함께 읽는다.', '숫자 권한은 `r=4`, `w=2`, `x=1`의 합이다.', '더 큰 권한이 아니라 필요한 주체·행동과 재시험으로 수정안을 만든다.'],
  }),
  'w2-streams': blockSet({
    id: 'w2-streams', question: '정상 출력과 오류 출력을 섞지 않고, 필요한 결과만 다음 명령으로 전달하려면 어떤 스트림을 연결해야 할까?',
    explanation: ['프로세스에는 기본 입력 stdin(0), 정상 출력 stdout(1), 오류 출력 stderr(2)가 있습니다. 파이프 `|`는 앞 명령의 stdout을 다음 명령의 stdin에 연결합니다. 따라서 오류 메시지는 기본적으로 파이프 뒤 명령으로 전달되지 않습니다.', '`>`는 stdout을 새 파일에 쓰고, `>>`는 이어 쓰며, `2>`는 stderr만 보냅니다. `2>&1`은 그 시점의 stdout이 가는 곳으로 stderr도 보냅니다. 순서가 의미를 바꿀 수 있으므로 결과 파일과 화면 출력을 실제로 비교합니다. `tee`는 입력을 화면과 파일에 동시에 보낼 때 유용합니다.'],
    terminal: { title: 'stdout과 stderr를 분리해 보기', command: '$ codecurelab-check --all > result.txt 2> errors.txt\n$ wc -l result.txt errors.txt\n$ cat errors.txt', output: '  12 result.txt\n   1 errors.txt\n  13 total\nwarning: optional training fixture is absent', annotations: ['정상 결과와 경고를 나눠야 후속 파이프라인이 오류 문장을 데이터로 세지 않습니다.', '`2>&1`은 리다이렉션 순서에 따라 stdout의 현재 목적지를 따른다는 점을 기억합니다.', '기록 공유 전에는 파일에 민감정보가 없는지 확인합니다.'] },
    comparison: { title: '리다이렉션과 파이프', columns: ['표기', '흐름', '언제 쓰는가'], rows: [['`cmd > out.txt`', 'stdout → 파일', '정상 결과를 저장할 때'], ['`cmd 2> err.txt`', 'stderr → 파일', '오류·경고를 별도 검토할 때'], ['`cmd > out.txt 2>&1`', 'stdout·stderr → 같은 파일', '전체 실행 기록이 필요할 때'], ['`cmd | next`', '앞 stdout → 다음 stdin', '단계별 텍스트 처리를 연결할 때'], ['`cmd | tee out.txt`', 'stdout → 화면과 파일', '관찰하면서 결과를 남길 때']] },
    caseBody: '배치 점검이 정상 파일 목록과 경고를 함께 낸다면, 경고를 결과 집계에 섞지 않고 별도 파일에서 확인해야 합니다. 로그 파이프라인은 “어떤 스트림을 다음 단계 데이터로 삼았는가”를 기록해야 재현됩니다.', facts: ['stdout과 stderr는 의미가 다른 두 출력 채널이다.', '파이프는 기본적으로 stdout만 연결한다.', '긴 명령은 중간 결과·파일 크기·줄 수를 단계마다 확인한다.'],
    misconception: ['파이프는 화면에 보이는 모든 글자를 전달한다 → 기본적으로 stdout만 다음 명령의 stdin으로 연결한다.', '`2>&1`은 항상 같은 결과다 → 앞선 stdout 리다이렉션의 위치에 따라 목적지가 달라질 수 있다.'],
    checks: [{ title: '스트림 선택', prompt: '명령의 오류 메시지만 `errors.txt`에 기록하려면?', options: ['`cmd 2> errors.txt`', '`cmd > errors.txt`', '`cmd | errors.txt`'], answer: 0, explanation: '파일 기술자 2는 stderr입니다.' }, { title: '파이프라인 계획', prompt: '로그 집계 명령에서 stderr를 결과 데이터와 분리해야 하는 이유와 확인 방법을 적어 보세요.' }],
    work: '보안 자동화, CI 검사, 관제 스크립트는 성공 결과와 오류·경고를 분리해 처리합니다. 그렇지 않으면 파서가 오류 문장을 정상 이벤트로 세거나 중요한 실패를 놓칠 수 있습니다.', labs: [], sourceItems: [sources.gnuBash, sources.coreutils], summary: ['stdin·stdout·stderr는 역할이 다른 기본 스트림이다.', '파이프는 stdout을 다음 명령의 stdin으로 연결한다.', '리다이렉션의 대상과 순서를 기록하고 중간 출력을 검증한다.'],
  }),
  'w2-text': blockSet({
    id: 'w2-text', question: '로그에서 “404가 많다”는 결론을 내리기 전에 어떤 중간 결과를 확인해야 할까?',
    explanation: ['`grep`은 텍스트 줄을, `find`는 파일 시스템 항목을 조건으로 찾습니다. `cut`, `tr`, `sort`, `uniq`, `wc`는 각 단계에서 데이터를 줄이고 바꾸고 세는 역할을 합니다. 파이프라인은 한 줄로 짧게 쓰는 기술이 아니라 각 단계의 입력·출력 계약을 만드는 방식입니다.', '`xargs`는 표준 입력을 명령 인자로 바꾸므로 공백·개행이 있는 파일명과 의도하지 않은 대상에 특히 주의합니다. 파일명을 다룰 때는 `find -print0`과 `xargs -0`처럼 NUL 구분자를 사용하거나, 더 안전하게 `find -exec`을 검토합니다.'],
    terminal: { title: '404 경로를 단계별로 요약하기', command: '$ grep " 404" access.log\n$ grep " 404" access.log | cut -d" " -f3\n$ grep " 404" access.log | cut -d" " -f3 | sort | uniq -c', output: '10.0.0.4 GET /missing 404\n10.0.0.9 GET /missing 404\n10.0.0.7 GET /missing 404\n\n/missing\n/missing\n/missing\n\n      3 /missing', annotations: ['첫 단계는 상태 코드가 404인 원본 줄을 확인합니다.', '둘째 단계는 경로 열만 선택합니다.', '정렬 뒤 `uniq -c`가 같은 값을 올바르게 셀 수 있습니다.'] },
    comparison: { title: '텍스트 도구의 역할', columns: ['도구', '입력·출력 단위', '실수 줄이기'], rows: [['`grep -n pattern file`', '텍스트 줄', '줄 번호와 원본 줄을 먼저 본다.'], ['`find path -type f`', '파일 시스템 항목', '시작 경로와 타입을 제한한다.'], ['`cut -d":" -f2`', '구분자 기반 필드', '구분자가 데이터 안에도 있는지 확인한다.'], ['`sort | uniq -c`', '정렬된 값의 묶음', '반드시 정렬 뒤에 빈도를 센다.'], ['`wc -l`', '줄 수', '필터 결과 규모를 빠르게 확인한다.']] },
    caseBody: 'CodeCureLAB 접근 로그에서 404가 반복된다고 해도 공격·오류·정상 오타를 바로 단정하지 않습니다. 먼저 어떤 경로, 어느 시간, 어느 사용자 유형에서 반복됐는지 후보를 줄이고 애플리케이션 변경·배포·요청 맥락을 확인합니다.', facts: ['집계는 관찰을 요약할 뿐 원인을 증명하지 않는다.', '각 파이프 단계는 원본·필터·필드·정렬·집계로 설명할 수 있어야 한다.', '로그에는 개인정보와 토큰이 있을 수 있으므로 최소 필드만 사용한다.'],
    misconception: ['한 줄 파이프가 짧으면 더 좋은 분석이다 → 중간 출력이 검증되지 않으면 잘못된 필드·조건을 놓치기 쉽다.', '`xargs`는 어떤 파일명에도 안전하다 → 공백·개행·옵션처럼 해석될 값에는 별도 처리와 범위 확인이 필요하다.'],
    checks: [{ title: '순서 고르기', prompt: '중복 경로의 빈도를 세기 전에 필요한 단계는?', options: ['`sort`', '`rm`', '`chmod`'], answer: 0, explanation: '`uniq -c`는 인접한 같은 값을 세므로 일반적으로 먼저 정렬합니다.' }, { title: '분석 한계', prompt: '`/missing`이 세 번 나왔다는 결과만으로 무엇을 말할 수 있고 무엇을 말할 수 없는지 적어 보세요.' }],
    work: 'SOC, SRE, 포렌식 분석에서는 작은 쿼리와 파이프라인의 중간 결과를 보관합니다. 재현 가능한 필터는 다른 분석가가 오탐·누락을 확인하고 탐지 규칙으로 발전시키는 근거가 됩니다.', labs: ['w2-log-lab', 'w2-bandit'], sourceItems: [sources.coreutils, sources.findutils], summary: ['`find`는 경로, `grep`은 텍스트 줄을 다룬다.', '파이프라인은 단계별 입력·출력 검증이 핵심이다.', '집계 결과는 관찰 요약이며 원인 결론에는 추가 맥락이 필요하다.'],
  }),
  'w2-binary': blockSet({
    id: 'w2-binary', question: 'Base64 문자열을 봤을 때 왜 “암호화되어 안전하다”라고 결론내리면 안 될까?',
    explanation: ['파일 형식은 이름 확장자가 아니라 실제 바이트와 구조를 함께 봐야 합니다. `file`은 형식 후보를, `strings`는 인쇄 가능한 문자열 후보를, `xxd`나 `hexdump`는 바이트와 문자 표현을 보여 줍니다. 이 도구들은 관찰을 돕지만 파일의 전체 의미나 안전성을 자동으로 판정하지 않습니다.', '인코딩은 데이터를 다른 표현으로 바꾸는 방식이고, Base64는 바이트를 제한된 문자 집합으로 표현합니다. 암호화는 키를 사용해 기밀성을 제공하려는 방식이며, 해시는 입력을 고정 길이 요약으로 바꿔 무결성 확인 등에 사용합니다. 압축과 아카이브도 각각 크기 감소와 여러 파일 묶기라는 다른 목적을 가집니다.'],
    terminal: { title: '표현 형식부터 관찰하기', command: "$ file upload.dat\nupload.dat: ASCII text\n$ head -c 32 upload.dat\nU2VjdXJlIHRyYWluaW5nIGRhdGE=\n$ printf '%s' U2VjdXJlIHRyYWluaW5nIGRhdGE= | base64 --decode", output: 'Secure training data', annotations: ['문자열이 Base64처럼 보인다는 관찰은 암호화 여부의 증명이 아닙니다.', '디코딩은 표현을 되돌리는 것이며 비밀 키를 요구하지 않습니다.', '실제 의심 파일은 허가된 분석 환경에서만 다루고 실행하지 않습니다.'] },
    comparison: { title: '표현과 보안 기능 구분', columns: ['구분', '목적', '키·복원 관계'], rows: [['인코딩(Base64)', '전송·표현 호환', '정해진 규칙으로 누구나 되돌릴 수 있다.'], ['암호화', '기밀성', '적절한 키 없이는 평문 복원이 어려워야 한다.'], ['해시', '무결성 확인·식별 보조', '원래 입력을 복원하는 기능이 아니다.'], ['압축(gzip)', '크기 감소', '압축 해제해도 기밀성이 생기지 않는다.'], ['아카이브(tar)', '여러 항목 묶기', '압축·암호화와 별도 기능이다.']] },
    caseBody: 'CodeCureLAB 업로드 검증은 파일 확장자만 보고 처리하지 않습니다. 허용 형식, 크기, 저장 위치, 검사 결과를 서버에서 확인하고 원본 이름을 신뢰 경계로 사용하지 않습니다. 이 모듈은 안전한 관찰 도구의 목적을 이해하는 단계입니다.', facts: ['파일명과 확장자는 사람이 만든 이름일 뿐이다.', '문자열·hex 출력은 단서이지 악성 여부의 결론이 아니다.', '실행 파일·의심 샘플은 격리된 허가 환경과 절차가 필요하다.'],
    misconception: ['Base64면 암호화된 비밀이다 → Base64는 인코딩이며 키 없이도 디코딩할 수 있다.', '`strings`에 비밀이 안 보이면 안전하다 → 문자열 관찰은 제한된 단서이며 압축·인코딩·바이너리 구조를 모두 판정하지 못한다.'],
    checks: [{ title: '구분하기', prompt: '원래 입력을 되돌리는 기능을 전제로 하지 않는 것은?', options: ['해시', 'Base64 디코딩', '압축 해제'], answer: 0, explanation: '해시는 일반적으로 입력 복원을 목적으로 하지 않는 고정 길이 요약입니다.' }, { title: '파일 관찰 계획', prompt: '처음 보는 `report.pdf`를 받았을 때 확장자 외에 형식·크기·출처·처리 경로 관점에서 무엇을 확인할지 적어 보세요.' }],
    warning: { title: '분석 범위', body: '실제 악성코드나 출처 불명 파일을 개인 PC에서 열거나 실행하지 마세요. 이 과정에서는 고정된 교육용 출력만 다루며, 악성코드 분석은 Week 11~12의 격리된 교육 범위에서 다룹니다.' },
    work: '포렌식, 악성코드 분석, 업로드 보안, 데이터 보호 업무는 파일의 이름과 실제 바이트·처리 경로를 구분합니다. 관찰 도구의 한계를 기록해야 다른 사람이 결과를 과장하지 않습니다.', labs: ['w2-bandit'], sourceItems: [sources.coreutils], summary: ['인코딩·암호화·해시·압축·아카이브는 목적이 다르다.', '파일 확장자와 문자열 출력은 단서이지 완전한 판정이 아니다.', '의심 파일은 격리된 허가 환경에서만 다룬다.'],
  }),
  'w2-curl': blockSet({
    id: 'w2-curl', question: '웹 요청을 바꾸기 전에 왜 먼저 정상 요청의 URL·Method·Headers·Body·Status를 기준선으로 남겨야 할까?',
    explanation: ['`curl`은 URL을 대상으로 HTTP 요청을 보내고 응답을 관찰할 수 있는 명령줄 도구입니다. Week 2의 목적은 공격이 아니라 정상 요청 기준선을 만드는 것입니다. `curl -i`는 상태선·응답 헤더·본문을 함께 보여 주고, `-v`는 연결과 요청·응답 방향을 더 자세히 보지만 기록 전 민감한 헤더를 마스킹해야 합니다.', '관찰을 비교할 때 한 번에 한 요소만 바꿉니다. URL, method, request header, body, status code 중 무엇이 달라졌는지 명확해야 서버가 어떤 값을 검증하는지 설명할 수 있습니다. 실제 외부 서비스에는 요청하지 않고 로컬 또는 명시적으로 허가된 교육 대상만 사용합니다.'],
    terminal: { title: '정상 요청 기준선 저장', command: '$ curl -i https://training.local/api/catalog\nHTTP/1.1 200 OK\nContent-Type: application/json\nCache-Control: no-store\n\n{"items":[{"id":"SEC-BOOK","available":true}]}', output: '$ curl -i -H "Accept: application/json" https://training.local/api/catalog\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{"items":[{"id":"SEC-BOOK","available":true}]}', annotations: ['예시는 로컬 training 대상의 고정 응답 형식입니다.', '두 요청의 차이는 Accept 헤더 하나이므로 응답이 같아도 비교 근거를 기록할 수 있습니다.', 'Cookie·Authorization·실제 URL의 민감한 부분은 항상 `[REDACTED]` 처리합니다.'] },
    comparison: { title: 'curl 관찰 옵션', columns: ['옵션', '보는 것', '기록 주의점'], rows: [['`-i`', '응답 상태선·헤더·본문', 'Set-Cookie 등 민감 값 마스킹'], ['`-I`', '응답 헤더만(HEAD 요청)', 'GET과 의미가 같은지 서버마다 다를 수 있음'], ['`-v`', '연결과 요청·응답 방향의 상세 로그', '인증 헤더·프록시 정보 노출 여부 확인'], ['`-X METHOD`', '요청 method 명시', '서버가 허용한 정상 method만 교육 범위에서 비교'], ['`-H "Name: value"`', '요청 헤더 하나 추가·변경', '한 번에 하나만 바꾸고 원본도 남긴다.']] },
    caseBody: '교육용 카탈로그 API의 정상 GET 응답을 먼저 기록하면, 다음 웹 기초에서 브라우저 DevTools와 Burp가 같은 요청을 어떻게 보이는지 비교할 수 있습니다. 기준선은 “정상 동작” 관찰이지 서버 검증이 불필요하다는 뜻이 아닙니다.', facts: ['기준선에는 URL·method·헤더·본문·status·관찰 시각을 남긴다.', '변경은 한 요소만 하고 원본·변경 요청과 응답을 나란히 비교한다.', '클라이언트 값은 서버가 인증·인가·입력 규칙으로 다시 검증해야 한다.'],
    misconception: ['`curl -v`가 보안 진단을 자동으로 해 준다 → 상세 전송 로그는 관찰 재료일 뿐 영향·원인 판단을 대신하지 않는다.', 'HTTP 상태가 200이면 보안적으로 안전하다 → 정상 상태 코드는 인증·인가·데이터 노출·입력 검증의 증명이 아니다.'],
    checks: [{ title: '기준선 구성', prompt: '정상 HTTP 기준선에 꼭 포함할 조합은?', options: ['URL·method·headers·body·status', '브라우저 테마·글꼴', 'CPU 온도만'], answer: 0, explanation: '요청과 응답의 의미를 비교하려면 핵심 메시지 구성 요소와 관찰 시각을 남겨야 합니다.' }, { title: '한 요소 비교', prompt: '정상 요청 뒤 header 하나만 바꿔 관찰할 때 원본·변경 기록에 각각 무엇을 남길지 적어 보세요.' }],
    warning: { title: '요청 범위', body: 'curl은 실제 네트워크 요청을 만들 수 있습니다. 이 과정에서는 내장 시뮬레이터와 명시적으로 허가된 교육 대상만 사용하며, 실제 기관·서비스에 옵션을 시험하지 않습니다.' },
    work: 'AppSec, API 개발, SRE, 취약점 진단은 모두 기준선과 diff를 사용합니다. 좋은 기록은 요청을 재현할 수 있게 하되 인증정보·개인정보·실제 비밀을 포함하지 않습니다.', labs: [], sourceItems: [sources.curl], summary: ['curl은 정상 HTTP 기준선을 만드는 도구다.', 'URL·method·headers·body·status를 원본과 변경본에 함께 남긴다.', '변경은 한 번에 한 요소만 하고 서버 검증 여부를 분리해 본다.'],
  }),
  'w2-process': blockSet({
    id: 'w2-process', question: '같은 `codecurelab-app` 이름이 보여도 실제로 어떤 계정·PID·소켓으로 실행되는지 왜 따로 확인해야 할까?',
    explanation: ['프로세스는 실행 중인 프로그램의 자원 단위이며 PID로 구분합니다. `ps`는 실행 중인 프로세스, `jobs`·`bg`·`fg`는 현재 셸의 작업, `PATH`는 셸이 명령을 찾는 디렉터리 순서와 관련됩니다. 운영 중인 프로세스를 종료하거나 신호를 보내는 행동은 영향이 크므로 이 과정에서는 개념과 읽기 전용 관찰에 한정합니다.', '`ip addr`는 인터페이스 주소, `ss`는 소켓 상태, `dig`는 DNS 질의 결과를 관찰하는 데 사용됩니다. 주소·포트·프로토콜 정보는 서비스 노출과 연결 관계의 단서이지만 허가 없는 연결 시도나 스캔의 근거가 되지 않습니다.'],
    terminal: { title: '프로세스와 소켓을 읽기 전용으로 보기', command: '$ ps -o pid,user,comm -C codecurelab-app\n  PID USER     COMMAND\n 4242 app      codecurelab-app\n$ ss -ltnp | grep 4242', output: 'LISTEN 0 128 127.0.0.1:8080 0.0.0.0:* users:(("codecurelab-app",pid=4242,fd=7))', annotations: ['PID와 실행 계정을 함께 확인합니다.', '127.0.0.1 바인딩은 로컬 인터페이스라는 관찰이며 프록시·방화벽 등 전체 노출 판단에는 추가 정보가 필요합니다.', '운영 프로세스 종료·신호 전송은 허가와 절차가 필요한 변경입니다.'] },
    comparison: { title: '프로세스·네트워크 CLI의 관찰 대상', columns: ['도구', '주요 관찰', '범위 주의'], rows: [['`ps`', 'PID·사용자·명령', '스냅샷이며 전체 실행 맥락을 자동으로 설명하지 않는다.'], ['`ss`', '소켓 상태·주소·포트', '수신 주소와 실제 외부 노출은 다를 수 있다.'], ['`ip addr`', '인터페이스·주소', '주소만으로 역할과 접근 권한을 단정하지 않는다.'], ['`dig`', 'DNS 질의 응답', '교육·승인된 도메인만 질의한다.']] },
    caseBody: '교육용 앱이 `app` 계정으로 127.0.0.1:8080에 대기하고 Reverse Proxy가 외부 요청을 전달하는 구조라면, 앱 프로세스의 실행 계정과 프록시의 공개 경계를 따로 기록해야 합니다.', facts: ['프로세스·소켓·DNS는 서로 다른 층의 관찰이다.', '관찰 명령과 프로세스 변경 명령의 영향은 다르다.', '주소·포트 정보는 지정된 교육 범위 밖에서 탐색하지 않는다.'],
    misconception: ['포트가 보이면 인터넷에서 누구나 접속할 수 있다 → 바인딩 주소, 프록시, 방화벽, 네트워크 경계를 함께 확인해야 한다.', '`kill`은 멈춘 프로그램을 고치는 기본 명령이다 → 서비스 영향과 승인 절차를 확인하지 않으면 장애를 만들 수 있다.'],
    checks: [{ title: '관찰 대상', prompt: 'PID와 실행 계정을 확인하는 도구는?', options: ['`ps`', '`grep`만', '`base64`'], answer: 0, explanation: '`ps`는 실행 중인 프로세스의 PID·사용자·명령을 보여 줍니다.' }, { title: '노출 판단', prompt: '소켓이 `127.0.0.1:8080`에 LISTEN인 관찰 뒤, 외부 노출 여부를 판단하기 위해 추가로 확인할 층을 적어 보세요.' }],
    warning: { title: '확장 경로 범위', body: '프로세스 종료, 포트 스캔, 임의 호스트 연결은 이 과정의 실습이 아닙니다. 읽기 전용 관찰도 지정된 로컬·허가 대상에서만 수행합니다.' }, work: '시스템 보안, SOC, SRE, 포렌식은 프로세스·계정·소켓·로그를 함께 비교해 이상 행동과 서비스 구조를 이해합니다.', labs: [], sourceItems: [sources.coreutils], summary: ['프로세스, 소켓, 인터페이스, DNS는 다른 관찰 대상이다.', 'PID·실행 계정·바인딩 주소를 함께 기록한다.', '변경·연결·스캔은 허가와 영향 검토가 필요한 행동이다.'],
  }),
  'w2-git': blockSet({
    id: 'w2-git', question: '파일을 지웠는데 왜 이미 커밋된 API key가 저장소 이력에서 자동으로 사라지지 않을까?',
    explanation: ['Git은 작업 트리, staging area, commit이라는 다른 상태를 관리합니다. `git status`로 현재 상태를 보고, `git diff`로 변경 내용을 검토한 뒤, 필요한 파일만 `git add`하고 의미 있는 단위로 `git commit`을 만듭니다. 보안 수정도 무엇을 왜 바꿨는지와 검증 결과가 남아야 재시험할 수 있습니다.', '비밀번호·API key·세션 토큰은 처음부터 저장소에 넣지 않는 것이 원칙입니다. `.gitignore`는 아직 추적하지 않는 파일을 제외하는 도구일 뿐 이미 commit한 비밀을 이력에서 지우지 않습니다. 노출이 확인되면 파일 삭제만 하지 말고 해당 비밀을 폐기·교체하고 영향 범위를 검토합니다.'],
    terminal: { title: '커밋 전 변경 검토', command: '$ git status --short\n M config/example.env\n M src/uploadPolicy.js\n$ git diff -- src/uploadPolicy.js\n$ git add src/uploadPolicy.js\n$ git commit -m "Validate upload media type on server"', output: '[main 1a2b3c4] Validate upload media type on server\n 1 file changed, 8 insertions(+), 2 deletions(-)', annotations: ['`status`는 상태, `diff`는 내용, `add`는 staging, `commit`은 이력 기록이라는 역할을 가집니다.', 'example 파일과 실제 비밀 파일을 구분하고 commit 전 diff를 확인합니다.', 'commit 메시지는 변경 이유와 검증 가능한 단위를 드러내야 합니다.'] },
    comparison: { title: 'Git 상태와 비밀정보 대응', columns: ['상황', 'Git에서 보는 위치', '보안 행동'], rows: [['아직 저장하지 않은 변경', 'working tree', '`status`·`diff`로 범위 확인'], ['다음 commit 후보', 'staging area', '필요한 파일만 `add`'], ['이미 기록한 변경', 'commit history', '리뷰·재시험 근거로 사용'], ['비밀이 이미 commit됨', '현재 파일과 history', '파일 삭제만 하지 말고 키 폐기·교체·영향 검토']] },
    caseBody: '업로드 정책 수정은 서버 검증 코드, 테스트 결과, 문서화된 예외를 함께 review해야 합니다. 실제 환경 파일과 `example.env`를 혼동해 비밀을 commit하지 않도록 명확한 파일명·검토 절차를 둡니다.', facts: ['commit은 기능 단위와 근거를 남기는 기록이다.', '비밀은 `.gitignore` 이전에 저장소 밖에 두는 것이 기본이다.', '이미 노출된 비밀은 이력 삭제보다 폐기·교체와 영향 조사부터 한다.'],
    misconception: ['`.gitignore`에 넣으면 과거 commit에서도 사라진다 → 이미 추적된 파일과 이력에는 적용되지 않는다.', '비밀 파일을 삭제해 commit하면 해결된다 → 외부 복제·캐시·이력 노출 가능성을 고려해 key rotation이 필요하다.'],
    checks: [{ title: '상태 구분', prompt: 'commit 전에 변경 내용을 검토하는 데 가장 직접적인 명령은?', options: ['`git diff`', '`git push --force`', '`git clone`'], answer: 0, explanation: '`git diff`는 아직 commit되지 않은 변경 내용을 비교해 보여 줍니다.' }, { title: '비밀 대응', prompt: 'API key가 이미 공유 저장소 commit에 포함된 사실을 알았을 때 즉시 할 행동과 이후 기록할 내용을 적어 보세요.' }],
    warning: { title: '비밀정보 처리', body: '실제 API key, 토큰, 비밀번호를 샘플 commit이나 화면 캡처에 넣지 마세요. 교육용 문자열도 실제 형식처럼 보이지 않게 `[REDACTED]`로 표시합니다.' }, work: 'DevSecOps, AppSec, 개발팀은 commit·리뷰·CI 결과를 변경 통제와 재시험 증적으로 사용합니다. 비밀 관리와 코드 검토는 보안 도구보다 먼저 지켜야 할 개발 운영 원칙입니다.', labs: [], sourceItems: [sources.git], summary: ['작업 트리·staging·commit은 다른 상태다.', 'commit 전에는 `status`와 `diff`로 범위를 검토한다.', '이미 노출된 비밀은 파일 삭제가 아니라 폐기·교체·영향 검토가 우선이다.'],
  }),
  'w2-http-tools': blockSet({
    id: 'w2-http-tools', question: 'DevTools, curl, Burp가 같은 HTTP 요청을 서로 다르게 보여 줄 때 각 도구는 어떤 질문에 가장 잘 답할까?',
    explanation: ['DevTools Network는 브라우저가 실제로 만든 요청·응답, timing, initiator를 관찰합니다. Application·Storage는 Cookie와 브라우저 저장소를, Elements는 실행 후 DOM을 보여 줍니다. curl은 재현 가능한 명령줄 기준선을 남기고, Burp Proxy는 허가된 대상의 HTTP 흐름을 기록하며 Repeater는 선택한 요청을 제한된 범위에서 반복 비교하는 데 사용합니다.', '도구는 서버 신뢰 경계를 바꾸지 않습니다. 브라우저에서 값을 숨기거나 제한해도 서버는 인증, 객체 인가, 입력 검증을 다시 수행해야 합니다. Burp Intercept를 켠 채 방치하면 요청이 멈춘 것처럼 보일 수 있으므로 proxy 상태와 대상 범위를 항상 확인합니다.'],
    terminal: { title: '정상 요청을 세 도구에서 비교할 때의 기준', command: 'curl:     GET /api/profile → HTTP 200\nDevTools: Request URL, Request Headers, Response, Initiator\nBurp:     Proxy history의 같은 요청을 선택 → Repeater에서 한 요소만 비교', output: '공통 기록: URL · method · request headers · request body · status · response body · 관찰 시각 · 마스킹 여부', annotations: ['도구마다 화면과 기능은 달라도 비교의 기준은 같은 HTTP 메시지입니다.', 'Burp는 외부 서비스가 아닌 명시적으로 허가된 교육 대상에서만 사용합니다.', 'Cookie·Authorization·개인정보는 모든 도구의 export·screenshot에서 마스킹합니다.'] },
    comparison: { title: '도구별 질문', columns: ['도구', '가장 잘 보는 것', '한계·주의'], rows: [['DevTools Network', '브라우저가 실제로 만든 요청·응답·timing', '브라우저 밖의 기준선·반복 비교는 제한적일 수 있음'], ['curl', '명령으로 남긴 정상 요청 기준선', '브라우저의 렌더링·DOM·자동 상태 처리를 그대로 재현하지 않음'], ['Burp Proxy·Repeater', '허가 범위의 HTTP 기록과 선택 요청 비교', 'scope와 intercept 상태를 잘못 설정하면 영향·혼선을 만들 수 있음']] },
    caseBody: 'CodeCureLAB 프로필 요청을 DevTools에서 보면 브라우저 initiator와 Cookie 속성을, curl에서는 최소한의 기준선을, Burp에서는 허가된 training 요청의 원본·변경 비교를 볼 수 있습니다. 세 도구의 화면을 더 많이 캡처하는 것보다 같은 필드가 서로 일치하는지 확인하는 것이 중요합니다.', facts: ['도구의 역할은 중복이 아니라 관찰 지점의 차이다.', '정상 요청을 먼저 남기고 한 요소만 바꾼다.', '클라이언트 관찰 결과는 서버 검증의 필요성을 없애지 않는다.'],
    misconception: ['Burp를 쓰면 모든 사이트를 검사해도 된다 → 프록시도 명시적 허가·scope·최소 영향 원칙 안에서만 사용한다.', 'DevTools에 값이 안 보이면 서버도 받지 않았다 → 요청 원문, 서버 로그, DOM은 서로 다른 관찰 지점이다.'],
    checks: [{ title: '도구 선택', prompt: '브라우저가 어떤 JavaScript initiator로 요청을 만들었는지 확인할 때 가장 직접적인 도구는?', options: ['DevTools Network', '파일 권한 문자열', 'Git commit message'], answer: 0, explanation: 'DevTools Network는 브라우저가 생성한 요청과 initiator 정보를 관찰하는 데 적합합니다.' }, { title: '안전한 비교', prompt: '같은 training HTTP 요청을 curl·DevTools·Burp로 비교할 때 공통으로 기록할 필드와 마스킹할 값을 적어 보세요.' }],
    warning: { title: 'Burp 사용 범위', body: 'Proxy와 Repeater는 로컬 또는 명시적으로 허가된 교육 대상만 다룹니다. 실제 서비스, 타인 계정, 범위 밖 URL을 proxy history에서 반복 요청하지 마세요.' }, work: '웹 보안 진단, API 개발, QA, AppSec은 브라우저·명령줄·프록시 도구를 함께 사용합니다. 도구 이름보다 대상 범위, 기준선, diff, 서버 재검증, 기록 마스킹이 업무 품질을 결정합니다.', labs: ['w2-http-lab'], sourceItems: [sources.chrome, sources.curl, sources.burp], summary: ['DevTools는 브라우저 요청, curl은 기준선, Burp는 허가된 비교에 강점이 있다.', '세 도구는 같은 HTTP 필드를 기준으로 교차 확인한다.', '프록시 도구도 ROE·scope·마스킹·최소 영향 원칙을 따른다.'],
  }),
})
