const sources = {
  xss: { label: 'OWASP · Cross Site Scripting Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html', note: '출력 컨텍스트, safe sink, sanitization, CSP의 역할과 한계를 확인합니다.' },
  dom: { label: 'OWASP · DOM-based XSS Prevention Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html', note: '브라우저 안의 source와 sink를 추적하는 방식을 확인합니다.' },
  wstg: { label: 'OWASP · Web Security Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/', note: '관찰 근거와 재시험을 남기는 테스트·보고서 기준으로 사용합니다.' },
  resteasyCve: { label: 'NVD · CVE-2020-10688', url: 'https://nvd.nist.gov/vuln/detail/CVE-2020-10688', note: '영향 버전, URL encoding 원인, reflected XSS 분류와 Red Hat 패치 참조를 확인합니다.' },
  resteasyPatch: { label: 'Red Hat · RESTEasy CVE-2020-10688 추적', url: 'https://bugzilla.redhat.com/show_bug.cgi?id=1814974', note: 'NVD가 Patch·Vendor Advisory로 분류한 Red Hat 추적 항목입니다.' },
  gitlabCve: { label: 'NVD · CVE-2022-1948', url: 'https://nvd.nist.gov/vuln/detail/CVE-2022-1948', note: 'GitLab이 보고한 영향 버전과 quick action 입력 검증 누락을 확인합니다.' },
  gitlabPatch: { label: 'GitLab · CVE-2022-1948 공식 패치', url: 'https://gitlab.com/gitlab-org/gitlab/-/commit/e61e9b9434e2198c4c1d5cf6b4531eb4323c3575', note: 'GitLab 보안 핸드북이 first/last name escaping 패치로 연결한 공식 커밋입니다.' },
  jqueryCve: { label: 'NVD · CVE-2020-11022', url: 'https://nvd.nist.gov/vuln/detail/CVE-2020-11022', note: '신뢰할 수 없는 HTML을 DOM 조작 메서드에 전달한 조건과 jQuery 3.5.0 패치를 확인합니다.' },
  jqueryPatch: { label: 'jQuery · 3.5.0 보안 릴리스', url: 'https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/', note: 'jQuery의 공식 3.5.0 릴리스 및 보안 수정 설명입니다.' },
}

const reportEvidenceScenario = {
  statements: [
    { id: 'fact', label: '합성 게시글 미리보기에서 고정 마커가 HTML 구조로 해석되는 DOM 변화를 확인했다.' },
    { id: 'impact', label: '권한 있는 사용자가 이 화면을 볼 때 페이지 기능과 DOM 데이터에 영향을 줄 가능성이 있어 추가 확인이 필요하다.' },
    { id: 'condition', label: '영향 판단에는 피해자 역할, 노출된 기능, HttpOnly와 CSP 설정을 별도로 확인해야 한다.' },
    { id: 'root-cause', label: '저장된 제목을 텍스트 노드가 아닌 `innerHTML` 경로로 렌더링한다.' },
    { id: 'control', label: '일반 텍스트 제목은 `textContent`로 출력하고, 제한된 HTML이 필요한 기능은 별도 정화 정책을 적용한다.' },
    { id: 'retest', label: '일반 제목, 문법 문자가 포함된 텍스트, 빈 값, 저장 후 재조회 경로를 수정 전과 같은 기준으로 비교한다.' },
  ],
  categories: [
    { id: 'fact', label: '관찰 사실' },
    { id: 'impact', label: '영향 판단' },
    { id: 'condition', label: '전제 조건' },
    { id: 'root-cause', label: '근본 원인' },
    { id: 'control', label: '수정 방향' },
    { id: 'retest', label: '재시험 계획' },
  ],
  reflection: {
    prompt: '위 문장 중 하나를 골라, 왜 그것이 관찰 사실 또는 영향 판단인지 근거를 60자 이상으로 설명하세요.',
    minimumLength: 60,
  },
}

export const week4LessonMeta = Object.freeze({
  'w4-nature': {
    title: '검색어는 언제 HTML이 되는가',
    summary: 'HTML, DOM, origin을 짧게 복습한 뒤 일반 텍스트가 해석형 출력 지점에서 구조가 되는 순간을 봅니다.',
    duration: 55,
    archetype: '원리 해설형',
    learningQuestion: '일반 텍스트를 보여 주는 검색 결과에서 브라우저가 값을 HTML로 읽게 되는 순간은 언제인가?',
    observableOutcome: '태그·속성·텍스트 노드·DOM을 구분하고 textContent와 innerHTML이 만드는 결과 차이를 설명한다.',
    prerequisiteConceptIds: [],
    newConceptIds: ['html-tag', 'html-attribute', 'text-node', 'html-parser', 'dom-node', 'origin'],
    evidenceObjects: ['합성 검색 코드', '요청·응답·DOM 흐름도'],
    failurePoint: '일반 텍스트를 해석형 HTML API에 전달하는 출력 단계',
    impactConditions: ['같은 출처 문맥', '사용자가 해당 페이지를 보는 상황'],
    controls: ['textContent', '프레임워크 기본 escaping'],
    retestMatrix: ['일반 텍스트', '문법 문자', '빈 값'],
    transferGate: ['태그·속성·텍스트 노드를 구분한다.', '해석형 출력 지점을 한 곳 표시한다.'],
  },
  'w4-types': {
    title: '세 경로는 어디서 갈라지는가',
    summary: '반사형·저장형·DOM 기반 XSS를 이름이 아니라 데이터가 이동하는 시간과 위치로 비교합니다.',
    duration: 55,
    archetype: '사례 판정형',
    learningQuestion: '서버 응답과 실행 후 DOM을 함께 볼 때 세 XSS 경로는 어디에서 달라지는가?',
    observableOutcome: '세 흐름에서 source, 저장 여부, browser interpretation 위치를 표와 증거로 구분한다.',
    prerequisiteConceptIds: ['dom-node', 'server-response'],
    newConceptIds: ['server-response', 'live-dom'],
    evidenceObjects: ['합성 요청', '저장 기록', '응답 원문', '실행 후 DOM'],
    failurePoint: '각 경로의 해석형 출력 단계',
    impactConditions: ['입력 전달 또는 저장', '피해자의 렌더링'],
    controls: ['출력 경로의 데이터/코드 분리'],
    retestMatrix: ['현재 요청', '저장 후 재조회', 'fragment 기반 경로'],
    transferGate: ['응답 원문과 live DOM을 구분한다.'],
  },
  'w4-taint': {
    title: '반사형 사례: CVE-2020-10688의 오류 경로',
    summary: 'RESTEasy의 반사형 XSS CVE를 사실·조건·패치와 함께 읽고, 일반적인 source-to-sink 검토로 연결합니다.',
    duration: 65,
    archetype: '흐름 추적형',
    learningQuestion: '공식 CVE에서 URL encoding 오류가 반사형 XSS가 되려면 어떤 오류 경로와 출력 조건이 함께 필요한가?',
    observableOutcome: '공식 CVE의 원인·영향 버전·패치를 인용하고, 일반 코드에서 source·transform·sink·context를 각각 표시한다.',
    prerequisiteConceptIds: ['html-parser', 'text-node'],
    newConceptIds: ['xss-source', 'data-transform', 'interpreting-sink', 'safe-sink'],
    evidenceObjects: ['NVD CVE 기록', 'Red Hat 패치 추적', '합성 JavaScript 코드', 'source-to-sink 흐름도'],
    failurePoint: 'interpreting sink에 신뢰 수준이 불명확한 값을 전달하는 단계',
    impactConditions: ['해석형 sink', '출력 컨텍스트'],
    controls: ['safe sink', '컨텍스트별 출력 처리'],
    retestMatrix: ['마커', '일반 문법 문자', '수정 뒤 DOM'],
    transferGate: ['source와 sink를 코드에서 각각 찾는다.'],
  },
  'w4-context': {
    title: '저장형 사례: CVE-2022-1948의 입력·재출력 경계',
    summary: 'GitLab의 저장형 XSS CVE와 공식 escaping 패치를 읽고, 출력 컨텍스트가 방어 선택을 바꾸는 이유를 봅니다.',
    duration: 70,
    archetype: '원리 해설형',
    learningQuestion: '저장된 입력이 나중에 다시 렌더링될 때, 왜 입력 검증과 출력 컨텍스트를 함께 확인해야 하는가?',
    observableOutcome: '공식 CVE의 입력 검증 누락과 escaping 패치를 연결하고, 출력 컨텍스트 네 가지의 첫 방어를 설명한다.',
    prerequisiteConceptIds: ['html-attribute', 'interpreting-sink'],
    newConceptIds: ['output-context', 'contextual-output-encoding'],
    evidenceObjects: ['NVD CVE 기록', 'GitLab 공식 패치', '네 가지 출력 위치', '수정 전·후 코드'],
    failurePoint: '문맥을 구분하지 않고 공통 문자열 처리만 적용하는 설계',
    impactConditions: ['브라우저 파서 규칙', '속성 또는 URL의 허용 범위'],
    controls: ['컨텍스트별 encoding', 'URL allowlist', '위험한 위치 회피'],
    retestMatrix: ['본문', '속성', 'URL', 'JS data'],
    transferGate: ['출력 컨텍스트 네 가지를 구분한다.'],
  },
  'w4-impact': {
    title: 'DOM 기반 사례: CVE-2020-11022의 DOM 조작 API',
    summary: 'jQuery DOM 조작 API의 실제 CVE를 통해 client-side source·sink와 라이브 DOM을 구분합니다.',
    duration: 50,
    archetype: '사례 판정형',
    learningQuestion: '신뢰할 수 없는 HTML이 브라우저 DOM 조작 API에 전달될 때, 왜 서버 응답만으로는 충분히 판단할 수 없는가?',
    observableOutcome: '공식 CVE의 DOM API 조건과 3.5.0 패치를 인용하고, server response와 live DOM의 증거를 분리한다.',
    prerequisiteConceptIds: ['origin', 'same-origin-policy'],
    newConceptIds: ['observation-inference', 'impact-conditions'],
    evidenceObjects: ['NVD CVE 기록', 'jQuery 3.5.0 보안 릴리스', '합성 DOM 관찰 결과'],
    failurePoint: '해석형 sink가 남은 렌더링 경로',
    impactConditions: ['신뢰할 수 없는 HTML 입력', 'DOM 조작 API', '사용자가 해당 페이지를 보는 상황'],
    controls: ['근본 수정', '보완 통제 검토'],
    retestMatrix: ['권한별 화면', '보호 속성', '수정 후 관찰'],
    transferGate: ['server response와 live DOM을 구분한다.', 'DOM 조작 API가 받는 값의 신뢰 경계를 표시한다.'],
  },
  'w4-defense': {
    title: '패치에서 근본 방어까지: 해석 경로를 없애기',
    summary: '세 CVE의 공식 패치와 text encoding·safe DOM API·CSP의 한계를 분리해 비교합니다.',
    duration: 70,
    archetype: '방어·재시험형',
    learningQuestion: 'HTML이 필요 없는 화면과 제한된 서식이 필요한 화면은 왜 다른 방어를 선택해야 하는가?',
    observableOutcome: '근본 수정과 보완 통제를 구분하고, 수정 후 재시험 매트릭스를 작성한다.',
    prerequisiteConceptIds: ['output-context', 'safe-sink'],
    newConceptIds: ['html-sanitization-policy', 'csp'],
    evidenceObjects: ['수정 전·후 코드', '방어 계층 지도', '재시험 행렬'],
    failurePoint: '문자열 블랙리스트나 CSP만으로 해석형 sink를 남기는 설계',
    impactConditions: ['허용 HTML 요구', '정책 구성', '브라우저 지원'],
    controls: ['safe sink', 'sanitization policy', 'URL allowlist', 'CSP'],
    retestMatrix: ['정상 텍스트', '문법 문자', '다른 렌더링 경로', '정책 적용'],
    transferGate: ['CSP가 원인 수정이 아니라는 이유를 설명한다.'],
  },
  'w4-validation': {
    title: '2차 확인: 수정 뒤에도 남는 경로 찾기',
    summary: '수정 전후를 비교해 정상 기능과 인접 렌더링 경로를 다시 확인하고, 검증되지 않은 우회 연결은 채택하지 않습니다.',
    duration: 60,
    archetype: '도구 관찰형',
    learningQuestion: '패치가 적용된 뒤, 같은 입력·정상 기능·인접 렌더링 경로를 어떻게 다시 비교해야 하는가?',
    observableOutcome: '정상·문법 문자·저장 후 재조회·client-side 경로를 재시험 표로 구분하고, 검증되지 않은 우회 주장을 배제한다.',
    prerequisiteConceptIds: ['observation-inference', 'impact-conditions', 'csp'],
    newConceptIds: ['retest-and-regression'],
    evidenceObjects: ['수정 전·후 DOM', '재시험 행렬', 'CVE 공식 근거 링크'],
    failurePoint: '근거 없이 영향을 단정하거나 수정 뒤 정상 기능을 확인하지 않는 기록',
    impactConditions: ['관찰 범위', '사용자 역할', '보호 장치'],
    controls: ['근본 수정 기록', '회귀 시험', '마스킹'],
    retestMatrix: ['정상', '문법 문자', '경계값', '다른 경로'],
    transferGate: ['네 가지 안전 활동의 결과를 source·sink·context와 함께 기록한다.'],
  },
})

const baseWeek4LessonBlocks = {
  'w4-nature': [
    { type: 'question', variant: 'lead', title: '검색어는 글자인데, 왜 페이지 구조가 될 수 있을까?', body: '검색 화면에 일반 문장을 넣었을 때 글자가 그대로 보이지 않고 일부가 사라진다면, 입력값이 이상한지부터 단정하지 마세요. 먼저 브라우저가 그 값을 글자로 보았는지, HTML 구조로 읽었는지를 구분해야 합니다.' },
    { type: 'concept-ref', variant: 'prerequisite', title: '시작 전 5분 복습', intro: '아래 다섯 개는 외부 문서를 열지 않고 이 페이지에서 바로 확인할 수 있는 선수 개념입니다.', conceptIds: ['html-tag', 'html-attribute', 'text-node', 'dom-node', 'origin'] },
    { type: 'explanation', variant: 'narrative', title: '문서 구조와 일반 글자는 다른 역할을 한다', paragraphs: [
      'HTML은 브라우저에게 문서의 구조를 알려 주는 언어입니다. 제목, 문단, 링크처럼 화면을 구성하는 표식이 있고, 그 표식 사이에는 사람이 읽을 문장이 들어갑니다. 검색어, 댓글, 프로필 이름처럼 사용자가 입력한 값은 대개 후자입니다. 서비스가 원하는 결과는 그 값을 화면에 보여 주는 일이지, 그 값이 새 태그나 속성을 만들게 하는 일이 아닙니다.',
      '브라우저는 받은 HTML을 읽어 DOM(Document Object Model)이라는 트리로 만듭니다. 태그, 속성, 텍스트는 DOM에서 서로 다른 노드와 값으로 남습니다. 페이지가 처음 로드된 뒤 JavaScript가 DOM을 바꿀 수도 있으므로, 서버가 보낸 원문과 현재 화면의 DOM은 항상 같은 것은 아닙니다.',
      'XSS는 "특수문자를 썼다"는 사건이 아닙니다. 일반 데이터가 어떤 경로를 거쳐 브라우저의 HTML 또는 코드 해석기에 전달되는 구조적 문제입니다. 따라서 먼저 정상 모델을 세웁니다. 일반 텍스트를 출력하는 기능이라면 입력은 시작부터 끝까지 텍스트 노드로 남아야 합니다.',
      '출처(origin)는 브라우저가 문서를 나누는 기본 경계입니다. 취약한 페이지 안에서 코드가 해석되면, 그 코드는 그 페이지의 DOM과 사용자가 가진 기능 문맥에서 동작할 수 있습니다. 이는 동일 출처 정책이 사라졌다는 뜻이 아니라, 취약한 페이지의 문맥 안에서 문제가 생긴다는 뜻입니다.',
    ] },
    { type: 'diagram', variant: 'boundary', title: '요청에서 화면까지, 어느 단계가 문법을 읽는가', body: '이 그림은 입력이 텍스트로 남는 정상 경로와 HTML 파서로 넘어가는 경로를 비교합니다. 실패 지점은 입력칸이 아니라 해석형 출력으로 갈라지는 곳입니다.', nodes: ['URL query · 사용자 데이터', '애플리케이션 · 문장 구성', 'textContent 또는 innerHTML 선택', 'HTML parser를 거친 DOM 또는 텍스트 노드', '브라우저 화면'] },
    { type: 'code', variant: 'before-after', language: 'JavaScript', title: '마지막 한 줄이 바꾸는 결과', description: '두 예시는 같은 `query` 값을 사용합니다. 어느 줄이 값을 HTML로 다시 읽게 하는지 비교하세요.', code: 'const query = new URLSearchParams(location.search).get(\'q\') ?? \'\'\n\n// 일반 텍스트 출력: 값은 text node로 남는다.\nresults.textContent = `검색어: ${query}`\n\n// 해석형 출력: 값이 HTML fragment로 파싱될 수 있다.\nresults.innerHTML = `검색어: ${query}`', annotations: ['두 줄의 입력 source와 문자열 조합은 같다.', '`textContent`는 일반 텍스트를 표시하는 목적에 맞는 출력 지점이다.', '`innerHTML`을 선택하면 브라우저의 HTML parser가 값에 관여하므로, 출력 컨텍스트를 다시 검토해야 한다.'] },
    { type: 'checkpoint', variant: 'prediction', id: 'w4-nature-check-01', title: '다음 결과를 예측해 보세요', prompt: '일반 텍스트를 보여 주는 검색 결과에서, 사용자의 값을 HTML parser에 넘기지 않으려면 어떤 선택이 가장 먼저 적절한가?', options: ['문자열 블랙리스트를 계속 늘린다.', '텍스트 전용 출력 지점을 사용한다.', 'CSP만 설정한다.'], answer: 1, explanation: '텍스트 전용 출력은 값이 HTML 구조로 해석되는 경로를 없앱니다. 블랙리스트와 CSP는 해석형 출력 지점이 남는 문제를 근본적으로 바꾸지 못하거나 보완 통제에 머뭅니다.' },
    { type: 'misconception', variant: 'contrast', title: '여기서 자주 섞이는 두 가지', items: ['`HTML을 화면에 표시한다`와 `사용자 값을 HTML로 해석한다`는 같은 말이다 → 전자는 문서 구조를 렌더링하는 일이고, 후자는 외부 값을 새 구조로 만들 수 있는 별도 선택이다.', '`HttpOnly`가 있으면 XSS는 문제가 아니다 → HttpOnly는 일부 쿠키 읽기를 제한할 뿐, 취약한 페이지 안에서 값이 해석되는 원인을 바꾸지 않는다.'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.xss] },
    { type: 'summary', title: '이 모듈의 결론', bullets: ['일반 텍스트 기능의 기대 결과는 입력이 텍스트 노드로 남는 것이다.', 'XSS의 핵심 질문은 값이 어디에서 HTML 또는 코드로 해석되는가이다.', '다음 모듈에서는 같은 값을 반사·저장·DOM 경로로 나눠 증거와 함께 비교한다.'] },
  ],
  'w4-types': [
    { type: 'case', variant: 'worked-example', title: '같은 마커, 서로 다른 세 장면', body: '합성 서비스에는 검색어를 즉시 응답에 넣는 페이지, 제목을 저장했다가 목록에 다시 그리는 게시판, URL fragment를 JavaScript가 읽어 화면을 바꾸는 페이지가 있습니다. 세 페이지에 같은 고정 마커가 보였다고 해서 같은 유형이라고 판단할 수는 없습니다.', facts: ['검색 페이지는 현재 요청의 query를 같은 응답에 넣는다.', '게시판은 작성 시점과 다른 사용자의 목록 렌더링 시점 사이에 저장 단계를 둔다.', 'fragment 값은 HTTP 요청 원문에 없을 수 있고, 브라우저 코드가 실행 후 DOM에 반영할 수 있다.'] },
    { type: 'diagram', variant: 'flow', title: '세 경로는 해석 전에 갈라진다', body: '유형 이름을 외우기보다 source가 저장되는지, 서버 응답에 있는지, 브라우저 안에서 새 DOM을 만드는지를 따라가세요.', nodes: ['Reflected · query → 응답 → 렌더링', 'Stored · 작성값 → 저장소 → 재조회 → 렌더링', 'DOM-based · fragment 또는 client data → JavaScript → live DOM'] },
    { type: 'explanation', variant: 'deep-dive', title: '반사, 저장, DOM 기반을 데이터의 수명으로 읽기', paragraphs: [
      '반사형 XSS에서는 현재 요청의 값이 서버 응답에 포함되는 흐름을 먼저 확인합니다. 이 경우에는 요청, 응답 원문, 값이 놓인 HTML 문법을 같은 시점의 증거로 비교할 수 있습니다. 누군가가 어떤 링크를 클릭해야 한다는 사실은 영향 조건일 수 있지만, 유형을 결정하는 유일한 기준은 아닙니다.',
      '저장형 XSS에서는 입력이 게시글, 프로필, 지원 티켓처럼 저장된 뒤 다른 화면에서 다시 출력됩니다. 저장된 값이 있다는 사실만으로 실행이 확정되는 것은 아닙니다. 작성 화면, 저장소, 조회 화면 중 어디가 해석형 출력을 사용했는지와 누가 그 화면을 보게 되는지를 분리해야 합니다.',
      'DOM 기반 XSS에서는 서버 응답 원문에 입력이 없을 수 있습니다. URL fragment, 브라우저 저장소, API 응답 같은 값이 JavaScript를 거쳐 live DOM에 들어갈 수 있기 때문입니다. 이때는 View Source만으로 결론을 내리지 않고, client-side source와 sink, 실행 뒤 DOM을 함께 봅니다.',
    ] },
    { type: 'comparison', variant: 'decision-matrix', title: '유형을 가르는 관찰 근거', columns: ['경로', '먼저 확인할 증거', '아직 확인할 것'], rows: [
      ['반사형 후보', '현재 요청 값과 서버 응답 원문', '값이 어떤 HTML 문맥에 출력되는지'],
      ['저장형 후보', '작성값, 저장 기록, 나중의 조회 화면', '다른 사용자·역할이 실제로 보는지'],
      ['DOM 기반 후보', 'client-side source, JavaScript, live DOM', '서버 응답·API 값 중 실제 source가 무엇인지'],
    ] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-types-check-01', title: '증거만으로 먼저 고르기', prompt: '서버 응답 원문에는 고정 마커가 없고, 페이지가 로드된 뒤 JavaScript가 만든 DOM에만 마커가 보입니다. 우선 조사할 경로는?', options: ['DOM 기반 흐름', '저장형 흐름만', 'SQL 질의 흐름'], answer: 0, explanation: '실행 후 DOM에만 값이 생겼다는 사실은 client-side source와 sink를 먼저 보게 하는 근거입니다. 다만 실제 source가 무엇인지는 JavaScript와 데이터 응답을 더 확인해야 확정할 수 있습니다.' },
    { type: 'concept-ref', variant: 'reference', title: '증거를 읽을 때 쓰는 용어', intro: '응답 원문과 실행 후 DOM을 같은 것으로 보지 않기 위해 아래 개념을 다시 확인하세요.', conceptIds: ['server-response', 'live-dom', 'dom-node'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.dom, sources.wstg] },
  ],
  'w4-taint': [
    { type: 'question', variant: 'prediction', title: '코드에서 첫 줄과 마지막 줄 중 어디가 더 중요할까?', body: 'URL에서 값을 읽는 줄을 찾았다고 해서 취약점이 확정되지는 않습니다. 그 값이 어떤 변환을 거쳐 마지막에 어느 API로 전달되는지까지 따라가야 합니다.' },
    { type: 'cve-case', title: 'Reflected XSS: RESTEasy 오류 응답의 URL encoding', cve: 'CVE-2020-10688', classification: 'Reflected XSS · 공식 기록', cause: 'NVD는 RESTEASY003870 예외가 발생할 때 RESTEasy가 URL encoding을 올바르게 처리하지 않았다고 기록합니다.', condition: 'NVD가 명시한 영향 범위는 3.11.1.Final 이전 및 4.5.0 이상 4.5.3.Final 이전입니다. NVD의 CVSS는 사용자 상호작용(UI:R)을 전제로 합니다.', patch: 'NVD는 3.11.1.Final과 4.5.3.Final을 수정 경계로 기록하고, Red Hat 추적 항목을 Patch·Vendor Advisory로 연결합니다.', followOn: '이 CVE의 패치 우회 또는 후속 CVE 관계는 검증되지 않아 미채택입니다.', facts: ['반사형이라는 분류는 NVD 설명에 직접 명시되어 있습니다.', '이 수업의 로컬 검색어 예시는 CVE 구현 코드가 아니라 source·sink를 읽기 위한 무해한 합성 흐름입니다.'], sources: [sources.resteasyCve, sources.resteasyPatch] },
    { type: 'code', variant: 'annotated', language: 'JavaScript', title: '검색어가 DOM에 도착하는 여섯 단계', description: '이 코드는 고정 교육용 흐름입니다. 각 줄이 source, transform, sink 중 어디에 해당하는지 읽어 보세요.', code: 'const raw = location.search                         // 1. 브라우저가 가진 URL\nconst query = new URLSearchParams(raw).get(\'q\') ?? \'\' // 2. source 읽기\nconst label = `검색어: ${query}`                       // 3. 문자열 transform\nconst panel = document.querySelector(\'#results\')     // 4. DOM 대상 선택\npanel.innerHTML = label                                 // 5. interpreting sink\n// 수정: panel.textContent = label                       // 6. text sink', annotations: ['source는 값의 출발점이며, 이 자체가 실행을 뜻하지는 않습니다.', '문자열 결합과 DOM 대상 선택은 transform 또는 중간 처리입니다.', '실패 지점은 일반 텍스트가 필요한 기능에서 `innerHTML`이 값을 HTML로 해석하게 하는 마지막 단계입니다.', '수정은 입력을 지우는 일이 아니라, 값이 텍스트로 남도록 최종 출력 계약을 바꾸는 일입니다.'] },
    { type: 'diagram', variant: 'flow', title: 'source에서 browser interpretation까지', body: '흐름을 끊어 읽으면 필터가 있는지에만 시선이 갑니다. 이 그림은 값이 어느 경계에서 문법으로 바뀌는지를 보여 줍니다.', nodes: ['URL query · source', 'URLSearchParams · decode/parse', '문자열 조합 · transform', 'innerHTML · interpreting sink', 'HTML parser · browser interpretation', 'live DOM · 관찰 대상'] },
    { type: 'evidence-board', variant: 'source-sink', title: '지금 코드에서 확정된 것과 아직 모르는 것', sections: [
      { label: '관찰', items: ['값은 `location.search`에서 읽힌다.', '`panel.innerHTML`이 최종 출력 API다.'] },
      { label: '해석', items: ['일반 텍스트 목적이라면 해석형 sink가 실패 지점이 될 수 있다.'] },
      { label: '전제', items: ['실제 화면이 HTML 구조를 입력으로 받을 필요가 없는 기능이어야 한다.'] },
      { label: '미확인', items: ['다른 렌더링 경로가 같은 값을 다시 HTML로 출력하는지', '권한 있는 화면에서 같은 코드가 쓰이는지'] },
    ] },
    { type: 'explanation', variant: 'narrative', title: '중간 필터가 있어도 마지막 문맥을 확인하는 이유', paragraphs: [
      'source와 sink 사이에는 decode, validate, template rendering, 저장, 문자열 조합처럼 많은 변환이 있습니다. 어떤 단계가 값을 검사했다는 사실만으로 최종 출력이 안전하다고 결론 내리면 안 됩니다. 검사한 값과 브라우저가 읽는 값의 문맥·순서가 다를 수 있기 때문입니다.',
      'safe sink는 값을 "신뢰한다"고 선언하는 API가 아닙니다. 일반 텍스트 기능에서 그 값을 HTML 문법으로 읽지 않겠다는 출력 계약입니다. 반대로 제한된 HTML을 지원해야 하는 기능이라면 텍스트 API만으로 요구를 충족할 수 없으므로, 허용 구조를 정한 정화 정책이 별도로 필요합니다.',
      '이 흐름을 기록하면 보고서의 원인 문장도 구체적으로 바뀝니다. "필터가 약하다"보다 "query 값이 HTML 본문 컨텍스트의 interpreting sink로 전달되어 텍스트가 아닌 마크업으로 해석될 수 있다"가 재시험 가능한 설명입니다.',
    ] },
    { type: 'checkpoint', variant: 'short-answer', id: 'w4-taint-check-01', title: '실패 지점을 한 문장으로 적기', prompt: '위 코드에서 source, transform, interpreting sink를 각각 하나씩 적고, 일반 텍스트 기능에서 무엇을 바꿔야 하는지 80자 이상으로 설명하세요.', placeholder: '예: source는 ..., transform은 ..., sink는 ...이며 ...' },
    { type: 'concept-ref', variant: 'reference', title: '경로를 표시할 때 쓰는 개념', intro: '이 용어들은 이후 SQLi의 코드/데이터 경계와 AI 보안의 prompt/tool 경계에도 다시 나옵니다.', conceptIds: ['xss-source', 'data-transform', 'interpreting-sink', 'safe-sink'] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.resteasyCve, sources.resteasyPatch, sources.dom, sources.xss] },
    { type: 'summary', title: '코드에서 남길 네 가지 표시', bullets: ['source는 값이 들어온 지점이다.', 'transform은 값의 문법·수명·형태를 바꾼 중간 단계다.', 'sink는 값이 최종적으로 해석되거나 표시되는 위치다.', '일반 텍스트 기능은 safe sink로 출력 계약을 분명히 한다.'] },
  ],
  'w4-context': [
    { type: 'concept-ref', variant: 'prerequisite', title: '문법 위치를 구분하는 두 단어', intro: '출력 컨텍스트와 컨텍스트별 인코딩은 "특수문자 처리"라는 한 덩어리가 아닙니다. 먼저 어떤 파서가 값을 읽는지 봅니다.', conceptIds: ['output-context', 'contextual-output-encoding'] },
    { type: 'cve-case', title: 'Stored XSS: GitLab contact details의 저장·재출력', cve: 'CVE-2022-1948', classification: 'Stored XSS · 공식 기록', cause: 'NVD는 quick action에 사용한 입력의 validation 누락으로 contact details에 HTML을 주입해 XSS가 가능했다고 기록합니다.', condition: 'NVD는 GitLab 15.0부터 15.0.1 이전을 영향 범위로, 권한 필요(PR:L)와 사용자 상호작용(UI:R)을 CVSS 조건으로 기록합니다.', patch: 'GitLab 보안 핸드북은 first/last name escaping을 적용한 공식 패치 커밋과 15.0.1 완화를 연결합니다.', followOn: '이 패치와 다른 XSS CVE 사이의 우회·재발 관계는 검증되지 않아 미채택입니다.', facts: ['GitLab 공식 보안 핸드북은 이 사례를 “Stored XSS in 15.0”으로 명시합니다.', '이 수업의 게시글 실습은 실제 GitLab 경로나 코드를 복제하지 않는 브라우저 내 격리 데이터입니다.'], sources: [sources.gitlabCve, sources.gitlabPatch] },
    { type: 'explanation', variant: 'deep-dive', title: '값이 같은데 방어가 달라지는 이유', paragraphs: [
      '브라우저는 HTML 본문의 텍스트, 따옴표로 감싼 속성 값, URL 값, JavaScript 문자열을 서로 다른 규칙으로 읽습니다. 따라서 "입력에 특수문자가 있다"는 말만으로는 필요한 방어를 정할 수 없습니다. 값이 실제로 놓이는 문법 위치와 기능 요구를 먼저 알아야 합니다.',
      'HTML 본문에서 일반 문장을 보여 주는 가장 단순한 선택은 텍스트 노드로 넣는 것입니다. 속성 값은 허용된 속성 이름을 코드에서 고정하고 값만 설정하는 방식이 더 낫습니다. URL은 인코딩뿐 아니라 허용할 protocol과 목적지를 검토해야 하며, JavaScript 문자열 안에 외부 값을 직접 붙이는 설계는 가능한 한 피해야 합니다.',
      'CSS와 HTML comment처럼 안전하게 다루기 어려운 문법 위치도 있습니다. 이 위치에서는 "더 좋은 escape"를 찾기보다 신뢰할 수 없는 값을 넣지 않는 설계를 우선합니다. 컨텍스트는 지식 퀴즈가 아니라, 값이 코드와 데이터의 경계를 넘는지 판단하는 도구입니다.',
    ] },
    { type: 'comparison', variant: 'decision-matrix', title: '네 가지 출력 위치에서 먼저 묻는 질문', columns: ['출력 위치', '브라우저가 읽는 것', '첫 방어 선택'], rows: [
      ['HTML 본문', '텍스트 또는 HTML 구조', '텍스트 전용 출력 또는 HTML context encoding'],
      ['따옴표 속성 값', '속성의 값', '안전한 속성명을 고정하고 속성 값 처리'],
      ['URL 값', '이동할 주소와 protocol', 'URL 파싱 뒤 허용 scheme·목적지 검증'],
      ['JavaScript 데이터', '문자열 또는 코드 문법', 'inline 조합을 피하고 구조화된 데이터 전달'],
    ] },
    { type: 'code', sourceType: 'educational-reconstruction', variant: 'before-after', language: 'JavaScript', title: '링크 목적지는 HTML body와 다른 판단이 필요하다', description: '두 코드는 모두 링크를 다룹니다. 하지만 URL 값은 텍스트 출력과 달리 이동할 목적지와 protocol을 먼저 검토해야 합니다.', code: 'const next = readTrainingValue()\n\n// 값이 곧바로 링크 목적지가 된다.\nnextLink.href = next\n\n// URL을 해석한 뒤 교육용 허용 범위만 선택한다.\nconst url = new URL(next, location.origin)\nif ([\'http:\', \'https:\'].includes(url.protocol)) {\n  nextLink.href = url.href\n}', annotations: ['문자열을 HTML 본문에 넣는 문제와 URL 목적지를 허용하는 문제는 같지 않습니다.', '실제 서비스에서는 허용 origin, 상대 경로, redirect 정책 같은 추가 요구를 기능에 맞게 정해야 합니다.', '이 교육 예시는 외부 링크를 열지 않고 판단 결과만 설명합니다.'] },
    { type: 'misconception', variant: 'contrast', title: '같은 단어로 부르면 놓치는 차이', items: ['`escaping`, `encoding`, `sanitization`, `validation`은 모두 입력 필터다 → 출력 인코딩은 문맥에서 데이터를 표시하는 방식이고, 정화는 제한된 HTML 정책이며, validation은 허용할 데이터 형태를 정하는 별도 통제다.', 'HTML escape를 한 번 적용하면 URL과 JavaScript에도 안전하다 → 파서와 문법 위치가 다르므로 값이 들어갈 자리를 먼저 구분해야 한다.'] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-context-check-01', title: '수정 방향 고르기', prompt: '사용자가 입력한 "다음 페이지" 값을 링크의 목적지에 넣는 기능을 검토할 때, HTML body 인코딩만으로 충분하지 않은 가장 직접적인 이유는?', options: ['링크는 화면에 보이지 않기 때문', 'URL 값에는 허용할 protocol과 목적지를 따로 판단해야 하기 때문', '모든 링크는 무조건 제거해야 하기 때문'], answer: 1, explanation: 'URL은 브라우저가 이동할 목적지를 해석하는 문맥입니다. 값이 HTML 속성 안에 들어간다는 사실만으로 허용할 protocol·origin·redirect 정책이 정해지지는 않습니다.' },
    { type: 'retest', variant: 'context-matrix', title: '컨텍스트별 수정 뒤 비교할 항목', intro: '재시험은 한 개의 눈에 띄는 문자열만 넣어 보는 일이 아닙니다. 각 출력 위치에서 정상 기능과 문법 경계를 함께 확인합니다.', rows: [
      { label: 'HTML 본문', check: '일반 한글과 문법 문자가 텍스트로 남는가', expected: 'DOM 구조가 늘지 않고 화면 문장만 바뀜' },
      { label: '속성 값', check: '고정된 안전 속성의 값이 의도대로 보이는가', expected: '새 이벤트 속성·태그가 생기지 않음' },
      { label: 'URL', check: '허용된 상대·HTTPS 주소만 기능을 유지하는가', expected: '허용 밖 목적지는 안전하게 거부 또는 기본 경로 사용' },
      { label: 'JavaScript 데이터', check: '구조화된 데이터 전달 뒤 같은 화면 상태가 유지되는가', expected: 'inline 코드 조합 없이 값이 데이터로 처리됨' },
    ] },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.gitlabCve, sources.gitlabPatch, sources.xss] },
  ],
  'w4-impact': [
    { type: 'cve-case', title: 'DOM-based XSS: jQuery DOM 조작 메서드', cve: 'CVE-2020-11022', classification: 'DOM-based XSS · 공식 기록', cause: 'NVD는 신뢰할 수 없는 HTML을 정화한 뒤에도 jQuery의 `.html()`, `.append()` 등 DOM 조작 메서드에 전달하면 신뢰할 수 없는 코드가 실행될 수 있다고 기록합니다.', condition: 'NVD가 명시한 영향 범위는 jQuery 1.12.0 이상 3.5.0 미만이며, DOM 조작 API에 신뢰할 수 없는 HTML이 전달되는 조건을 함께 요구합니다.', patch: 'NVD와 jQuery 공식 3.5.0 릴리스는 이 문제의 패치가 jQuery 3.5.0에 포함됐다고 기록합니다.', followOn: '이 패치와 다른 XSS CVE 사이의 우회·재발 관계는 검증되지 않아 미채택입니다.', facts: ['서버가 보낸 원문에 값이 없을 수 있으므로 client-side source·sink와 live DOM을 함께 봐야 합니다.', '이 수업의 fragment 실습은 실제 jQuery 취약 코드가 아닌 무해한 로컬 DOM 흐름입니다.'], sources: [sources.jqueryCve, sources.jqueryPatch] },
    { type: 'case', variant: 'dom-evidence', title: 'View Source와 Elements가 다른 장면', body: '합성 페이지의 서버 응답 원문에는 fragment의 무해 마커가 없습니다. 페이지가 열린 뒤 JavaScript가 fragment를 읽고 live DOM에 반영하면 Elements에는 마커가 보일 수 있습니다. 이 차이는 실제 CVE의 취약 코드를 재현한 것이 아니라, DOM 기반 흐름에서 어떤 증거를 비교할지 보여 주는 안전한 로컬 예시입니다.' },
    { type: 'evidence-board', variant: 'dom-flow', title: 'DOM 기반 판단에 필요한 네 칸', sections: [
      { label: 'server response', items: ['초기 응답 원문에 source 값이 있는지', '서버 템플릿이 실제 source인지'] },
      { label: 'client-side source', items: ['fragment·브라우저 저장소·API 응답 중 값의 출발점', '값을 읽는 JavaScript 위치'] },
      { label: 'interpreting sink', items: ['DOM 조작 API가 HTML을 해석하는지', '일반 텍스트 기능인지 제한 HTML 기능인지'] },
      { label: 'live DOM', items: ['실행 뒤 어떤 노드가 생기는지', '수정 모드에서 같은 값이 텍스트로 남는지'] },
    ] },
    { type: 'explanation', variant: 'narrative', title: 'DOM API를 쓰는 순간, 데이터 수명은 브라우저 안에서 이어진다', paragraphs: [
      'DOM 기반 XSS에서는 서버가 안전한 HTML 응답을 보냈다는 사실만으로 충분하지 않을 수 있습니다. URL fragment, 브라우저 저장소, API 응답처럼 client-side에서 읽은 값이 JavaScript를 통해 HTML을 해석하는 DOM API로 전달되면, 취약성 판단의 핵심 증거는 실행 뒤의 live DOM과 그 값의 흐름입니다.',
      'CVE-2020-11022는 신뢰할 수 없는 HTML을 DOM 조작 메서드에 전달하는 조건을 명시합니다. “정화했으니 안전하다”는 전제만으로 끝내지 말고, 어떤 라이브러리 버전과 API가 받는 값인지, HTML 기능이 실제로 필요한지, safe DOM API 또는 정책화된 HTML 경로로 바뀌었는지를 확인해야 합니다.',
      'CSP는 예상 밖 스크립트 실행을 줄이는 보완 통제일 수 있지만, 신뢰 경계 밖 HTML이 해석형 DOM API로 가는 원인 자체를 자동으로 제거하지는 않습니다. 따라서 코드 경로와 live DOM을 다시 확인합니다.',
    ] },
    { type: 'concept-ref', variant: 'reference', title: 'DOM 흐름을 표시할 때 쓰는 개념', intro: 'source와 sink를 서버 응답 하나로 축소하지 않기 위해 아래 개념을 다시 확인하세요.', conceptIds: ['live-dom', 'xss-source', 'interpreting-sink', 'safe-sink'] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-impact-check-01', title: '먼저 볼 증거 고르기', prompt: '서버 응답 원문에는 마커가 없고, 페이지가 열린 뒤 만든 DOM에만 마커가 보인다. 우선 확인할 조합은?', options: ['서버 로그만', 'client-side source와 DOM 조작 sink, 실행 뒤 live DOM', '저장소 백업만'], answer: 1, explanation: '이 관찰은 브라우저 안의 데이터 흐름을 먼저 보게 하는 근거입니다. source가 무엇인지와 어떤 sink가 값을 해석하는지는 JavaScript와 live DOM을 함께 확인해야 합니다.' },
    { type: 'sources', title: '근거와 더 읽을 곳', items: [sources.jqueryCve, sources.jqueryPatch, sources.dom, sources.wstg] },
  ],
  'w4-defense': [
    { type: 'explanation', variant: 'narrative', title: '방어는 입력을 지우는 일이 아니라 출력 계약을 고치는 일', paragraphs: [
      '사용자 입력을 일반 글자로 보여 주는 기능이라면 가장 좋은 출발점은 해석형 HTML API를 사용하지 않는 것입니다. 프레임워크의 기본 escaping을 유지하고 `textContent`처럼 값이 텍스트로 남는 출력 지점을 사용하면, 브라우저가 입력을 마크업으로 다시 읽는 경로를 줄일 수 있습니다.',
      '제목과 댓글처럼 일반 텍스트만 필요한 기능과, 서식 있는 문서처럼 제한된 HTML이 필요한 기능은 요구가 다릅니다. 후자의 경우에는 어떤 태그와 속성을 허용할지 명시한 sanitization policy가 필요합니다. 정화는 모든 문자열을 똑같이 삭제하는 블랙리스트가 아니라, 제품 기능에 맞는 허용 구조를 관리하는 일입니다.',
      'URL은 허용 protocol과 목적지를, JavaScript 데이터는 inline 문자열 결합을 피하는 전달 방식을 따로 검토합니다. CSP, Cookie 속성, WAF는 영향 완화·탐지에 도움이 될 수 있지만, 텍스트를 HTML로 해석하는 원인 자체를 수정한 사실과 구분해야 합니다.',
    ] },
    { type: 'comparison', variant: 'patch-to-root-defense', title: '공식 패치와 근본 방어를 같은 흐름으로 읽기', columns: ['공식 패치 근거', '무엇을 바꿨는가', '제품에서 이어서 확인할 것'], rows: [
      ['CVE-2020-10688 · 3.11.1.Final / 4.5.3.Final', '오류 경로의 URL encoding 처리', '현재 요청과 오류 응답에서 외부 값이 HTML로 해석되지 않는지'],
      ['CVE-2022-1948 · GitLab escaping 커밋', 'contact name 출력의 escaping', '저장·재조회·다른 renderer의 동일한 출력 정책'],
      ['CVE-2020-11022 · jQuery 3.5.0', '신뢰 밖 HTML을 DOM 조작 API로 전달하는 문제 수정', '라이브러리 버전과 safe DOM API 또는 정책화된 HTML 경로'],
      ['CSP·Cookie 속성·WAF', '일부 실행·노출 영향 또는 탐지', '근본 sink 또는 encoding 경로가 실제로 바뀌었는지 별도 재시험'],
    ] },
    { type: 'diagram', variant: 'boundary', title: '수정 뒤에도 세 겹으로 확인한다', body: '그림은 하나의 제품에 세 종류의 통제가 서로 다른 질문에 답한다는 점을 보여 줍니다. 가장 안쪽의 출력 계약이 바뀌지 않으면 바깥 통제만으로 완료라고 쓰지 않습니다.', nodes: ['근본 수정 · safe sink 또는 정책화된 HTML', '보완 통제 · CSP·Cookie 속성·URL 정책', '운영 확인 · 로그·코드 리뷰·회귀 시험'] },
    { type: 'misconception', variant: 'contrast', title: '차단됐다는 화면이 곧 수정 완료는 아니다', items: ['CSP가 고정 PoC 표시를 막았으니 취약점도 사라졌다 → CSP는 보완 통제일 수 있습니다. 여전히 해석형 sink가 남아 있는지 코드와 DOM으로 확인해야 합니다.', '문자열 블랙리스트를 추가하면 안전한 출력이 된다 → 입력의 표면 표현을 늘려 막는 방식은 문법 위치와 새 경로를 보장하지 못합니다.'] },
    { type: 'retest', variant: 'regression', title: '수정 결과를 확인하는 네 가지 비교', intro: '같은 무해한 입력 범주를 수정 전과 수정 후에 비교합니다. 재시험은 실행 표시가 사라지는지와 기능이 남는지를 함께 봅니다.', rows: [
      { label: '정상 기능', check: '일반 제목·댓글이 기존처럼 표시·저장되는가', expected: '기능과 레이아웃이 유지됨' },
      { label: '문법 문자', check: '꺾쇠·따옴표가 포함된 일반 문장이 텍스트로 남는가', expected: '새 DOM 구조나 이벤트 경로가 생기지 않음' },
      { label: '저장·재조회', check: '작성 후 다른 목록·상세 화면에서 같은 정책이 적용되는가', expected: 'renderer 사이에 보호 차이가 없음' },
      { label: '보완 통제', check: 'CSP 등 정책이 기대한 제한을 제공하는가', expected: '근본 수정과 별개로 정책 결과를 기록함' },
    ] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-defense-check-01', title: '수정 우선순위 판단', prompt: '일반 텍스트만 보여 주는 프로필 이름 화면에서 가장 직접적인 근본 수정은?', options: ['CSP에 규칙 하나만 추가한다.', '프로필 이름을 textContent 또는 프레임워크 기본 escaping 경로로 출력한다.', '차단 문자열 목록을 두 배로 늘린다.'], answer: 1, explanation: '기능이 HTML을 요구하지 않는다면 해석형 출력 지점을 텍스트 전용 경로로 바꾸는 것이 원인을 직접 다룹니다. CSP와 필터는 남는 위험을 줄일 수 있지만, 그 자체로 출력 계약을 바꾸지는 않습니다.' },
    { type: 'concept-ref', variant: 'reference', title: '방어 선택을 위한 보충 개념', intro: '같은 "방어"라는 말 안에 서로 다른 목적이 섞이지 않도록 아래 개념을 연결해 둡니다.', conceptIds: ['safe-sink', 'html-sanitization-policy', 'csp', 'retest-and-regression'] },
    { type: 'sources', title: '공식 패치와 방어 근거', items: [sources.resteasyCve, sources.resteasyPatch, sources.gitlabPatch, sources.jqueryPatch, sources.xss, sources.dom] },
  ],
  'w4-validation': [
    { type: 'question', variant: 'lead', title: '패치가 들어갔다면, 무엇을 한 번 더 확인할까?', body: '수정된 화면에서 무해한 마커가 사라졌다는 결과만으로 끝내지 않습니다. 정상 입력, 같은 데이터의 재조회, 브라우저 안에서 다시 만들어지는 DOM 경로를 나눠 확인해야 합니다.' },
    { type: 'explanation', variant: 'narrative', title: '두 번째 확인은 패치의 주장과 기능의 결과를 나란히 본다', paragraphs: [
      'CVE의 패치 버전 또는 공식 커밋은 수정의 출발점입니다. 제품에 적용할 때는 그 버전이 실제 배포에 들어갔는지, 일반 텍스트가 여전히 정상으로 보이는지, 같은 값이 다른 renderer에서 다시 해석되지 않는지를 별도로 확인해야 합니다.',
      '이번 주의 세 사례는 반사·저장·DOM 기반이라는 서로 다른 수명 경로를 가집니다. 그래서 재시험도 현재 요청, 저장 후 재조회, client-side source에서 live DOM으로 가는 흐름을 각각 확인합니다. 공식 근거가 없는 “이 패치는 우회됐다”는 연결은 학습 경로에 넣지 않습니다.',
    ] },
    { type: 'evidence-board', variant: 'retest-map', title: '두 번째 확인의 증거 지도', sections: [
      { label: '공식 패치', items: ['CVE-2020-10688: 수정 버전 경계와 Red Hat Patch 참조', 'CVE-2022-1948: GitLab escaping 커밋', 'CVE-2020-11022: jQuery 3.5.0 릴리스'] },
      { label: '로컬 관찰', items: ['반사형: 현재 요청과 결과', '저장형: 저장 뒤 재조회', 'DOM 기반: client-side source와 live DOM'] },
      { label: '정상 기능', items: ['일반 텍스트가 저장·표시되는지', '허용된 링크와 화면 흐름이 유지되는지'] },
      { label: '미채택 주장', items: ['공식 근거 없는 패치 우회 관계', '외부 서비스에서의 재현 또는 영향 단정'] },
    ] },
    { type: 'retest', variant: 'regression', title: '로컬 안전 실습의 재시험 행렬', intro: '실제 CVE 대상이 아닌 이 학습 앱의 격리된 무해 마커로만 입력·경로·기대 결과를 나란히 확인합니다.', rows: [
      { label: '반사형 sandbox', check: '현재 요청·오류 경로·일반 검색어 비교', expected: '수정 모드에서는 마커가 HTML 구조가 아닌 텍스트로 남음' },
      { label: '저장형 sandbox', check: '작성·저장·목록·상세 재조회 비교', expected: '저장된 제목이 모든 로컬 renderer에서 텍스트로 남음' },
      { label: 'DOM sandbox', check: 'fragment 값과 실행 뒤 live DOM 비교', expected: '수정 모드에서는 새 DOM 구조가 생기지 않음' },
      { label: '공식 XSS Lab', check: '플랫폼이 제공한 인스턴스와 계정 범위만 사용', expected: '외부 서비스·개인 쿠키·토큰을 사용하지 않음' },
    ] },
    { type: 'practice-link', variant: 'readiness', title: 'Week 03의 네 가지 안전 활동', body: '활동은 아래 네 개만 학습 흐름에 포함합니다. 앞의 세 활동은 이 브라우저 안의 무해한 고정 마커만 사용하고, 마지막 연결은 공식 교육 플랫폼의 허가된 Lab만 엽니다.', labIds: ['w4-reflected', 'w4-stored', 'w4-dom', 'w4-official-xss'] },
    { type: 'checkpoint', variant: 'decision', id: 'w4-validation-check-01', title: '재시험 범위 고르기', prompt: '목록 renderer를 textContent로 수정한 뒤, 회귀 확인에 반드시 포함할 조합은?', options: ['수정한 화면에서 고정 마커 하나만 다시 본다.', '일반 제목, 문법 문자가 든 텍스트, 저장 후 재조회, 다른 renderer를 비교한다.', '보고서 제목만 바꾼다.'], answer: 1, explanation: '수정 뒤에는 취약한 경로가 사라졌는지와 정상 기능이 유지되는지를 모두 확인해야 합니다. 저장 후 재조회와 다른 renderer를 보지 않으면 같은 데이터가 다른 경로에서 다시 해석될 수 있습니다.' },
    { type: 'checkpoint', variant: 'decision', id: 'w4-validation-check-02', title: '검증되지 않은 연결 다루기', prompt: '어떤 글이 “이 CVE 패치가 다른 CVE로 우회됐다”고 말하지만 vendor·NVD·CVE 기록에서 관계를 확인하지 못했다. 이 수업의 올바른 처리 방식은?', options: ['학습 흥미를 위해 관계를 확정해 적는다.', '검증되지 않아 미채택으로 표시하고 독립 사례로만 다룬다.', '공격 코드를 먼저 시험해 확인한다.'], answer: 1, explanation: '공식 근거가 없는 우회·재발 관계는 사실처럼 연결하지 않습니다. 외부 시스템을 시험하는 것도 이 학습 범위를 벗어납니다.' },
    { type: 'concept-ref', variant: 'reference', title: '다음 주로 가져갈 확인 습관', intro: 'Week 04 SQLi에서도 값과 코드의 경계가 어디서 깨졌는지, 패치가 어느 경로를 바꿨는지, 정상 기능을 어떻게 확인했는지부터 적습니다.', conceptIds: ['observation-inference', 'impact-conditions', 'retest-and-regression'] },
    { type: 'sources', title: '공식 근거와 다음 학습', items: [sources.resteasyCve, sources.gitlabCve, sources.jqueryCve, sources.wstg, sources.xss] },
    { type: 'summary', title: 'Week 03을 마치기 전 확인할 것', bullets: ['반사형·저장형·DOM 기반 CVE의 원인·조건·패치를 각각 공식 근거로 확인했다.', '근본 수정과 CSP 같은 보완 통제를 구분했다.', '네 가지 허용 활동만 열고 외부 대상·자격 증명·실제 CVE 코드는 사용하지 않았다.', '검증되지 않은 패치 우회 관계는 미채택으로 기록했다.'] },
  ],
}

export const week4LessonBlocks = Object.freeze(baseWeek4LessonBlocks)

export const week4ReportEvidenceScenario = reportEvidenceScenario
