const sources = {
  bash: { label: 'GNU Bash Reference Manual', url: 'https://www.gnu.org/software/bash/manual/', note: '셸의 명령 해석, 인용, 확장 규칙을 확인합니다.' },
  coreutils: { label: 'GNU Coreutils Manual', url: 'https://www.gnu.org/software/coreutils/manual/html_node/', note: 'pwd, ls, cat, head, tail 등 기본 명령의 공식 설명입니다.' },
  findutils: { label: 'GNU Findutils Manual', url: 'https://www.gnu.org/software/findutils/manual/', note: 'find와 grep을 포함한 검색 도구의 공식 매뉴얼입니다.' },
  file: { label: 'file(1) manual page', url: 'https://man7.org/linux/man-pages/man1/file.1.html', note: '파일 형식 판별이 무엇을 확인하는지 설명합니다.' },
  fhs: { label: 'Filesystem Hierarchy Standard 3.0', url: 'https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html', note: 'Linux 디렉터리 구조의 목적을 확인합니다.' },
  openssh: { label: 'OpenSSH ssh(1) Manual', url: 'https://man.openbsd.org/ssh', note: 'SSH 클라이언트의 공식 사용법을 확인합니다.' },
}

const answer = (id, prompt, answerGuide, options, correct, explanation) => ({
  type: 'checkpoint', id, prompt, answerGuide, ...(options ? { options, answer: correct, explanation } : {}),
})

export const week1LessonBlocks = Object.freeze({
  'w1-shell': [
    { type: 'question', body: '터미널에서 입력한 명령은 어떤 과정을 거쳐 파일을 읽고 화면에 출력될까?' },
    { type: 'explanation', title: '터미널, 셸, 커널은 역할이 다릅니다', paragraphs: ['터미널은 키보드 입력과 문자 출력을 보여 주는 인터페이스입니다. 셸은 입력한 한 줄을 명령 이름, 옵션, 인자로 나누고 프로그램을 실행합니다. 커널은 실행된 프로그램이 파일·프로세스·네트워크 같은 운영체제 자원에 접근하도록 처리합니다.', '명령이 실패했을 때는 화면이 고장 났다고 결론내리지 않습니다. 실행 계정, 현재 경로, 입력한 인자, 오류 메시지, 종료 상태를 차례로 확인합니다. 이 다섯 가지가 있으면 다른 사람도 같은 상황을 다시 확인할 수 있습니다.'] },
    { type: 'diagram', title: '명령 한 줄이 처리되는 흐름', nodes: ['터미널 입력', '셸: 명령·옵션·인자 해석', '프로그램 실행', '커널: 파일·프로세스 요청', '표준 출력 또는 오류 출력', '터미널 표시'] },
    { type: 'terminal', title: '명령 형식과 종료 상태', command: '$ pwd\n/home/student\n$ ls -l missing.txt\nls: cannot access \'missing.txt\': No such file or directory\n$ echo $?', output: '2', annotations: ['`pwd`의 결과는 표준 출력으로 나옵니다.', '`ls`의 진단 메시지는 표준 오류로 나올 수 있습니다.', '종료 상태 0은 보통 성공을 뜻합니다. 0이 아닌 값의 정확한 의미는 각 명령의 문서에서 확인합니다.'] },
    { type: 'comparison', title: '명령줄을 읽는 순서', columns: ['부분', '예시', '확인할 질문'], rows: [['명령', '`ls`', '무슨 프로그램 또는 셸 내장 명령인가?'], ['옵션', '`-l`, `-a`, `-h`', '출력이나 동작을 어떻게 바꾸는가?'], ['인자', '`/var/log`', '무엇을 대상으로 하는가?'], ['실행 맥락', '`student@host:/home/student`', '어느 계정과 현재 경로에서 실행했는가?']] },
    { type: 'case', title: '실행 전 확인 순서', body: '오류 로그를 열기 전에는 `pwd`로 기준 경로를 확인하고, 대상 이름과 `file` 결과, 권한을 함께 봅니다. 그러면 파일이 없는지, 디렉터리인지, 읽을 권한이 없는지를 구분할 수 있습니다.', facts: ['입력 문자열이 같아도 현재 위치와 사용자 권한이 결과를 바꿉니다.', '오류 메시지와 종료 상태는 원인을 좁히는 관찰값입니다.', '사용자·호스트·경로는 조사 기록에 함께 남깁니다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['터미널과 셸은 같은 것이다 → 터미널은 입출력 창이고 셸은 명령줄을 해석하는 프로그램입니다.', '종료 상태가 0이 아니면 항상 보안 문제다 → 먼저 명령의 정상 오류 조건과 입력·경로를 확인합니다.'] },
    answer('w1-shell-check-01', '상대 경로를 현재 디렉터리와 결합해 프로그램에 전달하는 역할에 가장 가까운 것은?', '정답: 셸. 셸은 명령줄을 해석해 프로그램 실행에 필요한 인자와 환경을 구성합니다.', ['셸', '모니터', '파일 확장자'], 0, '셸은 명령줄을 해석해 프로그램 실행에 필요한 인자와 환경을 구성합니다.'),
    answer('w1-shell-check-02', '`cat report.txt`가 실패했을 때 기록할 최소 사실 세 가지는?', '예시 답: 현재 경로(`pwd`), 실행 계정, 입력한 전체 명령과 대상 경로, 오류 메시지 또는 종료 상태 중 세 가지 이상을 남깁니다.'),
    { type: 'work-context', title: '보안 업무에서의 사용', body: '관제, 포렌식, 시스템 보안에서는 명령 자체보다 실행 계정, 호스트, 현재 위치, 입력, 출력, 시각을 같이 남겨야 다른 사람이 결과를 재검토할 수 있습니다.' },
    { type: 'practice-link', title: '다음 활동', body: '가상 셸에서 `pwd`와 `ls`가 알려 주는 실행 맥락을 확인합니다.', labIds: ['w1-treasure'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.bash, sources.coreutils] },
    { type: 'summary', title: '핵심 정리', bullets: ['터미널은 입출력, 셸은 명령 해석, 커널은 자원 요청 처리라는 역할을 가집니다.', '명령은 명령·옵션·인자와 실행 맥락으로 읽습니다.', '오류 메시지와 종료 상태는 다음 확인의 시작점입니다.'] },
  ],
  'w1-filesystem': [
    { type: 'question', body: '절대 경로와 상대 경로는 파일을 찾는 기준을 어떻게 다르게 만들까?' },
    { type: 'explanation', title: '경로는 파일을 찾는 방법입니다', paragraphs: ['Linux 파일 시스템은 `/`에서 시작하는 하나의 디렉터리 트리로 보입니다. `/home`은 사용자 홈, `/etc`는 시스템 설정, `/var`는 로그처럼 변하는 데이터에 흔히 사용됩니다. 디렉터리 관례는 이해를 돕지만 실제 시스템의 구조와 권한은 환경마다 다를 수 있습니다.', '절대 경로는 `/`부터 시작해 실행 위치와 관계없이 같은 위치를 가리킵니다. 상대 경로는 현재 작업 디렉터리(CWD)에서 시작합니다. `.`은 현재 디렉터리, `..`은 상위 디렉터리, `~`는 현재 사용자의 홈 디렉터리로 확장됩니다.'] },
    { type: 'diagram', title: '상대 경로가 해석되는 과정', nodes: ['현재 위치 `/home/student`', '입력 `notes/todo.txt`', '경로 결합 `/home/student/notes/todo.txt`', '대상 존재·권한 확인', '파일 내용 또는 오류 출력'] },
    { type: 'terminal', title: '절대 경로와 상대 경로', command: '$ pwd\n/home/student\n$ cat notes/todo.txt\nreview access log\n$ cd /tmp\n$ cat notes/todo.txt', output: 'cat: notes/todo.txt: No such file or directory', annotations: ['같은 상대 경로 문자열도 현재 위치가 달라지면 다른 위치를 뜻합니다.', '절대 경로 `/home/student/notes/todo.txt`는 두 위치에서 같은 파일을 가리킵니다.'] },
    { type: 'comparison', title: '경로 표기 비교', columns: ['표기', '시작점', '읽는 법'], rows: [['`/etc/training/app.conf`', '루트 `/`', '어디서 실행해도 같은 경로'], ['`logs/access.log`', '현재 디렉터리', '현재 위치를 기록해야 재현 가능'], ['`./run.sh`', '현재 디렉터리', '현재 위치의 파일임을 명시'], ['`../backup`', '상위 디렉터리', '현재 위치의 부모 아래 경로']] },
    { type: 'case', title: '숨김 이름과 실제 파일 형식', body: '`.env.example`처럼 점으로 시작하는 이름은 일반 `ls` 목록에서 숨겨집니다. 이것은 표시 규칙일 뿐 접근 통제가 아닙니다. 파일 확장자도 이름의 일부이므로, 내용을 읽기 전 `file`로 형식 후보를 확인합니다.', facts: ['숨김 표기는 권한이나 암호화를 제공하지 않습니다.', '확장자는 실제 형식을 보장하지 않습니다.', '경로, 내용 형식, 권한, 소유자는 서로 다른 관찰 항목입니다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`/`는 현재 폴더다 → `/`는 파일 시스템의 루트이고 현재 폴더는 `pwd`로 확인합니다.', '점으로 시작하면 안전한 비밀 파일이다 → 목록 표시 방식일 뿐 권한이나 암호화를 제공하지 않습니다.'] },
    answer('w1-filesystem-check-01', '현재 위치가 `/var/log`일 때 `../tmp/report.txt`는 어느 절대 경로를 뜻할까?', '정답: `/var/tmp/report.txt`. `..`은 `/var/log`의 상위인 `/var`을 뜻합니다.', ['/var/tmp/report.txt', '/tmp/report.txt', '/var/log/tmp/report.txt'], 0, '`..`은 `/var/log`의 상위인 `/var`을 뜻하므로 `/var/tmp/report.txt`가 됩니다.'),
    answer('w1-filesystem-check-02', '처음 보는 `backup.bin`을 실행하거나 열기 전에 무엇을 확인할까?', '예시 답: `pwd`와 절대 경로로 대상을 확인하고, `ls -l` 또는 `stat`으로 권한·소유자·크기를 확인합니다. `file backup.bin`으로 형식 후보를 보고, 출처가 불명확하면 실행하지 않습니다.'),
    { type: 'work-context', title: '보안 업무에서의 사용', body: '사고 분석과 취약점 재현 기록에서는 기준 디렉터리와 절대 경로를 함께 남깁니다. 경로가 빠지면 같은 명령도 다른 파일을 대상으로 다시 실행될 수 있습니다.' },
    { type: 'practice-link', title: '다음 활동', body: '가상 파일 시스템에서 현재 위치와 실제 경로를 확인하며 FLAG를 찾습니다.', labIds: ['w1-treasure'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.fhs, sources.coreutils, sources.file] },
    { type: 'summary', title: '핵심 정리', bullets: ['절대 경로는 `/`, 상대 경로는 현재 작업 디렉터리에서 시작합니다.', '`.`·`..`·`~`는 경로 해석의 기준을 바꿉니다.', '숨김 표기와 확장자는 접근 통제나 실제 파일 형식을 보장하지 않습니다.'] },
  ],
  'w1-navigation': [
    { type: 'question', body: '경로를 찾는 명령과 파일 안의 줄을 찾는 명령은 어떤 질문에 각각 답할까?' },
    { type: 'explanation', title: '명령을 확인 질문에 연결합니다', paragraphs: ['탐색의 시작은 현재 위치와 목록입니다. `pwd`로 기준 경로를 확인하고 `ls`로 이름과 메타데이터를 봅니다. 그 뒤에 `cd`로 이동하고, `file`로 형식을 확인한 뒤 읽기 또는 검색 명령을 고릅니다.', '검색은 두 단계로 나누면 결과를 설명하기 쉽습니다. `find [시작 경로] [조건]`은 파일 시스템 항목의 경로를 찾고, `grep [옵션] 패턴 [파일...]`은 지정한 텍스트 안의 줄을 찾습니다. 후보 경로를 먼저 좁힌 뒤 내용을 검색합니다.'] },
    { type: 'command-guide', title: '목록·경로·파일 형식 명령', intro: '대괄호 `[]` 안은 선택 항목이고, `...`은 같은 종류의 인자를 여러 개 받을 수 있다는 뜻입니다. 옵션은 필요한 것만 골라 사용합니다.', commands: [
      { syntax: 'pwd', purpose: '현재 작업 디렉터리를 출력합니다.', options: [{ flag: '인자 없음', description: '상대 경로가 어디를 기준으로 해석되는지 확인할 때 먼저 실행합니다.' }] },
      { syntax: 'ls [옵션] [파일 또는 디렉터리...]', purpose: '이름 목록과 선택한 메타데이터를 확인합니다.', options: [{ flag: '-a, --all', description: '점(`.`)으로 시작하는 숨김 이름까지 포함합니다.' }, { flag: '-l', description: '파일 유형·권한·링크 수·소유자·그룹·크기·시간·이름을 긴 형식으로 봅니다.' }, { flag: '-h', description: '`-l`과 함께 사용할 때 크기를 KiB, MiB처럼 읽기 쉬운 단위로 표시합니다.' }, { flag: '-t', description: '수정 시각을 기준으로 정렬합니다. 최근 변경 후보를 볼 때 사용합니다.' }, { flag: '-S', description: '크기를 기준으로 정렬합니다. 큰 파일을 살펴볼 때 사용합니다.' }, { flag: '-R', description: '하위 디렉터리까지 재귀적으로 표시합니다. 출력이 커질 수 있으므로 범위를 좁힌 뒤 사용합니다.' }] },
      { syntax: 'cd [디렉터리]', purpose: '현재 작업 디렉터리를 바꿉니다.', options: [{ flag: 'cd', description: '인자 없이 실행하면 보통 현재 사용자의 홈 디렉터리로 이동합니다.' }, { flag: 'cd ..', description: '현재 디렉터리의 상위로 이동합니다.' }, { flag: 'cd -', description: '직전 작업 디렉터리로 돌아갑니다. 이동 뒤에는 `pwd`로 확인합니다.' }] },
      { syntax: 'file [옵션] 파일...', purpose: '확장자가 아니라 파일 내용의 특징과 매직 값을 바탕으로 형식 후보를 표시합니다.', options: [{ flag: '-b, --brief', description: '파일명 접두사를 빼고 형식 설명만 출력합니다.' }, { flag: '-L, --dereference', description: '심볼릭 링크 자체가 아니라 링크가 가리키는 대상을 확인합니다.' }, { flag: '-z, --uncompress', description: '지원되는 압축 파일의 내부 내용도 확인합니다. 결과가 안전성을 보장하지는 않습니다.' }, { flag: '해석', description: '`file`은 실행 안전성 판정 도구가 아닙니다. 출처가 불명확한 파일은 확인을 위해서도 실행하지 않습니다.' }] },
      { syntax: 'find [시작 경로] [조건...]', purpose: '경로와 메타데이터 조건에 맞는 파일 시스템 항목을 찾습니다.', options: [{ flag: '-type f', description: '일반 파일만 찾습니다.' }, { flag: '-type d', description: '디렉터리만 찾습니다.' }, { flag: '-name "패턴"', description: '이름을 대소문자까지 구분해 찾습니다. 셸 확장을 막기 위해 패턴을 따옴표로 묶습니다.' }, { flag: '-iname "패턴"', description: '대소문자를 구분하지 않고 이름을 찾습니다.' }, { flag: '-maxdepth N', description: '시작 경로에서 내려갈 깊이를 제한합니다. 큰 트리에서는 범위를 먼저 좁힙니다.' }] },
    ] },
    { type: 'command-guide', title: '텍스트·로그·표현 형식 관찰 명령', intro: '읽을 대상이 텍스트인지와 범위를 먼저 확인합니다. 큰 파일이나 바이너리를 무작정 전체 출력하지 않습니다.', commands: [
      { syntax: 'grep [옵션] 패턴 [파일...]', purpose: '지정한 텍스트 파일에서 패턴과 일치하는 줄을 출력합니다.', options: [{ flag: '-i', description: '대소문자를 구분하지 않습니다.' }, { flag: '-n', description: '결과 앞에 줄 번호를 붙입니다. 기록과 재확인에 유용합니다.' }, { flag: '-v', description: '패턴과 일치하지 않는 줄을 출력합니다.' }, { flag: '-w', description: '단어 단위 일치만 찾습니다. 짧은 문자열의 과도한 일치를 줄일 수 있습니다.' }, { flag: '-E', description: '확장 정규표현식을 사용합니다. 정규표현식은 작은 교육용 또는 허가된 데이터에서 먼저 검증합니다.' }, { flag: '-l', description: '일치한 줄 대신 일치가 있는 파일명만 출력합니다.' }, { flag: '-r', description: '디렉터리 아래 파일을 재귀 검색합니다. 범위와 대상 디렉터리를 명시합니다.' }] },
      { syntax: 'cat [파일...] / less [파일]', purpose: '짧은 텍스트는 `cat`, 긴 텍스트는 페이지 단위 탐색이 가능한 `less`로 읽습니다.', options: [{ flag: 'cat', description: '파일 전체를 표준 출력으로 보냅니다. 긴 로그나 바이너리에는 적합하지 않습니다.' }, { flag: 'less', description: '화면 단위로 이동하고 `/패턴`으로 찾을 수 있습니다. `q`로 종료합니다.' }] },
      { syntax: 'head [-n N] 파일 / tail [-n N] 파일', purpose: '파일의 앞부분 또는 뒷부분 일부만 봅니다.', options: [{ flag: '-n N', description: '볼 줄 수를 지정합니다. 예: `tail -n 20 access.log`.' }, { flag: 'tail -f', description: '파일 끝에 추가되는 내용을 계속 표시합니다. 운영 로그에서는 허가된 대상과 종료 조건을 정한 뒤 사용합니다.' }] },
      { syntax: 'sort / uniq -c / cut -d 구분자 -f 필드 / wc -l', purpose: '작은 텍스트 처리 단계를 조합해 중복·필드·규모를 확인합니다.', options: [{ flag: 'sort', description: '같은 값을 모으기 위해 정렬합니다.' }, { flag: 'uniq -c', description: '인접한 같은 줄을 하나로 묶고 발생 횟수를 셉니다. 보통 `sort` 뒤에 둡니다.' }, { flag: 'cut -d : -f 1', description: '구분자와 필드 번호로 필요한 열을 고릅니다.' }, { flag: 'wc -l', description: '줄 수를 세어 처리 범위를 확인합니다.' }] },
      { syntax: 'strings 파일 / xxd 파일 / base64', purpose: '바이너리·바이트·인코딩 표현을 구분해 관찰합니다.', options: [{ flag: 'strings', description: '인쇄 가능한 문자열 후보만 보여 줍니다. 파일의 전체 의미를 해석하지는 않습니다.' }, { flag: 'xxd', description: '바이트를 16진수와 문자로 나란히 보여 줍니다.' }, { flag: 'base64', description: '문자 기반 표현을 인코딩·디코딩합니다. Base64는 암호화가 아니며 비밀성을 제공하지 않습니다.' }] },
      { syntax: 'man 명령 / 명령 --help', purpose: '명령의 공식 사용법과 옵션을 확인합니다.', options: [{ flag: 'SYNOPSIS', description: '명령 형식과 필수·선택 인자를 읽습니다.' }, { flag: 'OPTIONS', description: '현재 질문에 필요한 옵션만 찾아 의미와 기본값을 확인합니다.' }] },
    ] },
    { type: 'terminal', title: '경로를 찾고 줄을 찾는 순서', command: '$ find /var/log/training -type f -name "*.log"\n/var/log/training/access.log\n/var/log/training/error.log\n$ grep -n "validation failed" /var/log/training/error.log', output: '18:request_id=req-demo-42 upload validation failed: unsupported media type', annotations: ['`find` 결과는 경로 후보입니다.', '`grep -n` 결과는 지정한 파일 안에서 패턴이 있는 줄과 줄 번호입니다.', '출력 한 줄만으로 원인을 단정하지 말고 앞뒤 로그와 요청 조건을 확인합니다.'] },
    { type: 'code', title: '공백·하이픈 이름을 다루는 기본형', language: 'bash', code: "cat 'weekly report.txt'\ncat -- -note\nls -l -- -note", annotations: ['따옴표는 공백이 있는 이름을 하나의 인자로 유지합니다.', '`--`는 뒤의 값을 옵션이 아니라 파일명으로 해석합니다.', '와일드카드 `*`는 셸이 실행 전에 여러 이름으로 확장할 수 있으므로 대상 목록을 먼저 확인합니다.'] },
    { type: 'case', title: 'Bandit 전에 기록할 조사 순서', body: '어떤 파일에 비밀 값이 있을 수 있는 과제에서는 바로 `cat`을 반복하지 않습니다. 현재 위치, 목록, 숨김 여부, 형식, 후보 경로, 텍스트 패턴 순서로 관찰합니다. 이 순서는 운영 로그와 포렌식 자료에서도 같은 방식으로 적용됩니다.', facts: ['`ls -al`은 숨김 이름과 상세 정보를 함께 봅니다.', '`file`은 텍스트인지 바이너리인지 구분하는 데 도움을 줍니다.', '`find`와 `grep`은 각각 경로와 내용이라는 다른 질문에 답합니다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`grep`이 파일을 찾아 준다 → `grep`은 지정한 파일의 내용 줄을 검색합니다. 경로 후보는 `find` 등으로 먼저 찾습니다.', '`ls -al`이 모든 권한 문제를 해결한다 → 목록을 볼 수 있는지와 파일을 읽거나 디렉터리에 들어갈 수 있는지는 다릅니다.'] },
    answer('w1-navigation-check-01', '하위 디렉터리를 포함해 `.log` 파일의 경로를 찾는 가장 알맞은 시작 명령은?', '정답: `find . -type f -name "*.log"`. `find`는 파일 시스템의 경로와 조건을 다룹니다.', ['`find . -type f -name "*.log"`', '`grep -n ".log" .`', '`cat *.log`'], 0, '`find`는 파일 시스템의 경로와 조건을 다룹니다. `grep`은 파일 내용을 검색합니다.'),
    answer('w1-navigation-check-02', '숨김 파일일 수 있고 하위 경로 어딘가의 로그에 `security_flag` 텍스트가 있다면 어떤 순서로 볼까?', '예시 답: `pwd`로 기준을 확인한 뒤 `ls -al`로 숨김 이름을 포함해 목록을 봅니다. `find . -type f -name "*.log"`로 후보 경로를 찾고, 대상 파일에 `grep -n "security_flag" 경로`를 적용합니다.'),
    { type: 'work-context', title: '보안 업무에서의 사용', body: '로그 분석과 포렌식에서는 전체 디스크나 모든 로그를 무작정 읽지 않습니다. 시작 경로, 시간 범위, 파일 형식, 패턴, 줄 번호를 기록해 같은 결과를 재확인할 수 있게 합니다.' },
    { type: 'practice-link', title: '다음 활동', body: '목록, 파일 형식, 경로, 텍스트 검색을 순서대로 써서 두 가지 가상 실습을 풉니다.', labIds: ['w1-treasure', 'w1-command-ctf'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.coreutils, sources.findutils, sources.file] },
    { type: 'summary', title: '핵심 정리', bullets: ['`pwd`·`ls`로 맥락을 확인한 뒤 이동·형식 확인·읽기·검색을 진행합니다.', '`find`는 경로, `grep`은 텍스트 줄을 검색합니다.', '옵션은 외우기보다 명령 형식과 함께 읽고 필요한 것만 고릅니다.'] },
  ],
  'w1-fileops': [
    { type: 'question', body: '파일을 바꾸는 명령은 실행 전에 무엇을 확인해야 실수를 줄일 수 있을까?' },
    { type: 'explanation', title: '변경 명령은 대상과 영향 범위를 먼저 읽습니다', paragraphs: ['파일 조작 명령은 이름이 비슷해도 결과가 다릅니다. `touch`는 파일을 만들거나 시간 정보를 갱신하고, `mkdir`는 디렉터리를 만들며, `cp`는 복사하고 `mv`는 이동 또는 이름 변경을 합니다. `rm`은 휴지통을 거치지 않고 삭제합니다.', '실행 전에는 현재 위치, 출발 대상, 도착 대상, 와일드카드가 확장한 목록, 재귀 옵션 여부를 확인합니다. 특히 교육용 작업 디렉터리 밖에서 재귀 삭제를 연습하지 않습니다.'] },
    { type: 'command-guide', title: '파일과 디렉터리를 바꾸는 명령', intro: '아래 명령은 실제 변경을 만듭니다. 처음에는 연습용 디렉터리에서 한 파일씩 실행한 뒤 `ls -l`로 결과를 확인합니다.', commands: [
      { syntax: 'touch [옵션] 파일...', purpose: '빈 파일을 만들거나 기존 파일의 시간 정보를 갱신합니다.', options: [{ flag: '-c', description: '파일이 없으면 새로 만들지 않습니다.' }, { flag: '-t 시간', description: '접근·수정 시간을 지정합니다. 시간 형식은 `man touch`에서 확인합니다.' }] },
      { syntax: 'mkdir [옵션] 디렉터리...', purpose: '새 디렉터리를 만듭니다.', options: [{ flag: '-p', description: '중간 디렉터리도 함께 만들고 이미 있어도 오류를 줄입니다.' }, { flag: '-m MODE', description: '생성 직후의 권한 모드를 지정합니다. 조직의 기본 권한 정책과 함께 검토합니다.' }] },
      { syntax: 'cp [옵션] 출발 대상', purpose: '파일 또는 디렉터리를 복사합니다.', options: [{ flag: '-i', description: '기존 대상 파일을 덮어쓰기 전 확인을 요청합니다.' }, { flag: '-n', description: '이미 대상 파일이 있으면 덮어쓰지 않습니다.' }, { flag: '-r, -R', description: '디렉터리와 하위 항목을 재귀적으로 복사합니다. 출발·대상 경로를 다시 확인합니다.' }] },
      { syntax: 'mv [옵션] 출발 대상', purpose: '파일을 이동하거나 이름을 바꿉니다.', options: [{ flag: '-i', description: '기존 대상 파일을 덮어쓰기 전 확인을 요청합니다.' }, { flag: '-n', description: '이미 대상 파일이 있으면 덮어쓰지 않습니다.' }] },
      { syntax: 'rm [옵션] 파일...', purpose: '파일을 삭제합니다.', options: [{ flag: '-i', description: '각 삭제 전에 확인을 요청합니다.' }, { flag: '-I', description: '여러 파일 또는 재귀 삭제 전에 한 번 확인을 요청합니다.' }, { flag: '-r, -R', description: '디렉터리와 하위 항목을 재귀 삭제합니다. 교육용 임시 디렉터리에서만, 대상 목록을 확인한 뒤 사용합니다.' }, { flag: '금지 습관', description: '의미를 이해하지 못한 `rm -rf` 조합을 복사해 실행하지 않습니다.' }] },
      { syntax: 'rmdir [옵션] 디렉터리...', purpose: '비어 있는 디렉터리만 삭제합니다.', options: [{ flag: '--ignore-fail-on-non-empty', description: '비어 있지 않은 디렉터리 오류를 무시합니다. 내용은 삭제하지 않습니다.' }] },
    ] },
    { type: 'code', title: '셸이 인자를 나누는 방식', language: 'bash', code: "mkdir -p practice/logs\ntouch 'practice/logs/weekly report.txt'\ncp -i 'practice/logs/weekly report.txt' practice/logs/archive.txt\nls -l practice/logs", annotations: ['작은따옴표는 공백이 있는 이름을 하나의 인자로 전달합니다.', '`mkdir -p`는 없는 중간 경로를 함께 만듭니다.', '복사 후에는 대상 디렉터리를 목록으로 확인합니다.'] },
    { type: 'comparison', title: '이름 처리 규칙', columns: ['표현', '셸의 해석', '확인 방법'], rows: [['`*`', '0개 이상 문자열에 맞는 이름 목록으로 확장될 수 있음', '`echo 패턴`으로 확장 결과를 먼저 확인'], ['`?`', '한 글자에 맞는 이름 목록으로 확장될 수 있음', '범위가 넓지 않은지 목록 확인'], ['`"이름"`', '공백을 포함한 하나의 인자', '변수는 확장될 수 있음'], ["'이름'", '문자 그대로 하나의 인자', '특수문자 해석을 줄임'], ['`-- -name`', '옵션 해석 종료 뒤 파일명', '하이픈으로 시작한 이름을 안전하게 전달']] },
    { type: 'case', title: '변경 전 짧은 점검', body: '반복 작업 전에 `pwd`, `ls -la`, 출발·대상 경로, 옵션, 예상되는 변경 수를 확인합니다. 파일을 지우거나 덮어쓴 뒤에는 되돌리는 절차가 별도로 필요할 수 있습니다.', facts: ['`cp`와 `mv`는 기존 파일을 덮어쓸 수 있습니다.', '글로빙은 명령 실행 전에 셸이 파일명 목록으로 확장합니다.', '변경 뒤에는 목록과 내용으로 결과를 다시 확인합니다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`rm`은 휴지통으로 보낸다 → 일반적인 Linux `rm`은 즉시 삭제하며 휴지통을 거치지 않습니다.', '`*`는 명령이 알아서 안전하게 처리한다 → 셸이 예상보다 넓은 파일명 목록으로 확장할 수 있습니다.'] },
    answer('w1-fileops-check-01', '기존 파일을 실수로 덮어쓰지 않고 복사할 때 가장 직접적으로 쓸 수 있는 옵션은?', '정답: `cp -i` 또는 `cp -n`. `-i`는 확인을 요청하고 `-n`은 기존 파일을 덮어쓰지 않습니다.', ['`cp -i`', '`cp -r`만', '`rm -r`'], 0, '`cp -i`는 기존 대상 파일을 덮어쓰기 전 확인을 요청합니다.'),
    answer('w1-fileops-check-02', '재귀 삭제 명령을 실행하기 전 확인할 항목을 적어 보세요.', '예시 답: `pwd`로 현재 위치를 확인하고, 실제 대상 경로와 와일드카드 확장 결과, 하위 항목 수, 복구 가능 여부를 확인합니다. 교육용 임시 디렉터리 밖에서는 실행하지 않습니다.'),
    { type: 'work-context', title: '보안 업무에서의 사용', body: '로그 보존, 증거 복사, 설정 변경, 배포 작업에서는 출발 대상·결과 대상·무결성 확인값·작업 시각을 함께 기록합니다. 파일 변경은 작업 자체가 증거가 될 수 있습니다.' },
    { type: 'practice-link', title: '다음 활동', body: '읽기 전용 가상 셸에서는 파일 변경 대신 경로와 파일명을 안전하게 해석하는 연습을 합니다.', labIds: ['w1-command-ctf'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.coreutils, sources.bash] },
    { type: 'summary', title: '핵심 정리', bullets: ['파일 조작 명령은 현재 위치, 출발 대상, 도착 대상, 옵션을 함께 읽습니다.', '따옴표와 `--`는 파일명을 안전하게 인자로 전달하는 도구입니다.', '재귀 옵션은 영향 범위를 넓히므로 교육용 범위와 대상 목록을 먼저 확인합니다.'] },
  ],
  'w1-permission': [
    { type: 'question', body: '파일과 디렉터리의 `rwx`는 각각 어떤 행동을 허용하며, 소유권은 무엇을 바꿀까?' },
    { type: 'explanation', title: '권한은 대상과 주체를 함께 읽습니다', paragraphs: ['`ls -l`의 권한 문자열은 파일 유형 뒤에 소유자(user), 그룹(group), 기타 사용자(other)의 `rwx` 세 묶음으로 이어집니다. 파일에서 `r`은 내용 읽기, `w`는 내용 변경, `x`는 실행과 관련됩니다.', '디렉터리에서는 의미가 다릅니다. `r`은 이름 목록 보기, `w`는 항목 생성·삭제·이름 변경, `x`는 경로 통과와 하위 항목 접근에 관련됩니다. 목록은 보여도 디렉터리 `x`가 없으면 하위 경로에 들어갈 수 없을 수 있습니다.'] },
    { type: 'command-guide', title: '소유권과 권한을 확인·변경하는 명령', intro: '권한 변경은 서비스 동작과 다른 사용자의 접근에 영향을 줍니다. 승인된 소유자와 교육용 파일에서만 최소 권한 원칙으로 적용합니다.', commands: [
      { syntax: 'ls -l [파일 또는 디렉터리...]', purpose: '권한 문자열, 소유자, 그룹, 크기, 수정 시각을 확인합니다.', options: [{ flag: '-d', description: '디렉터리 자체의 정보를 보고 내부 목록은 펼치지 않습니다.' }, { flag: '-h', description: '`-l`과 함께 사용할 때 크기를 읽기 쉬운 단위로 표시합니다.' }] },
      { syntax: 'stat [옵션] 파일...', purpose: '권한, 소유자, 크기, 시간 등 자세한 메타데이터를 확인합니다.', options: [{ flag: '-c 형식', description: '원하는 필드만 지정한 형식으로 출력합니다. 형식 문자는 `man stat`에서 확인합니다.' }, { flag: '-L', description: '심볼릭 링크가 가리키는 대상을 확인합니다.' }] },
      { syntax: 'chmod [옵션] MODE 파일...', purpose: '파일 또는 디렉터리의 권한 비트를 바꿉니다.', options: [{ flag: 'u, g, o, a', description: '각각 소유자, 그룹, 기타, 모두를 뜻하는 기호 모드의 주체입니다.' }, { flag: '+, -, =', description: '권한을 추가, 제거, 정확히 지정합니다. 예: `chmod g-w report.txt`.' }, { flag: 'r, w, x', description: '읽기, 쓰기, 실행 권한을 뜻합니다.' }, { flag: '640', description: '숫자 모드입니다. 소유자 6(rw), 그룹 4(r), 기타 0(-)처럼 각 주체별 합으로 읽습니다.' }, { flag: '-R', description: '하위 항목까지 재귀 적용합니다. 영향이 크므로 대상 트리를 확인한 뒤에만 사용합니다.' }] },
      { syntax: 'chown [옵션] 사용자[:그룹] 파일...', purpose: '소유 사용자와 선택적으로 그룹을 바꿉니다.', options: [{ flag: '사용자:그룹', description: '소유자와 그룹을 함께 지정합니다.' }, { flag: '-R', description: '하위 항목까지 재귀 변경합니다. 서비스 계정과 파일 범위를 먼저 확인합니다.' }] },
      { syntax: 'chgrp [옵션] 그룹 파일...', purpose: '그룹만 바꿉니다.', options: [{ flag: '-R', description: '하위 항목까지 재귀 변경합니다. 다른 팀·서비스의 접근에 영향을 줄 수 있습니다.' }] },
      { syntax: 'umask [MODE]', purpose: '새 파일과 디렉터리를 만들 때 기본 권한에서 제거할 비트를 확인하거나 설정합니다.', options: [{ flag: 'umask', description: '현재 셸의 마스크 값을 표시합니다.' }, { flag: 'umask 027', description: '예시로 그룹의 쓰기와 기타 사용자의 모든 권한을 기본값에서 제거합니다. 조직 정책에 맞는 값을 사용합니다.' }] },
    ] },
    { type: 'terminal', title: '권한 문자열을 읽는 예시', command: '$ ls -ld reports reports/incident.txt\ndrwxr-x--- 2 analyst security 4096 Jul 11 10:30 reports\n-rw-r----- 1 analyst security  820 Jul 11 10:35 reports/incident.txt\n$ stat reports/incident.txt', output: 'Access: (0640/-rw-r-----)  Uid: ( 1001/ analyst)   Gid: ( 2001/ security)', annotations: ['첫 글자 `d`는 디렉터리, `-`는 일반 파일을 뜻합니다.', '`640`은 소유자 `rw`, 그룹 `r`, 기타 `---`으로 읽습니다.', '디렉터리의 `x`는 경로 통과와 하위 항목 접근을 판단할 때 함께 봅니다.'] },
    { type: 'comparison', title: '파일과 디렉터리의 `rwx`', columns: ['권한', '일반 파일', '디렉터리'], rows: [['r', '내용 읽기', '이름 목록 보기'], ['w', '내용 변경', '항목 생성·삭제·이름 변경'], ['x', '실행 가능 여부', '경로 통과·하위 항목 접근']] },
    { type: 'case', title: '최소 권한으로 변경하기', body: '권한 오류가 나도 바로 넓은 권한을 부여하지 않습니다. 누가 어떤 작업을 해야 하는지, 파일인지 디렉터리인지, 현재 소유자·그룹이 무엇인지 확인한 뒤 필요한 권한만 추가하거나 조정합니다.', facts: ['`chmod`는 권한, `chown`과 `chgrp`는 소유 주체를 바꿉니다.', '파일의 `x`와 디렉터리의 `x`는 의미가 다릅니다.', '재귀 변경은 하위 서비스 파일까지 영향을 줄 수 있습니다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`chmod 777`이면 권한 문제가 해결된다 → 과도한 권한은 다른 사용자에게 불필요한 읽기·쓰기·실행 권한을 줄 수 있습니다.', '파일을 읽을 수 있으면 상위 디렉터리도 항상 들어갈 수 있다 → 상위 디렉터리의 `x` 권한이 없으면 경로를 통과하지 못할 수 있습니다.'] },
    answer('w1-permission-check-01', '`640` 권한의 그룹이 할 수 있는 일은?', '정답: 읽기만. 숫자 모드의 가운데 4는 그룹의 읽기 권한입니다.', ['읽기만', '읽기와 쓰기', '실행만'], 0, '가운데 숫자 4는 그룹의 읽기 권한입니다.'),
    answer('w1-permission-check-02', '권한 오류가 났을 때 최소 권한 관점에서 확인할 순서를 적어 보세요.', '예시 답: 대상이 파일인지 디렉터리인지 확인하고, `ls -ld` 또는 `stat`으로 현재 소유자·그룹·권한을 읽습니다. 필요한 사용자와 행동(읽기, 쓰기, 경로 통과)을 정한 뒤 그 권한만 조정하고 결과를 재확인합니다.'),
    { type: 'work-context', title: '보안 업무에서의 사용', body: '시스템 보안, 클라우드 IAM, 사고 대응에서는 계정·그룹·권한·상위 경로 권한을 함께 봅니다. 권한 변경은 이유, 승인, 적용 범위, 재확인 결과를 남겨야 합니다.' },
    { type: 'practice-link', title: '다음 활동', body: '명령어 CTF에서 `ls -al`, `file`, `find`, `grep`을 조합해 파일을 찾은 뒤 권한 관찰 습관을 기록합니다.', labIds: ['w1-command-ctf'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.coreutils] },
    { type: 'summary', title: '핵심 정리', bullets: ['권한은 사용자·그룹·기타 주체와 파일·디렉터리 대상을 함께 읽습니다.', '`chmod`는 권한, `chown`·`chgrp`는 소유 주체를 바꿉니다.', '권한 오류는 과도한 권한 부여보다 필요한 행동과 최소 범위를 먼저 확인합니다.'] },
  ],
  'w1-ssh': [
    { type: 'question', body: '원격 서버에 처음 연결할 때 서버 신원 확인과 사용자 인증은 왜 분리되어 있을까?' },
    { type: 'explanation', title: 'SSH는 원격 셸 접속을 보호하는 프로토콜입니다', paragraphs: ['SSH 클라이언트는 사용자명, 호스트, 포트를 바탕으로 원격 서버에 연결합니다. 연결 초기에 서버는 호스트 키로 자신의 신원을 제시하고, 클라이언트는 이미 알고 있는 값 또는 공식 채널에서 확인한 지문과 비교합니다.', '호스트 키 확인 뒤에는 비밀번호나 공개키 같은 방식으로 사용자를 인증합니다. 서버 신원 확인과 사용자 인증은 다른 단계입니다. 처음 보는 서버의 지문을 무심코 승인하지 말고, 교육 플랫폼이 제공한 공식 값과 비교합니다.'] },
    { type: 'timeline', title: '원격 셸 접속 순서', items: ['사용자명·호스트·포트 확인', 'TCP 연결 시작', '서버 호스트 키 지문 확인', '사용자 인증', '원격 셸 명령 실행', '`exit` 또는 Ctrl+D로 연결 종료'] },
    { type: 'terminal', title: 'SSH 명령의 기본형', command: '$ ssh -p 2220 bandit0@bandit.labs.overthewire.org\nThe authenticity of host \'bandit.labs.overthewire.org\' can\'t be established.\nED25519 key fingerprint is SHA256:[공식 문서와 비교할 값].\nAre you sure you want to continue connecting (yes/no/[fingerprint])?', output: '교육 플랫폼의 공식 안내에서 지문과 접속 정보를 확인한 뒤에만 진행합니다.', annotations: ['`-p`는 기본 포트 22가 아닌 포트를 지정합니다.', '`사용자@호스트`는 어느 계정으로 어느 서버에 접속할지 나타냅니다.', '화면에 보이는 지문은 공식 안내의 값과 비교합니다.'] },
    { type: 'command-guide', title: 'SSH 접속에서 자주 보는 옵션', intro: '외부 연결은 제공 기관이 명시한 교육 계정과 대상에서만 사용합니다.', commands: [
      { syntax: 'ssh [옵션] 사용자@호스트', purpose: '암호화된 원격 셸에 접속합니다.', options: [{ flag: '-p 포트', description: '접속할 TCP 포트를 지정합니다.' }, { flag: '-i 키파일', description: '사용할 개인키 파일을 지정합니다. 개인키는 공유하거나 제출하지 않습니다.' }, { flag: '-v', description: '연결 진단 정보를 늘립니다. 기록 전에는 사용자명·경로·식별 정보를 검토합니다.' }, { flag: 'exit / Ctrl+D', description: '원격 셸을 종료하고 로컬 셸로 돌아옵니다.' }] },
    ] },
    { type: 'comparison', title: '서버 확인과 사용자 인증', columns: ['단계', '확인하는 대상', '실패 시 의미'], rows: [['호스트 키 확인', '연결한 서버의 신원', '잘못된 서버·중간자 위험 가능성 확인'], ['사용자 인증', '접속하려는 사용자 계정', '비밀번호·키·계정 상태 확인'], ['세션 종료', '원격 셸 연결', '로컬 셸로 돌아왔는지 확인']] },
    { type: 'case', title: '교육 서버 접속 기록', body: 'Bandit 같은 공식 워게임을 풀 때는 제공된 호스트·포트·계정만 사용하고, 접속에 쓰인 비밀번호와 다음 레벨 값은 제출 기록에서 마스킹합니다. 막혔을 때는 임의 대상에 같은 명령을 시도하지 않습니다.', facts: ['호스트 키 확인과 사용자 인증은 서로 다른 단계입니다.', '공식 서버 정보는 교육 플랫폼 안내에서 확인합니다.', '비밀번호·개인키·토큰은 화면과 기록에서 마스킹합니다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['호스트 키 경고는 매번 무시해도 된다 → 서버 키가 바뀐 이유를 공식 안내로 확인하지 않으면 다른 서버에 연결될 위험이 있습니다.', '비밀번호를 입력하면 서버 신원도 확인된 것이다 → 비밀번호 인증은 사용자 인증이고 서버 신원은 호스트 키로 별도 확인합니다.'] },
    answer('w1-ssh-check-01', 'SSH 최초 접속에서 호스트 키를 확인하는 목적은?', '정답: 연결한 서버의 신원을 확인하는 것입니다.', ['인터넷 속도 측정', '연결한 서버의 신원 확인', '사용자 파일 권한 변경'], 1, '호스트 키는 서버 신원 확인에 사용됩니다.'),
    answer('w1-ssh-check-02', '처음 보는 SSH 호스트 키 경고가 나오면 무엇을 확인할까?', '예시 답: 교육 플랫폼 또는 조직의 공식 안내에 있는 호스트명·포트·키 지문과 화면의 지문을 비교합니다. 일치하지 않거나 확인할 수 없으면 승인하지 않고 담당자 또는 공식 문서를 확인합니다.'),
    { type: 'work-context', title: '보안 업무에서의 사용', body: '운영과 사고 대응에서는 접속 호스트, 계정, 시간, 목적, 승인 범위를 기록합니다. 키 기반 인증을 쓰더라도 개인키와 세션에서 다루는 비밀정보는 별도 보호 대상입니다.' },
    { type: 'practice-link', title: '다음 활동', body: '가상 실습을 마친 뒤 공식 OverTheWire Bandit 0~10에서 허가된 교육 계정으로만 SSH 흐름을 적용합니다.', labIds: ['w1-bandit'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.openssh] },
    { type: 'summary', title: '핵심 정리', bullets: ['SSH는 서버 호스트 키 확인 뒤 사용자 인증을 수행합니다.', '호스트 키 지문은 공식 안내의 값과 비교합니다.', '외부 접속은 명시된 교육 대상과 계정 범위에서만 수행합니다.'] },
  ],
})
