const sources = {
  bash: { label: 'GNU Bash Reference Manual', url: 'https://www.gnu.org/software/bash/manual/', note: '셸의 명령 해석, 인용, 확장 규칙을 확인합니다.' },
  coreutils: { label: 'GNU Coreutils Manual', url: 'https://www.gnu.org/software/coreutils/manual/html_node/', note: 'ls, pwd, cat, file 관련 명령의 공식 설명입니다.' },
  findutils: { label: 'GNU Findutils Manual', url: 'https://www.gnu.org/software/findutils/manual/', note: 'find와 grep을 포함한 검색 도구의 공식 매뉴얼입니다.' },
  fhs: { label: 'Filesystem Hierarchy Standard 3.0', url: 'https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html', note: 'Linux 디렉터리 구조의 목적을 확인합니다.' },
  openssh: { label: 'OpenSSH ssh(1) Manual', url: 'https://man.openbsd.org/ssh', note: 'SSH 클라이언트의 공식 매뉴얼입니다.' },
}

export const week1LessonBlocks = Object.freeze({
  'w1-shell': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '터미널에 입력한 `ls -l`은 누가 해석하고, 누가 실제 디렉터리를 읽으며, 결과는 어디에 표시될까?' },
    { type: 'explanation', title: '터미널, 셸, 커널의 역할', paragraphs: ['터미널은 키보드 입력과 문자 출력을 보여 주는 인터페이스입니다. 셸은 입력한 명령줄을 읽어 명령 이름·옵션·인자를 해석하고 프로그램을 실행합니다. 커널은 파일, 프로세스, 네트워크 같은 운영체제 자원에 접근하는 요청을 처리합니다.', '따라서 터미널에서 명령이 실패했을 때 화면 자체가 고장 났다고 결론내리지 않습니다. 현재 디렉터리, 입력한 인자, 셸이 해석한 명령, 실행한 프로그램의 종료 상태를 순서대로 확인합니다.'] },
    { type: 'diagram', title: '명령 한 줄이 처리되는 흐름', nodes: ['터미널 입력', '셸: 명령·옵션·인자 해석', '프로그램 실행', '커널: 파일·프로세스 요청', '표준 출력·오류 출력', '터미널 표시'] },
    { type: 'terminal', title: '명령 형식과 종료 상태', command: '$ pwd\n/home/student\n$ ls -l missing.txt\nls: cannot access \'missing.txt\': No such file or directory\n$ echo $?', output: '2', annotations: ['`pwd`는 현재 작업 디렉터리를 표준 출력으로 보냅니다.', '`ls`의 오류 메시지는 표준 오류로 나올 수 있습니다.', '종료 상태 0은 일반적으로 성공이며 0이 아닌 값은 오류 또는 다른 상태를 뜻합니다. 정확한 의미는 명령마다 확인합니다.'] },
    { type: 'comparison', title: '명령줄 구성 요소', columns: ['부분', '예시', '확인할 점'], rows: [['명령', '`ls`', '어떤 프로그램 또는 셸 내장 명령인가?'], ['옵션', '`-l`, `-a`, `-h`', '출력 형식이나 동작을 바꾸는가?'], ['인자', '`/var/log`', '명령이 다룰 대상은 무엇인가?'], ['현재 디렉터리', '`/home/student`', '상대 경로 해석의 기준은 어디인가?']] },
    { type: 'case', title: 'CodeCureLAB 운영 확인', body: '운영자가 오류 로그를 열기 전에 `pwd`, 대상 경로, `file`, 권한을 확인하면 “파일이 없다”, “디렉터리다”, “권한이 없다”를 구분할 수 있습니다. 같은 `cat access.log`도 현재 위치가 다르면 다른 결과를 냅니다.', facts: ['입력 문자열은 같아도 현재 위치와 사용자 권한이 결과를 바꾼다.', '오류 메시지와 종료 상태는 실패 원인을 좁히는 관찰값이다.', '명령을 실행한 사용자·호스트·경로는 조사 기록의 일부다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['터미널과 셸은 같은 것이다 → 터미널은 입출력 창이고 셸은 명령줄을 해석하는 프로그램이다.', '종료 상태가 0이 아니면 항상 보안 문제다 → 우선 명령의 정상 오류 조건과 입력·경로를 확인한다.'] },
    { type: 'checkpoint', id: 'w1-shell-check-01', title: '역할 고르기', prompt: '상대 경로를 현재 디렉터리와 결합해 프로그램에 전달하는 역할에 가장 가까운 것은?', options: ['셸', '모니터', '파일 확장자'], answer: 0, explanation: '셸은 명령줄을 해석해 프로그램 실행에 필요한 인자와 환경을 구성합니다.' },
    { type: 'checkpoint', id: 'w1-shell-check-02', title: '실패 기록', prompt: '`cat report.txt`가 실패했을 때 기록할 최소 사실 세 가지를 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '관제, 포렌식, 시스템 보안에서는 명령 자체보다 실행 계정, 호스트, 현재 위치, 입력, 출력, 시각을 같이 남겨야 다른 사람이 결과를 재검토할 수 있습니다.' },
    { type: 'practice-link', title: '다음 활동', body: '가상 셸에서 `pwd`와 `ls`의 결과가 어떤 맥락을 말해 주는지 확인합니다.', labIds: ['w1-treasure'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.bash, sources.coreutils] },
    { type: 'summary', title: '핵심 정리', bullets: ['터미널은 입출력, 셸은 명령 해석, 커널은 자원 요청 처리라는 역할을 가진다.', '명령은 명령·옵션·인자와 실행 맥락으로 읽는다.', '오류 메시지와 종료 상태는 결론이 아니라 다음 확인의 시작점이다.'] },
  ],
  'w1-filesystem': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '같은 `notes/todo.txt`가 실행 위치에 따라 왜 다른 파일을 가리킬 수 있을까?' },
    { type: 'explanation', title: '경로는 파일의 성격이 아니라 찾는 방법이다', paragraphs: ['Linux 파일 시스템은 `/`에서 시작하는 디렉터리 트리로 보입니다. `/home`은 사용자 홈 디렉터리에, `/etc`는 시스템 설정에, `/var`는 로그처럼 변하는 데이터에 자주 사용됩니다. 이름과 관례는 이해를 돕지만 실제 시스템마다 내용과 권한은 다를 수 있습니다.', '절대 경로는 `/`부터 시작해 어디서 실행해도 같은 위치를 가리킵니다. 상대 경로는 현재 작업 디렉터리(CWD)에서 시작합니다. `.`은 현재 디렉터리, `..`은 상위 디렉터리, `~`는 현재 사용자의 홈 디렉터리로 확장됩니다.'] },
    { type: 'diagram', title: '상대 경로 해석', nodes: ['현재 위치 `/home/student`', '입력 `notes/todo.txt`', '경로 결합 `/home/student/notes/todo.txt`', '대상 존재·권한 확인', '파일 내용 또는 오류 출력'] },
    { type: 'terminal', title: '절대 경로와 상대 경로', command: '$ pwd\n/home/student\n$ cat notes/todo.txt\nreview access log\n$ cd /tmp\n$ cat notes/todo.txt', output: "cat: notes/todo.txt: No such file or directory", annotations: ['같은 상대 경로 문자열도 CWD가 달라지면 다른 위치를 뜻합니다.', '절대 경로 `/home/student/notes/todo.txt`는 두 위치에서 같은 파일을 가리킵니다.'] },
    { type: 'comparison', title: '경로 표기 비교', columns: ['표기', '시작점', '장점·주의점'], rows: [['`/etc/codecurelab/app.conf`', '루트 `/`', '재현성이 높지만 시스템마다 존재 여부가 다를 수 있다.'], ['`logs/access.log`', '현재 디렉터리', '짧지만 실행 위치를 함께 기록해야 한다.'], ['`./run.sh`', '현재 디렉터리', '현재 위치의 파일임을 명시한다.'], ['`../backup`', '상위 디렉터리', '구조를 이해해야 하며 이동 뒤 의미가 달라진다.']] },
    { type: 'case', title: '숨김 파일과 파일 형식', body: 'CodeCureLAB 설정 디렉터리에 `.env.example`처럼 점으로 시작하는 파일이 있어도 점은 일반 `ls`에서 숨기는 이름 규칙일 뿐 보호 통제가 아닙니다. 파일의 확장자도 내용의 보증이 아니므로 `file`로 형식을 먼저 확인합니다.', facts: ['숨김 표기는 접근 제어가 아니다.', '파일명 확장자는 사람이 붙인 이름의 일부다.', '내용·권한·소유자·경로는 서로 다른 관찰 항목이다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`/`는 현재 폴더다 → `/`는 파일 시스템의 루트이고, 현재 폴더는 `pwd`로 확인한다.', '점으로 시작하면 안전한 비밀 파일이다 → 목록 표시 방식일 뿐 권한이나 암호화를 제공하지 않는다.'] },
    { type: 'checkpoint', id: 'w1-filesystem-check-01', title: '경로 계산', prompt: '현재 위치가 `/var/log`일 때 `../tmp/report.txt`는 어느 절대 경로를 뜻하는가?', options: ['/var/tmp/report.txt', '/tmp/report.txt', '/var/log/tmp/report.txt'], answer: 0, explanation: '`..`은 `/var/log`의 상위인 `/var`을 뜻하므로 `/var/tmp/report.txt`가 됩니다.' },
    { type: 'checkpoint', id: 'w1-filesystem-check-02', title: '관찰 계획', prompt: '처음 보는 `backup.bin`을 실행하거나 열기 전에 경로·형식·권한 관점에서 무엇을 확인할지 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '사고 분석과 취약점 재현 기록에서는 기준 디렉터리와 절대 경로를 함께 남깁니다. 경로가 빠지면 같은 명령도 다른 파일을 대상으로 다시 실행될 수 있습니다.' },
    { type: 'practice-link', title: '다음 활동', body: '경로 오류를 고치고 가상 파일 시스템에서 실제 경로를 찾아봅니다.', labIds: ['w1-path', 'w1-treasure'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.fhs, sources.coreutils] },
    { type: 'summary', title: '핵심 정리', bullets: ['절대 경로는 `/`, 상대 경로는 현재 작업 디렉터리에서 시작한다.', '`.`·`..`·`~`는 경로 해석의 기준을 바꾼다.', '숨김 표기와 확장자는 접근 통제나 실제 파일 형식을 보장하지 않는다.'] },
  ],
  'w1-navigation': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '파일을 찾는 `find`와 파일 안의 줄을 찾는 `grep`은 어떤 순서로 함께 쓰면 좋을까?' },
    { type: 'explanation', title: '명령을 외우기보다 확인 질문에 연결하기', paragraphs: ['탐색의 첫 질문은 “내가 어디에 있고 무엇이 있는가”입니다. `pwd`는 현재 위치를, `ls [옵션] [파일 또는 디렉터리]`는 목록과 메타데이터를 보여 줍니다. 그 뒤에 경로를 이동하는 `cd [디렉터리]`, 파일 형식을 보는 `file [파일]`, 내용을 읽는 명령을 고릅니다.', '검색은 두 단계로 나누면 실수가 줄어듭니다. `find [시작 경로] [조건]`은 파일 시스템 항목의 경로를 찾고, `grep [옵션] 패턴 파일`은 텍스트 안의 줄을 찾습니다. 후보 파일을 먼저 좁힌 뒤 그 내용을 검색하면 결과의 의미를 설명하기 쉽습니다.'] },
    { type: 'comparison', title: '자주 쓰는 읽기·탐색 명령', columns: ['명령 형식', '무엇을 확인하는가', '자주 쓰는 옵션·주의점'], rows: [
      ['`pwd`', '현재 작업 디렉터리', '인자 없이 실행한다. 상대 경로 오류의 첫 확인이다.'],
      ['`ls [옵션] [디렉터리]`', '이름·메타데이터 목록', '`-a` 숨김 이름 포함, `-l` 상세, `-h` 사람이 읽기 쉬운 크기. `-alh`는 함께 쓸 수 있다.'],
      ['`cd [디렉터리]`', '현재 작업 디렉터리 변경', '인자가 없으면 보통 홈으로 이동한다. 이동 뒤 `pwd`로 확인한다.'],
      ['`file [파일]`', '내용으로 추정한 형식', '확장자가 아닌 매직·내용을 본다. 안전성 판정 도구는 아니다.'],
      ['`find [경로] -type f -name 패턴`', '경로 조건에 맞는 파일', '시작 경로와 파일·디렉터리 조건을 명시한다. 넓은 `/`부터 시작하지 않는다.'],
      ['`grep [-in] 패턴 파일`', '텍스트 줄의 패턴', '`-i` 대소문자 무시, `-n` 줄 번호. 바이너리·큰 파일은 먼저 형식과 범위를 확인한다.'],
      ['`head [-n N] 파일` / `tail [-n N] 파일`', '파일 앞·뒤 일부', '긴 로그 전체 대신 필요한 범위를 관찰한다.'],
      ['`man 명령` / `명령 --help`', '공식 사용법과 옵션', 'SYNOPSIS에서 인자 형식을 읽고 OPTIONS에서 필요한 것만 고른다.'],
    ] },
    { type: 'terminal', title: '경로를 찾고 줄을 찾는 순서', command: '$ find /var/log/codecurelab -type f -name "*.log"\n/var/log/codecurelab/access.log\n/var/log/codecurelab/error.log\n$ grep -n "validation failed" /var/log/codecurelab/error.log', output: '18:request_id=req-demo-42 upload validation failed: unsupported media type', annotations: ['`find`의 결과는 파일 경로 후보입니다.', '`grep -n`의 결과는 해당 파일 안에서 패턴이 있는 줄과 줄 번호입니다.', '출력 한 줄만으로 원인을 단정하지 말고 앞뒤 로그와 요청 조건을 확인합니다.'] },
    { type: 'code', title: '공백·하이픈 이름을 안전하게 다루기', language: 'bash', code: "cat 'weekly report.txt'\ncat -- -note\nls -l -- -note", annotations: ['따옴표는 공백이 있는 이름을 하나의 인자로 유지합니다.', '`--`는 이후 값을 옵션이 아니라 파일명으로 해석하게 합니다.', '와일드카드 `*`는 셸이 실행 전에 여러 이름으로 확장할 수 있으므로 대상 목록을 먼저 확인합니다.'] },
    { type: 'case', title: 'Bandit 전에 기록할 조사 순서', body: '어떤 파일에 비밀 값이 있을 수 있다는 과제에서 바로 `cat`을 반복하기보다 현재 위치, 목록, 숨김 여부, 형식, 후보 경로, 텍스트 패턴 순서로 관찰합니다. 이 순서는 운영 로그와 포렌식 자료에서도 같은 방식으로 적용됩니다.', facts: ['`ls -al`은 숨김 이름과 상세 정보를 함께 본다.', '`file`은 텍스트인지 바이너리인지 구분하는 데 도움을 준다.', '`find`와 `grep`은 각각 경로와 내용이라는 다른 질문에 답한다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`grep`이 파일을 찾아 준다 → `grep`은 지정한 파일의 내용 줄을 검색한다. 경로 후보는 `find` 등으로 먼저 찾는다.', '`ls -al`이 모든 권한 문제를 해결한다 → 목록을 볼 수 있는지와 파일을 읽거나 디렉터리에 들어갈 수 있는지는 다르다.'] },
    { type: 'checkpoint', id: 'w1-navigation-check-01', title: '도구 고르기', prompt: '하위 디렉터리를 포함해 `.log` 파일의 경로를 찾는 가장 알맞은 시작 명령은?', options: ['`find . -type f -name "*.log"`', '`grep -n ".log" .`', '`cat *.log`'], answer: 0, explanation: '`find`는 파일 시스템의 경로와 조건을 다룹니다. `grep`은 파일 내용을 검색합니다.' },
    { type: 'checkpoint', id: 'w1-navigation-check-02', title: '명령 계획', prompt: '숨김 파일일 수 있고, 하위 경로 어딘가의 로그에 `security_flag`라는 텍스트가 있다고 할 때 관찰 순서를 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '로그 triage와 포렌식에서는 전체 디스크나 모든 로그를 무작정 읽지 않습니다. 시작 경로, 시간 범위, 파일 형식, 패턴, 줄 번호를 기록해 다른 분석가가 같은 후보를 재확인할 수 있게 합니다.' },
    { type: 'practice-link', title: '다음 활동', body: '가상 셸에서 세 개의 낮은 난이도 조사 과제를 순서대로 풉니다.', labIds: ['w1-treasure'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.coreutils, sources.findutils] },
    { type: 'summary', title: '핵심 정리', bullets: ['`pwd`와 `ls`로 현재 맥락을 먼저 확인한다.', '`find`는 경로, `grep`은 텍스트 줄을 검색한다.', '옵션은 SYNOPSIS와 공식 매뉴얼에서 목적에 맞게 확인한다.'] },
  ],
  'w1-fileops': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '파일을 복사·이동·삭제하는 명령에서 “대상”을 확인하지 않으면 어떤 사고가 생길 수 있을까?' },
    { type: 'explanation', title: '변경 명령은 되돌리기 전에 범위를 읽는다', paragraphs: ['`touch`, `mkdir`, `cp`, `mv`, `rm`, `rmdir`는 파일 시스템을 바꿉니다. 특히 `rm`과 재귀 옵션은 하위 항목에 영향을 줄 수 있으므로 교육용 읽기 전용 셸 밖에서 예시를 그대로 실행하지 않습니다. 먼저 현재 위치와 대상 경로를 출력으로 확인하고, 필요한 최소 범위만 변경합니다.', '셸은 따옴표, 이스케이프, 글로빙을 해석할 수 있습니다. 공백이 있는 이름은 인자가 둘로 나뉠 수 있고, `*`는 여러 파일명으로 확장될 수 있습니다. 명령을 실행하기 전 확장될 후보를 `printf`나 `ls`로 확인하는 습관이 안전합니다.'] },
    { type: 'terminal', title: '복사 전과 후의 대상 확인', command: "$ pwd\n/home/student\n$ ls -ld drafts backup\ndrwxr-x--- 2 student student 4096 drafts\ndrwxr-x--- 2 student student 4096 backup\n$ cp -- 'drafts/weekly report.txt' backup/\n$ ls -l backup/", output: '-rw-r----- 1 student student 312 Jul 12 10:30 weekly report.txt', annotations: ['복사 전에는 출발지·도착지가 디렉터리인지 확인합니다.', '`--`와 따옴표는 옵션·공백 이름 해석을 명확하게 합니다.', '복사 후에는 결과 경로와 메타데이터를 다시 관찰합니다.'] },
    { type: 'comparison', title: '파일 조작 명령의 범위', columns: ['명령', '기본 행동', '실행 전 질문'], rows: [['`mkdir -p path`', '필요한 상위 경로와 디렉터리 생성', '이미 있는 경로와 권한은 어떤가?'], ['`cp source destination`', '파일·디렉터리를 복사', '대상 이름이 덮어써지는가?'], ['`mv source destination`', '이동 또는 이름 변경', '다른 파일 시스템·기존 이름에 영향이 있는가?'], ['`rm file`', '파일 제거', '정말 이 경로 하나인가? 재귀·force 옵션이 필요한가?'], ['`rmdir dir`', '빈 디렉터리 제거', '비어 있지 않다면 왜 비어 있지 않은가?']] },
    { type: 'code', title: '셸 확장을 확인하는 습관', language: 'bash', code: "printf '%s\\n' logs/*.log\nprintf '%s\\n' -- *\n# 실제 변경 전 후보 이름을 먼저 출력한다", annotations: ['글로빙은 셸이 실행 전에 확장합니다.', '매칭 항목이 없을 때의 동작은 셸 옵션에 따라 달라질 수 있습니다.', '교육 실습에서는 실제 삭제 명령 대신 대상 목록과 영향 범위를 설명합니다.'] },
    { type: 'case', title: '업로드 임시 파일 정리', body: 'CodeCureLAB의 업로드 처리에서 임시 디렉터리를 정리하는 작업은 파일 이름만 믿고 삭제하지 않습니다. 서비스가 만든 경로인지, 보관 기간이 지났는지, 다른 작업이 사용 중인지, 삭제 후 검증할 로그가 있는지를 함께 확인합니다.', facts: ['자동화 작업도 명시적 시작 경로와 파일 조건을 가져야 한다.', '삭제 대상과 보관 대상은 정책·시간·소유자를 기준으로 구분한다.', '변경 전후 결과와 실패 조건을 로그에 남긴다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['`rm -rf`는 문제가 생기면 복구하면 된다 → 삭제 영향과 복구 가능성은 환경마다 다르며 사전 범위 확인이 우선이다.', '따옴표는 보기 좋게 쓰는 장식이다 → 공백·특수문자가 있는 인자 경계를 셸에 명시한다.'] },
    { type: 'checkpoint', id: 'w1-fileops-check-01', title: '인자 해석', prompt: '파일 이름이 `-report.txt`일 때 옵션이 아니라 파일로 읽게 하는 형식은?', options: ['`cat -- -report.txt`', '`cat -report.txt`', '`cat /- report.txt`'], answer: 0, explanation: '`--` 뒤의 값은 옵션 해석이 끝난 뒤의 인자로 처리합니다.' },
    { type: 'checkpoint', id: 'w1-fileops-check-02', title: '변경 계획', prompt: '임시 파일 정리 작업을 실행하기 전 확인할 경로·조건·검증 항목을 적어 보세요.', mode: 'short-answer' },
    { type: 'warning', title: '안전 범위', body: '이 과정의 가상 셸은 읽기 전용입니다. 실제 운영 환경이나 개인 파일에 파괴적인 명령을 연습하지 말고, 허가된 로컬 테스트 디렉터리에서만 별도 실습하세요.' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '사고 대응과 운영 자동화는 빠르게 바꾸는 능력보다 바꿀 대상·영향·되돌림·증적을 정확히 남기는 능력이 중요합니다. 변경 명령은 보안 통제와 운영 절차 안에서 실행됩니다.' },
    { type: 'practice-link', title: '다음 활동', body: '경로와 이름 해석을 고치는 문제로 먼저 연습합니다.', labIds: ['w1-path'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.coreutils, sources.bash] },
    { type: 'summary', title: '핵심 정리', bullets: ['변경 명령은 현재 위치·대상·기존 항목·영향 범위를 먼저 확인한다.', '따옴표와 `--`는 셸의 인자 해석을 명시한다.', '삭제와 자동화는 최소 범위·검증·되돌림 계획을 함께 가진다.'] },
  ],
  'w1-permission': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '파일의 `rwx`와 디렉터리의 `rwx`는 왜 같은 문자여도 다른 행동을 뜻할까?' },
    { type: 'explanation', title: '권한은 주체와 대상 유형을 함께 읽는다', paragraphs: ['`ls -l`의 권한 문자열 첫 글자는 파일 유형이고, 다음 아홉 글자는 소유자·그룹·기타에 대한 `rwx` 권한입니다. 파일에서 읽기는 내용 확인, 쓰기는 내용 변경, 실행은 프로그램 실행과 관련됩니다.', '디렉터리에서는 읽기가 이름 목록, 쓰기가 항목 생성·삭제, 실행이 경로 진입·탐색과 관련됩니다. 따라서 디렉터리 권한을 파일 권한처럼 해석하면 “목록은 보이는데 파일에 못 들어간다” 같은 상황을 이해하지 못할 수 있습니다. 숫자 권한 계산과 `chmod`, `umask`, 특수 권한은 Week 2에서 다룹니다.'] },
    { type: 'terminal', title: '파일과 디렉터리 권한을 나눠 읽기', command: '$ ls -ld uploads\ndrwxr-x--- 2 app uploaders 4096 uploads\n$ ls -l uploads/assignment.pdf\n-rw-r----- 1 app uploaders 2034 assignment.pdf', output: 'directory: owner rwx, group r-x, other ---\nfile:      owner rw-, group r--, other ---', annotations: ['디렉터리의 `x`는 하위 경로에 들어가기 위한 권한과 관련됩니다.', '파일의 `x`는 그 파일을 실행 가능한 프로그램으로 다루는 권한과 관련됩니다.', '권한만으로 실제 접근을 단정하지 말고 소유자·그룹·ACL·프로세스 맥락도 나중에 확인합니다.'] },
    { type: 'comparison', title: '파일과 디렉터리의 r·w·x', columns: ['권한', '일반 파일', '디렉터리'], rows: [['r', '내용 읽기', '이름 목록 읽기'], ['w', '내용 변경', '항목 생성·이름 변경·삭제에 관여'], ['x', '실행 가능한 프로그램으로 실행', '경로 진입·하위 항목 탐색에 관여']] },
    { type: 'case', title: '과제 업로드 디렉터리', body: 'CodeCureLAB 업로드 디렉터리는 서비스 계정과 업로더 그룹만 필요한 작업을 하게 해야 합니다. 모든 사용자에게 쓰기 권한을 주는 방식은 단순해 보여도 파일 교체·삭제와 감사 범위를 넓힐 수 있습니다.', facts: ['최소 권한은 필요한 사용자·그룹·행동만 허용하는 설계다.', '권한 변경은 서비스 동작, 배포 과정, 백업·운영 계정을 함께 검토한다.', '변경 뒤에는 예상한 계정에서 허용·거부가 각각 나오는지 검증한다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['디렉터리에 `r`만 있으면 파일을 모두 읽을 수 있다 → 하위 경로를 탐색하려면 보통 `x`도 필요하다.', '권한 오류는 `sudo`로 해결하면 된다 → 필요한 주체와 최소 권한을 설계하지 않으면 더 큰 권한을 넓히게 된다.'] },
    { type: 'checkpoint', id: 'w1-permission-check-01', title: '디렉터리 권한', prompt: '디렉터리의 실행(`x`) 권한과 가장 직접적으로 관련된 행동은?', options: ['하위 경로로 들어가거나 탐색하기', '파일 내용을 자동으로 암호화하기', '파일 확장자 바꾸기'], answer: 0, explanation: '디렉터리의 `x`는 경로 탐색과 진입에 관여합니다.' },
    { type: 'checkpoint', id: 'w1-permission-check-02', title: '최소 권한 설명', prompt: '교직원만 피드백 파일을 수정하고 학생은 자신의 피드백만 읽게 하려면 어떤 주체·행동을 분리해야 하는지 적어 보세요.', mode: 'short-answer' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: 'Linux 권한, 클라우드 IAM, 데이터베이스 권한, 애플리케이션 객체 인가는 모두 “누가 어떤 대상에 어떤 행동을 할 수 있는가”를 다룹니다. 표현은 달라도 최소 권한과 재검증 원칙은 연결됩니다.' },
    { type: 'practice-link', title: '다음 활동', body: 'Week 2에서 기호 권한과 숫자 권한을 계산하고 최소 권한 수정안을 비교합니다.', labIds: ['w2-permission-lab'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.coreutils, sources.fhs] },
    { type: 'summary', title: '핵심 정리', bullets: ['권한은 소유자·그룹·기타와 파일·디렉터리 유형을 함께 읽는다.', '디렉터리의 `rwx`는 파일의 `rwx`와 다른 행동을 뜻한다.', '권한 오류는 더 큰 권한이 아니라 최소 권한과 검증 조건으로 해결한다.'] },
  ],
  'w1-ssh': [
    { type: 'question', title: '이 모듈이 답할 질문', body: '원격 서버에 처음 연결할 때 비밀번호보다 먼저 호스트 키를 확인하는 이유는 무엇일까?' },
    { type: 'explanation', title: '원격 셸 연결의 두 신원', paragraphs: ['SSH는 원격 시스템에 암호화된 연결을 만들기 위한 프로토콜과 도구입니다. 접속 명령에는 보통 사용자명, 호스트, 포트가 포함됩니다. 연결 과정에서는 서버가 자신을 증명하는 호스트 키를 제시하고, 사용자는 비밀번호나 키 기반 인증으로 자신을 증명합니다.', '서버 신원 확인과 사용자 인증은 다른 문제입니다. 처음 보는 호스트 키 지문은 제공 기관이나 운영자가 안내한 공식 값과 비교해야 합니다. 예상과 다른 호스트 키 경고를 무시하면 다른 서버나 중간자 상황을 구분하지 못할 수 있습니다.'] },
    { type: 'timeline', title: 'SSH 연결 흐름', items: [{ title: '대상 확인', body: '사용자명·호스트·포트와 허가 범위를 확인한다.' }, { title: '서버 호스트 키 확인', body: '처음 접속 또는 변경 경고의 지문을 공식 채널과 비교한다.' }, { title: '사용자 인증', body: '비밀번호 또는 개인 키로 사용자 신원을 확인한다.' }, { title: '원격 셸 사용', body: '현재 호스트와 계정을 표시해 로컬·원격 맥락을 구분한다.' }, { title: '종료·기록', body: '`exit` 또는 Ctrl+D로 연결을 닫고 민감정보를 기록에서 마스킹한다.' }] },
    { type: 'terminal', title: '교육용 SSH 명령 형태', command: '$ ssh -p 2220 bandit0@bandit.labs.overthewire.org\nThe authenticity of host ... cannot be established.\nED25519 key fingerprint is SHA256:[OFFICIAL-FINGERPRINT-CHECK-REQUIRED].', output: '공식 Bandit 안내의 현재 호스트 키 지문과 일치할 때만 계속합니다.', annotations: ['이 예시는 명령 형식을 설명하기 위한 것이며 실제 접속 전에는 공식 안내를 다시 확인합니다.', '호스트 키 지문 확인은 사용자 비밀번호 입력보다 앞서는 서버 신원 확인 단계입니다.'] },
    { type: 'comparison', title: '호스트 키와 사용자 키', columns: ['항목', '무엇을 확인하는가', '보관·운영 주의점'], rows: [['호스트 키', '연결한 서버가 예상한 서버인지', '변경 경고는 무시하지 말고 공식 채널로 확인한다.'], ['사용자 개인 키', '접속자가 해당 사용자 키를 소유하는지', '개인 키는 공유·업로드·캡처하지 않고 권한·passphrase를 관리한다.'], ['비밀번호', '사용자 계정의 비밀을 아는지', '교육 플랫폼이 제공한 값도 기록·공유 시 마스킹한다.']] },
    { type: 'case', title: 'Bandit 연결 기록', body: 'Bandit을 풀 때에는 레벨 번호, 공식 호스트, 포트, 사용한 명령, 파일 관찰, 원리만 기록합니다. 다음 레벨 비밀번호나 호스트 키 값을 블로그·캡처에 그대로 올리지 않습니다.', facts: ['외부 실습은 제공 기관의 대상·계정·시간 지침만 따른다.', '로컬 프롬프트와 원격 프롬프트를 구분해 명령 실행 위치를 기록한다.', '연결이 끝나면 `exit`로 원격 셸을 종료한다.'] },
    { type: 'misconception', title: '자주 하는 혼동', items: ['호스트 키 경고는 처음 한 번만 누르면 되는 창이다 → 서버 신원을 확인하는 보안 경계이므로 예기치 않은 변경을 조사한다.', 'SSH는 비밀번호만 안전하게 보내 주는 도구다 → 서버 인증, 사용자 인증, 암호화된 채널, 원격 셸 맥락을 함께 다룬다.'] },
    { type: 'checkpoint', id: 'w1-ssh-check-01', title: '연결 순서', prompt: 'SSH에서 서버 호스트 키 확인과 사용자 인증의 관계로 알맞은 것은?', options: ['서버 신원을 먼저 확인한 뒤 사용자 인증을 진행한다.', '사용자 인증이 끝난 뒤에만 서버를 확인한다.', '둘은 같은 값을 확인한다.'], answer: 0, explanation: '호스트 키는 연결 대상 서버의 신원을, 비밀번호·개인 키는 접속 사용자의 신원을 다룹니다.' },
    { type: 'checkpoint', id: 'w1-ssh-check-02', title: '경고 대응', prompt: '예상하지 못한 호스트 키 변경 경고가 보였을 때 안전한 다음 행동을 적어 보세요.', mode: 'short-answer' },
    { type: 'warning', title: '외부 실습 범위', body: 'SSH 명령은 OverTheWire가 제공한 Bandit 호스트·계정 같은 명시된 교육 대상에서만 사용합니다. 실제 학교·회사·개인 서버에 같은 절차를 시험하지 않습니다.' },
    { type: 'work-context', title: '보안 업무에서의 사용', body: '서버 운영, 클라우드 관리, 사고 대응에서는 연결한 대상과 계정의 신원을 정확히 구분해야 합니다. 호스트 키, 권한 있는 계정, 명령 기록은 감사와 재현의 핵심 근거가 됩니다.' },
    { type: 'practice-link', title: '다음 활동', body: '먼저 연결 순서를 시뮬레이션한 뒤, 공식 Bandit 지침 범위에서만 적용합니다.', labIds: ['w1-ssh-flow', 'w1-bandit'] },
    { type: 'sources', title: '공식 참고자료', items: [sources.openssh] },
    { type: 'summary', title: '핵심 정리', bullets: ['SSH는 서버 호스트 키 확인과 사용자 인증을 구분한다.', '예상 밖 호스트 키 경고는 공식 채널로 확인한다.', '외부 실습의 계정·비밀번호·토큰은 기록에서 마스킹한다.'] },
  ],
})
