#!/usr/bin/env python3
"""Convert the audited Week 0 job-posting workbook into a compact JS data module."""

from __future__ import annotations

import json
import sys
from collections import Counter
from datetime import date, datetime
from pathlib import Path

from openpyxl import load_workbook


def serialize(value):
    if isinstance(value, (datetime, date)):
        return value.strftime("%Y-%m-%d")
    return value


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: import-week0-job-postings.py INPUT.xlsx OUTPUT.js")

    input_path = Path(sys.argv[1]).resolve()
    output_path = Path(sys.argv[2]).resolve()
    workbook = load_workbook(input_path, read_only=True, data_only=True)
    worksheet = workbook["320개 공고"]
    rows = worksheet.iter_rows(values_only=True)
    next(rows)
    next(rows)
    headers = list(next(rows))
    column = {header: index for index, header in enumerate(headers)}

    records = []
    for values in rows:
        if not values or values[column["공고 번호"]] is None:
            continue

        def read(name):
            return serialize(values[column[name]])

        records.append({
            "number": read("공고 번호"),
            "fieldNumber": read("분야 번호"),
            "field": read("분야"),
            "roleNumber": read("직무 번호"),
            "representativeRole": read("대표 직무"),
            "market": read("권역"),
            "company": read("회사"),
            "jobTitle": read("실제 공고 제목"),
            "matchLevel": read("대응 수준"),
            "careerLevel": read("경력 수준"),
            "location": read("근무지역"),
            "originalStatus": read("공고 상태"),
            "sourceType": read("소스 유형"),
            "initialCheckedDate": read("확인일"),
            "url": read("공고 URL"),
            "urlUseCount": read("전역 URL 사용 횟수"),
            "duplicateMapping": read("중복 연결"),
            "notes": read("매칭 근거·비고"),
            "finalLinkStatus": read("최종 링크 상태"),
            "operatingRecommendation": read("최종 운영 권장"),
            "verificationBasis": read("최종 검증 근거"),
            "finalVerifiedDate": read("최종 검증일"),
            "replacementTitle": read("교체 후보 제목"),
            "replacementUrl": read("교체 후보 URL"),
        })

    unique_by_url = {}
    for record in records:
        unique_by_url.setdefault(record["url"], record)

    mapping_status_counts = Counter(record["finalLinkStatus"] for record in records)
    unique_status_counts = Counter(record["finalLinkStatus"] for record in unique_by_url.values())
    summary = {
        "sourceFile": input_path.name,
        "auditDate": max(record["finalVerifiedDate"] for record in records if record["finalVerifiedDate"]),
        "mappingCount": len(records),
        "uniqueUrlCount": len(unique_by_url),
        "fieldCount": len({record["field"] for record in records}),
        "representativeRoleCount": len({(record["field"], record["representativeRole"]) for record in records}),
        "domesticCount": sum(record["market"] == "국내" for record in records),
        "internationalCount": sum(record["market"] == "해외" for record in records),
        "mappingStatusCounts": dict(mapping_status_counts),
        "uniqueStatusCounts": dict(unique_status_counts),
    }

    payload = (
        "// Generated by scripts/import-week0-job-postings.py from the user-provided audited workbook.\n"
        "// Do not hand-edit individual rows; rerun the importer when the workbook changes.\n"
        f"export const jobPostingAuditSummary = Object.freeze({json.dumps(summary, ensure_ascii=False, indent=2)})\n\n"
        f"export const jobPostingAuditRows = Object.freeze({json.dumps(records, ensure_ascii=False, indent=2)})\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(payload, encoding="utf-8")
    print(f"wrote {len(records)} mappings and {len(unique_by_url)} unique URLs to {output_path}")


if __name__ == "__main__":
    main()
