const reportGuide = {
  title: '보고서에 남길 것',
  items: [
    '영향받는 자산, 기능, URL 또는 파일을 정확히 특정한다.',
    '공격자가 어떤 권한과 사전 조건을 갖는지 적는다.',
    '재현 절차를 최소 단계로 쓰고, 각 단계의 관찰 결과를 붙인다.',
    '기대 결과와 실제 결과를 나누어 영향이 추정이 아니라는 점을 보인다.',
    '기밀성·무결성·가용성 영향을 분리하고, 안전한 수정 방향을 제안한다.',
    '허가된 실습 환경에서만 재현하고 실제 서비스의 데이터는 건드리지 않는다.',
  ],
  source: { label: 'OWASP WSTG · Security Test Data Analysis and Reporting', url: 'https://owasp.org/www-project-web-security-testing-guide/latest/2-Introduction/README' },
}

const source = (label, url) => ({ label, url })

export const concepts = {
  1: {
    title: '보안 기초와 Linux',
    summary: '운영체제와 파일 권한을 관찰하는 습관을 만들고, 명령어를 외우기보다 입력·처리·출력의 관계를 기록합니다.',
    sources: [source('OverTheWire · Bandit', 'https://overthewire.org/wargames/bandit/'), source('Linux man-pages · proc', 'https://man7.org/linux/man-pages/man5/proc.5.html'), source('Dreamhack · 보안 기초', 'https://dreamhack.io/lecture/units/dreambeginners-introduction')],
    diagram: ['사용자 입력', 'Shell 해석', '프로세스 실행', '파일·권한·출력'],
    sections: [
      { title: '핵심 개념', body: 'Linux에서 명령어는 현재 사용자의 권한과 현재 작업 디렉터리라는 맥락 안에서 실행됩니다. 같은 명령도 사용자의 UID, 파일의 소유자와 권한, 환경 변수에 따라 결과가 달라질 수 있습니다.' },
      { title: '확인 순서', bullets: ['현재 위치와 파일 목록을 확인한다.', '파일의 소유자·권한·크기·수정 시간을 비교한다.', '프로그램이 읽고 쓰는 경로와 입력이 어디서 오는지 기록한다.', '권한 상승이나 민감 정보 노출이 발생하는지 실습 환경에서만 확인한다.'] },
      { title: '방어 관점', body: '최소 권한, 명확한 파일 소유권, 비밀값의 별도 보관, 명령어 실행 시 인자 분리와 로그 기록이 핵심입니다. 명령어가 성공했다는 사실만으로 안전하다고 결론 내리지 않습니다.' },
    ],
    checklist: ['UID/GID와 권한을 적었는가?', '입력과 출력 파일을 구분했는가?', '재현에 필요한 최소 명령만 남겼는가?'],
    caseStudy: { title: '현실에서의 의미', body: '공격자는 복잡한 도구보다 먼저 노출된 파일, 잘못된 권한, 로그와 환경 설정을 살핍니다. 그래서 초반 실습의 목표는 “명령어를 많이 아는 것”이 아니라 시스템의 상태를 근거와 함께 읽는 것입니다.', source: 'https://man7.org/linux/man-pages/man5/proc.5.html' },
    warmup: { id: 'warmup-1', week: 1, title: 'LOW · Linux 상태 읽기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '제공된 Linux 실습 환경에서 현재 사용자, 작업 디렉터리, 파일 권한을 확인하고 관찰 결과를 세 줄로 기록합니다.' },
    quiz: [{ q: '파일 권한을 확인하는 이유로 가장 적절한 것은?', options: ['명령어를 빠르게 외우기 위해', '누가 어떤 파일을 읽고 쓸 수 있는지 확인하기 위해', '인터넷 속도를 측정하기 위해'], answer: 1, explanation: '권한은 파일과 디렉터리에 대한 주체별 접근 범위를 설명합니다.' }],
  },
  2: {
    title: '보안 도구 익히기',
    summary: 'Burp Suite와 개발자 도구를 이용해 브라우저가 보내는 요청과 서버의 응답을 관찰하는 법을 익힙니다.',
    sources: [source('PortSwigger · Burp Suite 시작하기', 'https://portswigger.net/burp/documentation/desktop/getting-started'), source('Chrome DevTools · Network', 'https://developer.chrome.com/docs/devtools/network/'), source('MDN · HTTP', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview')],
    diagram: ['브라우저', 'Proxy 기록', 'HTTP 요청', '서버 응답'],
    sections: [
      { title: '핵심 개념', body: '프록시는 브라우저와 서버 사이의 HTTP 메시지를 관찰하고 반복해서 재현할 수 있게 해줍니다. 요청의 메서드·경로·헤더·쿠키·본문과 응답의 상태 코드·헤더·본문을 각각 기록해야 합니다.' },
      { title: '확인 순서', bullets: ['정상 흐름을 먼저 한 번 기록한다.', '한 번에 하나의 값만 바꿔 서버의 반응 차이를 비교한다.', '응답 상태 코드뿐 아니라 본문과 보안 헤더도 확인한다.', '허가된 대상과 로컬 실습 서버에서만 재전송한다.'] },
      { title: '방어 관점', body: '서버는 브라우저가 보낸 값과 권한을 신뢰하지 않고, 서버 측에서 인증·인가·입력 검증을 다시 수행해야 합니다. 도구는 취약점을 자동으로 증명하는 판정기가 아니라 관찰을 돕는 기록 장치입니다.' },
    ],
    checklist: ['정상 요청을 기준으로 삼았는가?', '변경한 입력과 응답 차이를 짝지었는가?', '민감 정보가 캡처에 노출되지 않았는가?'],
    caseStudy: { title: '도구 사용의 기준', body: '좋은 보고서는 도구 이름보다 관찰 근거가 먼저 보입니다. 요청 한 개, 응답 한 개, 변경한 값 한 개를 기준으로 재현 가능성을 설명하세요.', source: 'https://portswigger.net/burp/documentation/desktop/getting-started' },
    warmup: { id: 'warmup-2', week: 2, title: 'LOW · 한 요청 비교하기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '실습 페이지에서 정상 요청과 한 가지 값만 바꾼 요청을 비교하고, 상태 코드·응답 길이·관련 헤더의 차이를 기록합니다.' },
    quiz: [{ q: 'Burp Proxy를 처음 사용할 때 가장 먼저 해야 할 일은?', options: ['모든 요청을 무작정 재전송한다', '정상적인 사용자 흐름을 먼저 기록한다', '서버의 데이터를 삭제한다'], answer: 1, explanation: '정상 기준선이 있어야 변경 후 반응을 비교할 수 있습니다.' }],
  },
  3: {
    title: 'HTTP와 세션 구조',
    summary: 'HTTP의 무상태 특성과 쿠키 기반 세션을 이해하고, 인증 상태가 요청 사이에서 어떻게 유지되는지 추적합니다.',
    sources: [source('MDN · HTTP Overview', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'), source('MDN · Cookies', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies'), source('RFC 9110 · HTTP Semantics', 'https://www.rfc-editor.org/rfc/rfc9110')],
    diagram: ['로그인 요청', 'Set-Cookie', '브라우저 저장', 'Cookie 포함 요청', '세션 확인'],
    sections: [
      { title: '핵심 개념', body: 'HTTP 자체는 요청 사이의 상태를 기억하지 않습니다. 서버가 세션 식별자를 발급하고 브라우저가 이후 요청에 쿠키를 포함하면서 애플리케이션 수준의 상태가 만들어집니다. 세션 ID 자체가 권한은 아니지만, 서버는 이를 인증 상태와 연결합니다.' },
      { title: '확인 순서', bullets: ['로그인 전·후의 응답과 Set-Cookie를 비교한다.', '쿠키의 Secure·HttpOnly·SameSite·Domain·Path를 확인한다.', '로그아웃·비밀번호 변경·권한 변경 뒤 세션이 폐기되는지 본다.', '다른 사용자나 다른 권한의 세션 ID가 재사용되지 않는지 확인한다.'] },
      { title: '방어 관점', body: '세션 ID는 예측 불가능해야 하고 HTTPS로만 전송하며, HttpOnly로 스크립트 접근을 막고, SameSite와 적절한 만료·폐기 정책을 적용합니다. 민감한 상태 변경에는 재인증이나 추가 검증을 고려합니다.' },
    ],
    checklist: ['요청·응답 방향을 구분했는가?', '쿠키 속성을 표로 정리했는가?', '인증과 인가를 혼동하지 않았는가?'],
    caseStudy: { title: '보고서에서 자주 빠지는 것', body: '“쿠키가 보인다”만으로 취약점이라고 보고하지 않습니다. 어떤 보호 속성이 빠졌고, 그로 인해 어떤 사용자 행동과 영향이 가능한지까지 연결해야 합니다.', source: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies' },
    warmup: { id: 'warmup-3', week: 3, title: 'LOW · 로그인 흐름 그리기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '로그인 전후의 요청·응답을 관찰하고 세션이 생성·전달·폐기되는 흐름을 그림으로 표현합니다.' },
    quiz: [{ q: 'HTTP의 무상태성을 보완해 요청 사이의 상태를 연결하는 대표 수단은?', options: ['쿠키와 서버 측 세션', 'HTML 주석', 'DNS 레코드'], answer: 0, explanation: '쿠키는 브라우저가 이후 요청에 상태 식별자를 포함하도록 도와줍니다.' }],
  },
  4: {
    title: 'XSS와 SQL Injection',
    summary: '신뢰할 수 없는 입력이 브라우저 문맥이나 SQL 문법으로 해석되는 지점을 찾고, 증거와 방어책이 있는 보고서를 작성합니다.',
    sources: [source('OWASP WSTG · Reflected XSS', 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting'), source('OWASP · XSS Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html'), source('OWASP WSTG · SQL Injection', 'https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection'), source('OWASP · SQLi Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html')],
    diagram: ['입력값', '서버 처리', '출력 문맥 / SQL 쿼리', '브라우저 / DB 해석', '영향'],
    sections: [
      { title: 'XSS에서 확인할 것', bullets: ['입력이 반사·저장·DOM source 중 어디에서 들어오는지 찾는다.', 'HTML 본문·속성·URL·JavaScript 등 출력 문맥을 구분한다.', '브라우저에서 실제로 코드 문맥으로 해석되는지 확인한다.', 'CSP가 있어도 근본 원인인 출력 인코딩·안전한 sink·sanitization을 검토한다.'] },
      { title: 'SQL Injection에서 확인할 것', bullets: ['쿼리에 들어갈 수 있는 모든 입력 지점을 목록화한다.', '정상 입력과 비정상 입력의 오류·응답 구조·시간 차이를 비교한다.', '오류 메시지나 데이터 변경을 유발하지 않는 범위에서 영향만 증명한다.', '문자열 결합 대신 매개변수화 쿼리가 사용되는지 확인한다.'] },
      { title: '방어 관점', body: 'OWASP는 XSS에 문맥별 출력 인코딩과 안전한 sink를, SQL Injection에는 Prepared Statement·안전한 저장 프로시저·allow-list 검증을 우선 권고합니다. WAF나 문자열 차단만으로 근본 원인을 해결했다고 쓰지 않습니다.' },
    ],
    checklist: ['반사 위치와 문맥을 특정했는가?', '입력·처리·출력의 흐름을 재현했는가?', '영향과 방어책이 같은 원인을 가리키는가?', '실제 서비스가 아닌 허가된 실습 범위인가?'],
    caseStudy: { title: '공개 사례로 보는 보고 품질', body: 'CISA는 Adobe Experience Manager의 Stored·Reflected·DOM XSS 사례를 공개했고, Google Bug Hunters는 CSP가 실행을 막으면 HTML Injection과 XSS를 구분해야 한다고 설명합니다. “문자열이 보인다”와 “다른 사용자의 브라우저에서 실행된다”는 서로 다른 주장입니다. SQL Injection은 CISA·FBI가 관리형 파일 전송 제품의 대규모 피해 사례를 근거로 제조사에 Prepared Statement 적용을 촉구했습니다.', source: 'https://www.cisa.gov/news-events/bulletins/sb23-360' },
    warmup: { id: 'warmup-4', week: 4, title: 'LOW · 반사 지점 찾기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '허가된 실습 페이지에서 입력값이 응답의 어느 위치로 돌아오는지 표시하고, HTML 본문·속성·스크립트 문맥 중 하나로 분류합니다.' },
    quiz: [{ q: 'XSS 보고서에서 가장 먼저 특정해야 하는 것은?', options: ['사용한 도구의 이름', '입력값이 들어간 출력 문맥과 실제 영향', '스크린샷의 해상도'], answer: 1, explanation: '반사 사실보다 어느 문맥에서 실행 가능한지와 누구에게 어떤 영향이 생기는지가 핵심입니다.' }, { q: 'SQL Injection의 우선 방어책은?', options: ['에러 메시지만 숨기기', 'Prepared Statement와 파라미터 바인딩', '입력값에 특정 문자열만 삭제하기'], answer: 1, explanation: '쿼리 구조와 사용자 데이터를 분리하는 것이 근본 방어입니다.' }],
  },
  5: {
    title: 'CSRF와 웹 취약점 복습',
    summary: '브라우저가 자동으로 보내는 인증 정보를 악용하는 요청 위조를 이해하고, 상태 변경 요청의 출처와 의도를 검증합니다.',
    sources: [source('OWASP · CSRF Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html'), source('OWASP WSTG · CSRF', 'https://owasp.org/www-project-web-security-testing-guide/v42/4-Web_Application_Security_Testing/06-Session_Management_Testing/05-Testing_for_Cross-Site_Request_Forgery'), source('MDN · Set-Cookie', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie')],
    diagram: ['외부 사이트', '브라우저 자동 쿠키', '상태 변경 요청', '서버 검증', '허용 / 거부'],
    sections: [
      { title: '핵심 개념', body: 'CSRF는 공격자가 사용자의 인증 정보를 직접 읽지 못해도, 브라우저가 쿠키를 자동으로 포함한다는 성질을 악용합니다. 따라서 상태를 변경하는 요청은 인증뿐 아니라 요청의 의도와 출처도 확인해야 합니다.' },
      { title: '확인 순서', bullets: ['GET이 상태를 변경하는지 먼저 확인한다.', 'POST·PUT·PATCH·DELETE 요청에 토큰·Origin·Referer·Fetch Metadata 검증이 있는지 본다.', 'SameSite 설정이 실제 서비스의 도메인 구조와 맞는지 확인한다.', 'XSS가 있으면 CSRF 방어가 무력화될 수 있다는 점을 함께 평가한다.'] },
      { title: '방어 관점', body: 'OWASP는 프레임워크 기본 보호를 우선 사용하고, 동기화 토큰 또는 세션에 묶인 Signed Double-Submit Cookie, Origin 검증, Fetch Metadata, SameSite를 방어 심층으로 조합하라고 안내합니다. 상태 변경에 GET을 쓰지 않는 것도 중요합니다.' },
    ],
    checklist: ['상태 변경 요청과 안전한 조회 요청을 구분했는가?', '토큰 검증 주체가 서버인가?', 'SameSite만으로 충분하다고 단정하지 않았는가?'],
    caseStudy: { title: '최근 방어의 변화', body: '요즘은 CSRF 토큰 하나만 보는 대신 SameSite, Origin/Referer, Sec-Fetch-Site를 함께 사용하고, 로그 전용 모드로 오탐을 확인한 뒤 차단 정책을 적용합니다. 보고서에는 어떤 브라우저·도메인·인증 방식에서 성립하는지 적어야 합니다.', source: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' },
    warmup: { id: 'warmup-5', week: 5, title: 'LOW · 상태 변경 요청 구분', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '실습 서비스의 요청 목록에서 조회와 상태 변경 요청을 분류하고, 각 상태 변경 요청에 필요한 검증 항목을 표시합니다.' },
    quiz: [{ q: 'CSRF 방어의 핵심 목적은?', options: ['브라우저의 화면을 예쁘게 만들기', '상태 변경 요청이 신뢰된 흐름에서 온 것인지 검증하기', '모든 쿠키를 삭제하기'], answer: 1, explanation: '인증 쿠키가 자동 전송되어도 요청의 의도와 출처를 추가로 검증해야 합니다.' }],
  },
  6: {
    title: 'AI와 웹 문제 풀이',
    summary: 'AI를 정답 생성기가 아니라 가설·체크리스트·보고서 초안 보조로 사용하고, 모든 결과를 HTTP 근거로 검증합니다.',
    sources: [source('OWASP WSTG · 최신판', 'https://owasp.org/www-project-web-security-testing-guide/latest/'), source('Google Bug Hunters · 좋은 보고서', 'https://bughunters.google.com/learn/improving-your-reports/getting-started/what-is-a-security-vulnerability'), source('OWASP Top 10 · 2025', 'https://owasp.org/www-project-top-ten/')],
    diagram: ['관찰한 증거', 'AI에 가설 질문', '수동 재현', '근거 대조', '보고서 작성'],
    sections: [
      { title: 'AI를 사용할 위치', bullets: ['관찰한 요청·응답을 표로 정리하게 한다.', '가능한 원인과 반증 방법을 여러 개 제안받는다.', 'OWASP 항목과 보고서 목차를 비교한다.', '생성된 페이로드·영향·패치 주장은 공식 문서와 실습 결과로 검증한다.'] },
      { title: 'AI에 맡기지 않을 것', body: '실제 대상에 대한 범위 판단, 취약점 확정, 영향 산정, 민감 정보 처리, 공격 실행은 사람이 통제해야 합니다. AI가 그럴듯한 오류 메시지나 존재하지 않는 CVE를 만들 수 있으므로 출처와 캡처를 함께 관리합니다.' },
      { title: '방어 관점', body: 'OWASP Top 10 2025와 WSTG의 테스트 목적을 기준선으로 삼고, 자동화 도구의 결과는 수동 검증이 끝난 뒤에만 보고서에 반영합니다.' },
    ],
    checklist: ['AI 입력에 비밀값을 넣지 않았는가?', 'AI 답변마다 검증 근거가 있는가?', '추측과 관찰을 문장으로 구분했는가?'],
    caseStudy: { title: '좋은 보고서와 나쁜 보고서의 차이', body: 'Google Bug Hunters는 공격 시나리오가 실제 사용자 데이터나 권한에 영향을 주는지를 중심으로 판단하고, 단순한 자기 브라우저 조작은 보안 취약점으로 보지 않는다고 설명합니다. AI를 쓸수록 이 구분을 더 엄격히 해야 합니다.', source: 'https://bughunters.google.com/learn/invalid-reports/web-platform/xss/do-it-yourself-xss' },
    warmup: { id: 'warmup-6', week: 6, title: 'LOW · AI 답변 검증하기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '웹 요청 하나를 근거로 AI에게 분석을 요청하고, 답변 중 사실·가설·검증이 필요한 주장을 세 종류로 나눕니다.' },
    quiz: [{ q: 'AI가 제안한 취약점 판단을 보고서에 넣기 전 필요한 것은?', options: ['그럴듯하면 그대로 복사한다', '공식 문서와 실습 증거로 재현·검증한다', '출처를 삭제한다'], answer: 1, explanation: 'AI 출력은 가설일 뿐이며 재현 가능한 근거가 있어야 합니다.' }],
  },
  7: {
    title: '컴퓨터 아키텍처와 메모리 레이아웃',
    summary: '프로세스 주소 공간과 메모리 영역을 관찰해 이후 디버깅에서 주소와 상태를 읽을 수 있는 기반을 만듭니다.',
    sources: [source('Linux · proc_pid_maps', 'https://man7.org/linux/man-pages/man5/proc_pid_maps.5.html'), source('Dreamhack · 컴퓨터 과학 배경', 'https://dreamhack.io/lecture/units/background-computer-science'), source('Dreamhack · Linux Memory Layout', 'https://dreamhack.io/lecture/units/linux-memory-layout')],
    diagram: ['높은 주소', '스택', '공유 라이브러리', '힙', '데이터 / BSS', '코드', '낮은 주소'],
    sections: [{ title: '핵심 개념', body: '프로세스는 실행 파일 전체를 한 덩어리로 다루지 않고 코드·읽기 전용 데이터·전역 데이터·힙·스택과 같은 영역으로 나눠 사용합니다. 실제 배치는 운영체제와 로더, ASLR 등 설정의 영향을 받습니다.' }, { title: '관찰 순서', bullets: ['프로세스의 매핑 목록과 권한을 확인한다.', '읽기·쓰기·실행 권한을 영역별로 비교한다.', '지역 변수·동적 할당·함수 호출이 어느 영역과 연결되는지 추적한다.'] }, { title: '방어 관점', body: 'NX, ASLR, PIE, RELRO 같은 완화 기법은 메모리 오용의 예측 가능성과 실행 가능성을 줄입니다. 완화 기법을 우회하는 방법보다 먼저 어떤 위협을 줄이는지 설명합니다.' }],
    checklist: ['영역과 권한을 구분했는가?', '주소가 실행마다 바뀔 수 있음을 기록했는가?', '관찰 결과와 일반적인 메모리 모델을 구분했는가?'],
    caseStudy: { title: '실무 연결', body: '메모리 취약점 보고서는 “크래시가 났다”에서 끝나지 않고 어떤 입력 길이·상태·영역에서 오류가 발생하는지와 방어 완화 기법의 상태를 함께 기록합니다.', source: 'https://man7.org/linux/man-pages/man5/proc_pid_maps.5.html' },
    warmup: { id: 'warmup-7', week: 7, title: 'LOW · 프로세스 매핑 읽기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '실습 프로세스의 메모리 매핑에서 코드·힙·스택 영역을 찾고 각 영역의 권한을 표로 정리합니다.' },
    quiz: [{ q: '스택과 힙을 구분하는 가장 적절한 기준은?', options: ['둘 다 항상 같은 주소를 사용한다', '호출 프레임과 동적 할당이라는 사용 맥락이 다르다', '둘 다 실행 권한이 필수다'], answer: 1, explanation: '스택은 호출 흐름과 지역 상태, 힙은 동적 할당 수명과 연결해 관찰합니다.' }],
  },
  8: {
    title: 'x86 Assembly와 GDB',
    summary: '명령어를 외우기보다 레지스터·스택·메모리의 상태가 한 명령 뒤 어떻게 바뀌는지 기록합니다.',
    sources: [source('Intel · 64 and IA-32 Manuals', 'https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html'), source('GDB Documentation', 'https://sourceware.org/gdb/documentation/'), source('Dreamhack · x86 Assembly', 'https://dreamhack.io/lecture/units/x86-assembly'), source('Dreamhack · GDB', 'https://dreamhack.io/lecture/units/gdb')],
    diagram: ['명령어', '레지스터 변화', '메모리 접근', '스택 프레임', '다음 실행 위치'],
    sections: [{ title: '핵심 개념', body: '어셈블리 분석은 명령어 이름을 번역하는 작업보다 데이터가 어느 레지스터와 메모리 위치를 거치는지 추적하는 작업입니다. GDB는 중단점·단일 단계·레지스터·메모리·콜 스택을 관찰하는 도구입니다.' }, { title: '관찰 순서', bullets: ['함수 진입 전후의 스택 포인터와 베이스 포인터를 비교한다.', '인자의 이동과 반환값 위치를 확인한다.', '분기 조건이 어떤 플래그에 의존하는지 기록한다.', '소스·디스어셈블리·메모리 관찰을 하나의 타임라인으로 묶는다.'] }, { title: '방어 관점', body: '디버거로 확인한 주소와 값은 실행 환경에 종속될 수 있습니다. 보고서에는 컴파일 옵션, 아키텍처, 재현 환경을 적고, 완화 기법이 결과에 미친 영향도 분리해서 씁니다.' }],
    checklist: ['명령어 전후 상태를 비교했는가?', '레지스터와 메모리 값을 혼동하지 않았는가?', '재현 환경을 기록했는가?'],
    caseStudy: { title: '좋은 디버깅 기록', body: 'GDB 로그는 명령어 목록보다 “어느 시점에 어떤 값이 왜 바뀌었는가”가 중요합니다. 보고서에는 중단점 위치, 관찰 값, 기대 값, 차이를 간결하게 남깁니다.', source: 'https://sourceware.org/gdb/current/onlinedocs/gdb.html/' },
    warmup: { id: 'warmup-8', week: 8, title: 'LOW · 한 함수 추적', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '작은 실습 바이너리의 함수 하나를 중단점과 단일 단계로 추적하고 인자·반환값·스택 변화를 기록합니다.' },
    quiz: [{ q: 'GDB에서 중단점의 목적은?', options: ['프로그램을 영구 삭제하기 위해', '특정 실행 지점에서 상태를 관찰하기 위해', '네트워크 패킷을 암호화하기 위해'], answer: 1, explanation: '중단점은 실행을 멈춰 레지스터와 메모리를 관찰할 수 있게 합니다.' }],
  },
  9: {
    title: 'Pwntools와 Shellcode',
    summary: '익스플로잇 자동화 도구의 역할과 실행 파일·프로세스 상호작용을 이해하되, 모든 실습은 격리된 로컬 환경에서 진행합니다.',
    sources: [source('Pwntools Documentation', 'https://docs.pwntools.com/en/stable/'), source('Pwntools · asm', 'https://docs.pwntools.com/en/stable/asm.html'), source('Linux man-pages · execve', 'https://man7.org/linux/man-pages/man2/execve.2.html'), source('Dreamhack · Pwntools', 'https://dreamhack.io/lecture/units/pwntools'), source('Dreamhack · Shellcode', 'https://dreamhack.io/lecture/units/shellcode')],
    diagram: ['Python 스크립트', '프로세스 / 소켓', '입력·출력 동기화', '바이너리 상태', '검증 가능한 결과'],
    sections: [{ title: '핵심 개념', body: 'Pwntools는 CTF와 격리된 실습에서 프로세스·소켓·바이너리 형식·패킹·디버거 연결을 반복 가능하게 만드는 Python 라이브러리입니다. Shellcode는 실행 환경과 권한, 메모리 실행 가능성에 강하게 의존합니다.' }, { title: '확인 순서', bullets: ['로컬 바이너리와 실행 환경을 고정한다.', '입력·출력 동기화와 실패 시점을 로그로 남긴다.', '아키텍처와 엔디언을 확인한다.', '네트워크 대상이 아닌 로컬 실습 프로세스만 사용한다.'] }, { title: '방어 관점', body: '실무 보고서에서는 실행 가능한 문자열보다 취약한 입력 경계, 메모리 권한, 완화 기법 상태와 패치 방향이 중요합니다. 운영 환경에서의 무단 실행이나 지속성 확보는 학습 범위를 벗어납니다.' }],
    checklist: ['대상 범위를 고정했는가?', '프로세스와 소켓 상태를 로그로 남겼는가?', '실행 환경과 아키텍처를 명시했는가?'],
    caseStudy: { title: '실습 범위', body: 'Pwntools 공식 문서도 CTF와 익스플로잇 개발용 라이브러리로 설명합니다. 이 트랙에서는 제공된 바이너리와 컨테이너 안에서만 재현하고, 보고서에는 격리 조건을 반드시 적습니다.', source: 'https://docs.pwntools.com/en/stable/' },
    warmup: { id: 'warmup-9', week: 9, title: 'LOW · 프로세스 입출력 연결', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '제공된 로컬 실습 바이너리에 연결해 입력과 출력의 순서를 기록하고, 실패 시점과 재현 조건을 정리합니다.' },
    quiz: [{ q: 'Pwntools를 사용하는 교육적 목적은?', options: ['실제 서비스에 자동 공격하기 위해', '허가된 실습의 반복·기록·검증을 자동화하기 위해', '비밀번호를 저장하기 위해'], answer: 1, explanation: '자동화는 재현성을 높이는 도구이며 범위와 권한을 대신 판단하지 않습니다.' }],
  },
  10: {
    title: '함수 호출 규약과 Stack BOF',
    summary: '함수 호출이 인자·반환값·스택 프레임을 어떻게 약속하는지 이해하고, 메모리 오염을 방어 관점에서 분석합니다.',
    sources: [source('System V AMD64 ABI', 'https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf'), source('GDB · Examining the Stack', 'https://sourceware.org/gdb/current/onlinedocs/gdb.html/Examining-the-Stack.html'), source('CERT C · Buffer Handling', 'https://wiki.sei.cmu.edu/confluence/display/c/STR31-C.+Guarantee+that+storage+for+strings+has+sufficient+space'), source('Dreamhack · Calling Convention', 'https://dreamhack.io/lecture/units/calling-convention'), source('Dreamhack · Stack Buffer Overflow', 'https://dreamhack.io/lecture/units/stack-buffer-overflow')],
    diagram: ['호출자', '인자 전달', 'Return address', '지역 변수', '경계 검사', '안전한 반환'],
    sections: [{ title: '핵심 개념', body: '호출 규약은 인자 전달 위치, 반환값, 호출자·피호출자 보존 레지스터, 스택 정리 규칙을 정합니다. Stack BOF는 버퍼의 경계를 넘은 입력이 인접한 제어 데이터나 상태를 덮을 수 있는 메모리 안전성 문제입니다.' }, { title: '확인 순서', bullets: ['입력 버퍼의 크기와 복사 함수의 길이 검사를 확인한다.', '크래시가 발생한 지점과 손상된 스택 상태를 기록한다.', 'ASLR·NX·Canary·PIE·RELRO 상태를 확인한다.', '재현은 제공된 로컬 바이너리에서만 하고 실제 서비스에는 적용하지 않는다.'] }, { title: '방어 관점', body: '길이 검증, 안전한 API, 컴파일러 완화 기법, 테스트와 코드 리뷰를 함께 적용합니다. 완화 기법은 버그를 고치는 대체재가 아니라 추가 방어층입니다.' }],
    checklist: ['버퍼 크기와 입력 길이를 명시했는가?', '크래시와 임의 제어를 구분했는가?', '완화 기법을 사실로 확인했는가?'],
    caseStudy: { title: '보고서의 경계', body: '메모리 오류가 확인되었다고 곧바로 모든 시스템에서 임의 코드 실행이 된다고 쓰지 않습니다. 실제 관찰된 영향, 필요한 전제 조건, 완화 기법을 구분해 심각도를 과장하지 않습니다.', source: 'https://wiki.sei.cmu.edu/confluence/display/c/STR31-C.+Guarantee+that+storage+for+strings+has+sufficient+space' },
    warmup: { id: 'warmup-10', week: 10, title: 'LOW · 입력 경계 찾기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '로컬 실습 코드에서 버퍼 크기와 입력 길이 검사를 찾아, 경계가 보장되는 지점과 빠진 지점을 표시합니다.' },
    quiz: [{ q: 'Stack BOF 분석에서 가장 먼저 확인할 것은?', options: ['입력 버퍼의 경계와 복사 길이', '화면 색상', 'DNS 캐시'], answer: 0, explanation: '메모리 안전성 문제는 입력 길이와 저장 공간의 관계에서 시작합니다.' }],
  },
  11: {
    title: 'AI와 Pwn 문제 풀이',
    summary: 'AI를 어셈블리 해설과 디버깅 기록 정리에 활용하되, 실행 결과와 메모리 상태를 사람이 검증합니다.',
    sources: [source('GDB Documentation', 'https://sourceware.org/gdb/documentation/'), source('Pwntools Documentation', 'https://docs.pwntools.com/en/stable/'), source('OWASP Top 10 for LLM Applications', 'https://owasp.org/www-project-top-10-for-large-language-model-applications/')],
    diagram: ['디버깅 로그', 'AI 설명 가설', '명령어별 검증', '사람의 판단', '보고서'],
    sections: [{ title: '핵심 개념', body: 'AI는 레지스터 이름, 호출 흐름, 반복되는 디버깅 로그를 설명하는 보조자로 사용할 수 있습니다. 그러나 바이너리의 실제 상태를 보지 못한 설명은 가설일 뿐입니다.' }, { title: '확인 순서', bullets: ['질문에 비밀값과 운영 대상 정보를 넣지 않는다.', 'AI 설명을 명령어·레지스터·메모리 관찰과 대조한다.', '잘못된 가설도 기록해 왜 배제했는지 남긴다.', '최종 보고서에는 AI가 아니라 직접 확인한 근거를 인용한다.'] }, { title: '방어 관점', body: 'LLM 앱의 과도한 권한과 부적절한 출력 처리는 별도 위험입니다. AI가 쉘이나 도구를 호출하는 경우 사람 승인, 최소 권한, 로그가 필요합니다.' }],
    checklist: ['AI 입력에서 민감 정보를 제거했는가?', '가설과 관찰을 분리했는가?', '도구 실행을 사람이 승인했는가?'],
    caseStudy: { title: 'AI 사용의 실패 지점', body: 'OWASP는 LLM 앱에서 과도한 권한과 안전하지 않은 출력 처리를 주요 위험으로 분류합니다. Pwn 학습에서도 AI에게 실행 권한을 넘기기보다 설명·정리·검증 질문에 한정하는 방식이 안전합니다.', source: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/' },
    warmup: { id: 'warmup-11', week: 11, title: 'LOW · AI 해설 검증', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '짧은 디버깅 로그에 대한 AI 해설을 받고, 실제 GDB 관찰과 일치하는 주장·틀린 주장·추가 확인 항목을 구분합니다.' },
    quiz: [{ q: 'AI가 제안한 어셈블리 해석을 채택하는 기준은?', options: ['답변이 자신 있어 보이는가', '실제 레지스터·메모리 상태와 일치하는가', '답변이 긴가'], answer: 1, explanation: '바이너리 분석의 근거는 실행 상태와 재현 가능한 관찰입니다.' }],
  },
  12: {
    title: 'Crypto와 Forensics 맛보기',
    summary: '암호의 목적과 디지털 증거의 보존·분석 과정을 구분해, 문제 풀이와 조사 보고서를 혼동하지 않습니다.',
    sources: [source('NIST · Cryptographic Standards', 'https://csrc.nist.gov/projects/cryptographic-standards-and-guidelines'), source('NIST · Computer Forensics Tool Testing', 'https://www.nist.gov/itl/ssd/software-quality-group/computer-forensics-tool-testing'), source('Dreamhack · Crypto', 'https://dreamhack.io/lecture/paths/crypto')],
    diagram: ['원본 증거', '해시·보존', '메타데이터 분석', '가설 검증', '타임라인 보고서'],
    sections: [{ title: '핵심 개념', body: '암호화는 기밀성·무결성·인증 등의 목표를 달성하기 위한 수단이고, 인코딩·해싱과 같은 개념과 구분해야 합니다. 포렌식은 원본 증거를 보존하고 분석 절차를 재현 가능하게 만드는 과정입니다.' }, { title: '확인 순서', bullets: ['분석 전 원본 해시와 보관 상태를 기록한다.', '파일 시간·메타데이터·로그·프로세스 흔적을 서로 비교한다.', '하나의 흔적만으로 결론 내리지 않고 독립적인 증거를 찾는다.', '도구 버전과 분석 명령을 보고서에 남긴다.'] }, { title: '방어 관점', body: '강한 알고리즘을 선택하는 것뿐 아니라 키 관리, 로그 무결성, 시간 동기화, 접근 통제가 중요합니다. 포렌식 결과는 가능성·확정·미확인으로 표현을 나눕니다.' }],
    checklist: ['원본과 분석본을 분리했는가?', '해시와 타임라인을 기록했는가?', '사실과 추론을 구분했는가?'],
    caseStudy: { title: '조사 보고서의 신뢰성', body: 'NIST의 도구 테스트 취지는 포렌식 도구의 결과가 재현 가능하고 검증되어야 한다는 점에 있습니다. 화면 캡처 한 장보다 원본 보존과 절차 기록이 우선입니다.', source: 'https://www.nist.gov/itl/ssd/software-quality-group/computer-forensics-tool-testing' },
    warmup: { id: 'warmup-12', week: 12, title: 'LOW · 증거 해시 기록', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '제공된 파일의 해시·크기·생성 시각을 기록하고, 분석본과 원본을 구분해 보관합니다.' },
    quiz: [{ q: '포렌식 분석에서 원본 증거의 해시를 기록하는 이유는?', options: ['파일을 더 예쁘게 보이게 하려고', '분석 전후 동일성을 확인하려고', '네트워크 속도를 높이려고'], answer: 1, explanation: '해시는 원본이 분석 과정에서 바뀌지 않았는지 검증하는 근거입니다.' }],
  },
  13: {
    title: '네트워크 보안',
    summary: 'TCP·UDP·IP와 애플리케이션 흐름을 계층별로 나누어 보고, Wireshark에서 근거 패킷을 찾는 방법을 익힙니다.',
    sources: [source('Wireshark User Guide', 'https://www.wireshark.org/docs/wsug_html/'), source('RFC 9293 · TCP', 'https://www.rfc-editor.org/rfc/rfc9293'), source('RFC 768 · UDP', 'https://www.rfc-editor.org/rfc/rfc768'), source('RFC 791 · IPv4', 'https://www.rfc-editor.org/rfc/rfc791')],
    diagram: ['애플리케이션', 'TCP / UDP', 'IP', '링크', '패킷 캡처와 필터'],
    sections: [{ title: '핵심 개념', body: '네트워크 분석은 패킷 하나를 보는 것보다 흐름을 재구성하는 작업입니다. IP는 전달, TCP는 순서·신뢰성·연결 상태, UDP는 낮은 오버헤드의 비연결 전송이라는 관점으로 나눠 봅니다.' }, { title: '확인 순서', bullets: ['대화의 양 끝점과 시간 범위를 정한다.', 'DNS·TCP handshake·TLS·애플리케이션 요청 순서를 만든다.', 'display filter와 capture filter를 구분한다.', '비정상 판단에는 플래그·재전송·상태 코드 등 패킷 근거를 붙인다.'] }, { title: '방어 관점', body: '암호화는 내용을 숨기지만 메타데이터와 트래픽 패턴까지 자동으로 숨기지는 않습니다. 네트워크 분할, 인증, 최소 노출, 적절한 로깅과 탐지가 함께 필요합니다.' }],
    checklist: ['양 끝점과 시간대를 특정했는가?', '패킷과 애플리케이션 로그를 대조했는가?', '필터를 재현 가능하게 기록했는가?'],
    caseStudy: { title: '분석 보고서의 형태', body: 'Wireshark 공식 문서는 캡처·필터·통계·문제 보고를 각각 다룹니다. 보고서에는 전체 pcap을 무작정 첨부하기보다 관련 패킷 번호, 필터, 시간과 관찰 결과를 함께 제시합니다.', source: 'https://www.wireshark.org/docs/wsug_html/' },
    warmup: { id: 'warmup-13', week: 13, title: 'LOW · TCP 흐름 찾기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '제공된 pcap에서 한 TCP 연결을 찾아 handshake·데이터 교환·종료를 시간순으로 정리합니다.' },
    quiz: [{ q: 'Wireshark 분석에서 가장 먼저 정할 것은?', options: ['관찰할 대화의 양 끝점과 시간 범위', '모든 패킷을 한 문장으로 요약하기', '파일 이름만 변경하기'], answer: 0, explanation: '범위를 정해야 관련 흐름과 근거 패킷을 재현할 수 있습니다.' }],
  },
  14: {
    title: 'Fuzzing',
    summary: '입력 공간을 체계적으로 탐색하고, 크래시를 곧바로 취약점으로 단정하지 않고 재현·분류·축소합니다.',
    sources: [source('Fuzzing101', 'https://github.com/antonio-morales/Fuzzing101'), source('AFL++ Documentation', 'https://aflplus.plus/'), source('LLVM libFuzzer', 'https://llvm.org/docs/LibFuzzer.html')],
    diagram: ['입력 seed', '변형 / 생성', '대상 실행', 'coverage·crash', '재현·분류·수정'],
    sections: [{ title: '핵심 개념', body: 'Fuzzing은 다양한 입력을 자동으로 생성·변형해 프로그램의 예외 상태와 새로운 코드 경로를 찾는 테스트 기법입니다. coverage-guided fuzzing은 실행 경로 정보를 다음 입력 생성에 활용합니다.' }, { title: '확인 순서', bullets: ['seed와 입력 형식을 먼저 이해한다.', '재현 가능한 실행 명령과 제한 시간을 고정한다.', '크래시를 입력 축소로 최소화한다.', '중복 크래시를 스택·원인·영향 기준으로 분류한다.'] }, { title: '방어 관점', body: 'Fuzzer가 찾는 것은 결함 후보입니다. 수정 전후 회귀 테스트, sanitizer 결과, 영향 분석이 필요하며, 운영 서비스에 직접 부하를 주지 않고 격리된 대상에서 실행합니다.' }],
    checklist: ['seed와 대상 버전을 고정했는가?', '크래시 재현 명령이 있는가?', '중복과 원인 분석을 구분했는가?'],
    caseStudy: { title: '크래시와 취약점의 차이', body: '크래시는 안정성 결함의 증거일 수 있지만, 보안 영향은 메모리 손상 종류·권한·입력 경로·완화 기법을 추가로 확인해야 합니다. 이 구분을 보고서에 명시합니다.', source: 'https://llvm.org/docs/LibFuzzer.html' },
    warmup: { id: 'warmup-14', week: 14, title: 'LOW · 크래시 재현 기록', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: 'Fuzzing101 실습 대상에서 하나의 크래시를 선택하고 입력 파일, 실행 명령, 재현 횟수와 관찰 결과를 기록합니다.' },
    quiz: [{ q: 'Fuzzing에서 크래시를 발견한 다음 우선할 일은?', options: ['즉시 공개한다', '재현하고 입력을 축소해 원인을 확인한다', '모든 파일을 삭제한다'], answer: 1, explanation: '재현성과 최소 입력이 원인 분석과 수정에 필요합니다.' }],
  },
  15: {
    title: '클라우드 보안',
    summary: '클라우드의 공유 책임 모델과 IAM·네트워크·스토리지·로그를 연결해, 권한 경계가 어디서 무너지는지 확인합니다.',
    sources: [source('AWS Well-Architected · Security Pillar', 'https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html'), source('CloudGoat', 'https://github.com/RhinoSecurityLabs/cloudgoat'), source('NIST · CSF 2.0', 'https://www.nist.gov/cyberframework')],
    diagram: ['사용자 / 역할', 'IAM 정책', '서비스 API', '리소스 정책', '로그·탐지'],
    sections: [{ title: '핵심 개념', body: '클라우드 보안은 네트워크만 보호하는 문제가 아니라 누가 어떤 역할로 어떤 리소스에 어떤 조건에서 접근하는지의 문제입니다. 공급자가 책임지는 기반과 사용자가 설정하는 권한·데이터·애플리케이션을 구분합니다.' }, { title: '확인 순서', bullets: ['주체·행동·리소스·조건을 IAM 문장으로 분해한다.', '과도한 권한과 공개된 저장소·보안 그룹을 확인한다.', '관리 로그가 켜져 있고 변경 추적이 가능한지 본다.', 'CloudGoat 같은 격리된 학습 환경에서만 실습한다.'] }, { title: '방어 관점', body: '최소 권한, 짧은 자격 증명 수명, 역할 분리, 암호화, 네트워크 분리, 중앙 로그와 알림을 함께 적용합니다. 정책 한 줄보다 실제 호출 경로와 로그를 확인합니다.' }],
    checklist: ['주체·행동·리소스를 명시했는가?', '공급자 책임과 사용자 책임을 구분했는가?', '실습 리소스를 종료했는가?'],
    caseStudy: { title: '클라우드 보고서의 핵심', body: '클라우드 취약점은 “공개되어 있다”보다 어떤 주체가 어떤 API로 어떤 데이터에 도달할 수 있는지와 로그·완화 가능성을 보고해야 합니다.', source: 'https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html' },
    warmup: { id: 'warmup-15', week: 15, title: 'LOW · IAM 경로 그리기', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: 'CloudGoat 실습에서 사용자·역할·정책·리소스 사이의 접근 경로를 그림으로 나타내고 과도한 권한을 한 곳 표시합니다.' },
    quiz: [{ q: '클라우드 권한 분석에서 먼저 분해할 네 가지는?', options: ['주체·행동·리소스·조건', '색상·폰트·화면·브라우저', '파일명·날짜·아이콘·제목'], answer: 0, explanation: 'IAM 권한은 누가 무엇을 어떤 리소스에 어떤 조건으로 할 수 있는지로 분석합니다.' }],
  },
  16: {
    title: 'AI 보안과 최종 정리',
    summary: 'LLM 앱의 입력·출력·도구 권한·데이터 경계를 점검하고, 16주 학습을 보고서와 재현 가능한 근거로 정리합니다.',
    sources: [source('OWASP GenAI · LLM Top 10', 'https://owasp.org/www-project-top-10-for-large-language-model-applications/'), source('NIST AI RMF', 'https://www.nist.gov/itl/ai-risk-management-framework'), source('OWASP Vulnerability Communication Guide', 'https://owasp.org/www-project-vulnerability-management-guide/'), source('FIRST CVSS v4.0', 'https://www.first.org/cvss/v4.0/')],
    diagram: ['사용자 입력', '모델 / 프롬프트', '검색·도구', '외부 데이터', '출력·행동 승인'],
    sections: [{ title: '핵심 개념', body: 'LLM 앱은 모델만의 문제가 아니라 프롬프트, 검색 문서, 도구, 권한, 출력 소비자가 연결된 시스템입니다. OWASP는 Prompt Injection, Sensitive Information Disclosure, Insecure Output Handling, Excessive Agency 등을 주요 위험으로 다룹니다.' }, { title: '확인 순서', bullets: ['신뢰된 지시와 외부 콘텐츠의 경계를 표시한다.', '모델 출력이 실행·저장·권한 변경으로 이어지는 지점을 찾는다.', '도구별 최소 권한과 사람 승인 여부를 확인한다.', '민감 데이터가 입력·검색·로그·출력에 남는 경로를 추적한다.'] }, { title: '보고서와 위험도', body: '취약점 보고서에는 요약·영향 자산·전제 조건·재현 절차·증거·영향·완화·회귀 테스트를 포함합니다. 심각도는 CVSS v4.0의 Base만으로 끝내지 말고 실제 위협과 환경을 함께 설명합니다.' }],
    checklist: ['입력·출력·도구 경계를 그렸는가?', '사람 승인과 최소 권한을 확인했는가?', 'CVSS 점수와 근거를 함께 적었는가?', '공개 전 조정된 제보 절차를 확인했는가?'],
    caseStudy: { title: '현재 보안 흐름', body: 'OWASP GenAI 프로젝트는 LLM 앱 위험을 모델 단독이 아니라 도구·데이터·권한을 포함한 시스템 문제로 다룹니다. CISA의 KEV 카탈로그처럼 실제 악용 여부를 별도로 확인하는 습관도 최종 보고서에 반영합니다.', source: 'https://www.first.org/cvss/v4.0/' },
    warmup: { id: 'warmup-16', week: 16, title: 'LOW · 취약점 보고서 초안', difficulty: '하', points: 5, required: true, type: 'warmup', status: 'open', description: '앞선 주차 중 하나의 문제를 선택해 요약·영향·재현·증거·방어 항목만으로 1페이지 보고서 초안을 작성합니다.' },
    quiz: [{ q: '좋은 보안 보고서의 핵심은?', options: ['도구 이름과 어려운 용어의 개수', '재현 가능한 근거와 영향·완화의 연결', '가장 높은 심각도 주장'], answer: 1, explanation: '보고서는 개발자가 재현하고 수정할 수 있는 근거와 영향 설명을 제공해야 합니다.' }],
  },
}

export { reportGuide }

concepts[4].backgroundIntro = 'XSS를 이해하기 전에 웹 페이지가 어떻게 만들어지고 브라우저가 HTML과 JavaScript를 어떻게 해석하는지부터 확인합니다. 이 단계에서는 공격 절차가 아니라, 왜 입력값이 코드로 바뀔 수 있는지와 방어의 기본 원리까지만 다룹니다.'
concepts[4].guideSections = [
  { title: '웹 페이지는 무엇으로 만들어지는가', body: '브라우저는 서버가 보낸 HTML 문서를 읽고 DOM이라는 메모리상의 트리로 바꿉니다. HTML은 문서의 구조와 의미를 표현하고, CSS는 표현을 담당하며, JavaScript는 페이지에 동작과 상호작용을 추가합니다. 사용자가 입력한 문자열이 어느 단계에서 문서 구조나 코드로 해석되는지가 XSS의 출발점입니다.' },
  { title: '<script>는 무엇인가', body: 'HTML의 <script> 요소는 브라우저가 실행할 JavaScript를 문서에 포함하거나 외부 파일로 연결하는 요소입니다. 브라우저는 일반 텍스트와 실행 가능한 문맥을 다르게 처리합니다. 따라서 서버가 사용자 입력을 script 문맥이나 이벤트 핸들러 같은 실행 문맥에 안전하지 않게 끼워 넣으면 단순한 문자열이 아니라 동작으로 해석될 수 있습니다.', code: '<script src="app.js" defer></script>\n\n// app.js\nconst button = document.querySelector("button");\nbutton.addEventListener("click", () => {\n  console.log("사용자 동작");\n});' },
  { title: 'DOM과 JavaScript의 관계', body: 'DOM은 HTML 문서를 객체와 노드의 트리로 표현하는 Web API입니다. JavaScript는 DOM API를 통해 요소를 찾고, 텍스트와 속성을 바꾸고, 이벤트를 등록합니다. 이때 URL 조각이나 저장된 데이터가 안전하지 않은 DOM sink로 흘러가면 서버 응답에 문자열이 없더라도 DOM-based XSS가 생길 수 있습니다.' },
  { title: '브라우저가 문맥을 해석하는 방법', body: '같은 입력이라도 HTML 본문, HTML 속성, URL, CSS, JavaScript 문자열 안에 들어가면 해석 규칙이 달라집니다. 그래서 “특수 문자를 모두 지웠다”는 방어 설명은 충분하지 않습니다. 출력 위치에 맞는 인코딩과 안전한 API를 선택해야 합니다.' },
  { title: 'XSS의 세 가지 유형', bullets: ['Reflected XSS: 요청에 들어온 값이 같은 응답에서 반사되는 형태입니다.', 'Stored XSS: 저장된 값이 나중에 다른 사용자의 화면에 출력되는 형태입니다.', 'DOM-based XSS: 브라우저 JavaScript가 URL·저장소 등 source를 읽어 위험한 sink로 전달하는 형태입니다.'] },
  { title: '방어 원칙', body: 'OWASP의 우선순위는 출력 문맥별 인코딩, 안전한 sink 사용, 필요한 경우 검증된 HTML sanitization, CSP를 방어 심층으로 조합하는 것입니다. CSP는 보조 통제이며, 서버와 클라이언트의 출력 처리를 대신하지 않습니다. 세션 쿠키에는 HttpOnly·Secure·SameSite를 올바른 범위와 함께 적용합니다.' },
]
concepts[4].reports = [
  { type: '공개 제보 분석 · HTML Injection과 XSS 구분', title: 'Google Bug Hunters · Reflected XSS 사례', target: 'YouTube Blog 검색', entry: 'tags 파라미터가 결과 HTML에 반사되는 지점', impact: 'CSP 조건에 따라 HTML Injection으로 분류', discovery: '제보자는 검색 요청의 입력이 응답 HTML에 반사되는 위치를 특정하고, 브라우저에서 어떤 문맥으로 렌더링되는지 확인했습니다. 중요한 점은 “반사됨”만 주장하지 않고 CSP가 실제 실행을 어떻게 제한하는지까지 확인했다는 것입니다.', scenario: '공격자가 조작된 검색 링크를 만들고 피해자가 열었을 때 입력이 결과 페이지에 나타나는 흐름을 설명합니다. 보고서에서는 자기 브라우저의 개발자 도구를 조작한 Self-XSS와, 다른 사용자가 링크를 열어 영향을 받는 Reflected XSS를 구분해야 합니다.', fix: '출력 문맥에 맞는 인코딩과 허용 목록 검증을 적용하고, CSP는 보조 방어로 유지합니다. 영향이 HTML 렌더링인지 스크립트 실행인지 보고서에서 정확히 구분합니다.', lesson: '실행 여부와 영향 범위를 과장하지 않고, 브라우저의 실제 해석 결과로 분류한다.', source: 'https://bughunters.google.com/reports/vrp/hFQjByYnm/report' },
  { type: '공개 권고 분석 · 의존성의 출력 경계', title: 'PostCSS CVE-2026-41305 · style 문맥 탈출', target: 'PostCSS CSS stringify 출력', entry: '사용자 제어 CSS가 HTML <style> 안에 삽입되는 경계', impact: '조건이 맞으면 HTML 문맥이 깨져 XSS로 이어질 수 있음', discovery: '공개 advisory는 CSS AST를 문자열로 만들 때 style 종료 문자열이 안전하게 처리되지 않는 경우를 문제로 설명합니다. 이 사례는 입력이 JavaScript처럼 보이지 않아도 최종 출력 문맥이 HTML이면 XSS가 될 수 있음을 보여줍니다.', scenario: '공격자가 제어한 CSS가 서버나 빌드 파이프라인을 거쳐 HTML style 요소 안에 들어가고, 브라우저가 style 경계를 다시 해석하는 흐름입니다. 실제 운영 대상이 아니라 advisory의 재현 조건과 영향 설명만 읽고 분석합니다.', fix: '수정 코드는 “CSS 값이 HTML style 문맥으로 들어갈 때 style 종료 시퀀스를 안전하게 처리한다”는 원칙으로 읽습니다. 아래 코드는 원문 복사가 아닌 학습용 의사 코드입니다.', code: 'const safeCss = escapeStyleTerminator(untrustedCss);\nconst html = `<style>${safeCss}</style>`;', lesson: '취약점은 입력의 겉모양보다 최종 sink와 출력 문맥으로 판단한다.', source: 'https://github.com/advisories/GHSA-qx2v-qp2m-jg93' },
  { type: '공식 사례 · 제품 취약점', title: 'CISA 공개 XSS 사례를 읽는 법', target: 'Adobe Experience Manager', entry: '폼·검색·DOM 처리 등 여러 입력 경로', impact: '저권한 사용자가 입력한 값이 다른 사용자의 브라우저에서 실행될 수 있음', discovery: 'CISA 요약은 취약점 유형을 Stored·Reflected·DOM-based로 나누고, 공격자가 어떤 조건에서 입력을 넣고 피해자가 어떤 화면을 보는지 설명합니다. 학생은 이 구조를 그대로 보고서 목차로 바꿔 읽습니다.', scenario: '공격자 권한, 피해자의 방문 또는 상호작용, 취약한 페이지의 출력 위치를 분리해 적습니다. “모든 사용자가 즉시 탈취된다”처럼 전제를 생략한 표현은 피합니다.', fix: '출력 인코딩, 안전한 DOM API, 입력 검증과 업데이트된 버전 적용을 함께 검토합니다. 패치가 배포되면 영향 버전과 수정 버전을 명시합니다.', lesson: '유형·권한·사용자 상호작용·영향을 한 문장에 섞지 않고 단계별로 쓴다.', source: 'https://www.cisa.gov/news-events/bulletins/sb23-360' },
]

concepts[4].reports.push({ type: '공식 권고 · SQL Injection 실제 피해', title: 'CISA/FBI Secure by Design · SQLi 사례', target: '관리형 파일 전송 제품', entry: '사용자 입력이 데이터베이스 쿼리로 이어지는 서버 기능', impact: '기밀성·무결성·가용성에 영향을 줄 수 있으며 다수 조직이 피해를 입은 사례', discovery: 'CISA와 FBI는 공개된 SQL Injection 결함이 관리형 파일 전송 제품을 겨냥한 캠페인에서 악용되어 수천 개 조직에 영향을 준 사례를 바탕으로 권고를 발표했습니다. 보고서에는 취약점 이름보다 영향 자산과 실제 피해 범위를 먼저 씁니다.', scenario: '입력값이 데이터와 쿼리 구조를 구분하지 못하는 서버 경계를 거쳐 데이터베이스에 도달하는 흐름을 그립니다. 교육 실습에서는 데이터 변경이나 대량 추출 없이, 허가된 데이터와 응답 차이로 취약한 경계를 증명합니다.', fix: 'Prepared Statement와 파라미터 바인딩을 기본값으로 사용하고, 최소 권한 DB 계정·안전한 오류 처리·입력 allow-list를 보조 통제로 적용합니다. 문자열 차단만을 유일한 방어로 제시하지 않습니다.', lesson: '근본 원인인 코드와 데이터의 혼합을 수정 방향과 직접 연결한다.', source: 'https://www.cisa.gov/news-events/alerts/2024/03/25/cisa-and-fbi-release-secure-design-alert-urge-manufacturers-eliminate-sql-injection-vulnerabilities' })

concepts[1].reading = {
  tabLabel: 'Linux 명령어 읽을거리',
  title: 'Linux 명령어 참고',
  summary: 'Bandit 문제에서 자주 쓰는 파일 탐색, 내용 확인, 문자열 검색 명령을 정리합니다. 각 명령의 기본 형식과 자주 쓰는 옵션을 먼저 보고, 다음 실습에서 직접 사용합니다.',
  groups: [
    {
      kicker: '01 · 탐색', title: '경로와 디렉터리 목록', description: '파일 시스템은 루트(/)에서 시작하는 트리입니다. pwd, cd, ls를 같은 묶음으로 사용합니다.',
      items: [
        { command: 'pwd', syntax: 'pwd [옵션]', summary: '현재 작업 디렉터리의 경로를 출력합니다.', level: '기본', when: '경로를 적거나 파일을 찾기 전에 현재 위치를 확인할 때', features: ['옵션 없이 실행: 쉘이 기억하는 현재 경로를 출력', '-L: 심볼릭 링크를 유지한 논리 경로를 출력하는 기본 동작', '-P: 심볼릭 링크를 따라가 실제 디렉터리의 물리 경로를 출력'], sourceLabel: 'GNU Coreutils', source: 'https://www.gnu.org/software/coreutils/manual/html_node/pwd-invocation.html' },
        { command: 'ls', syntax: 'ls [옵션] [파일 및 디렉터리...]', summary: '파일과 디렉터리의 이름 또는 상세 정보를 나열합니다.', level: '기본', when: '현재 폴더 또는 지정한 경로에 무엇이 있는지 확인할 때', features: ['인자 생략: 현재 디렉터리를 대상으로 실행', '-a / --all: .과 ..을 포함해 .으로 시작하는 숨김 파일도 표시', '-A / --almost-all: .과 ..은 빼고 나머지 숨김 파일을 표시', '-l: 파일 유형·권한·링크 수·소유자·그룹·크기·수정 시각·이름을 긴 형식으로 표시', '-h: -l과 함께 쓰면 크기를 KiB·MiB·GiB처럼 읽기 쉬운 단위로 표시', '-t: 수정 시각이 최근인 파일부터 정렬, -r: 현재 정렬 순서를 뒤집음', '-R: 하위 디렉터리까지 재귀적으로 출력하므로 큰 경로에서는 결과가 매우 길어질 수 있음', '-la: 숨김 파일까지 긴 형식으로 확인할 때 가장 자주 쓰는 조합'], sourceLabel: 'GNU Coreutils · ls', source: 'https://www.gnu.org/software/coreutils/manual/html_node/ls-invocation.html' },
        { command: 'cd', syntax: 'cd [디렉터리]', summary: '쉘의 현재 작업 디렉터리를 바꿉니다.', level: '기본', when: '다른 경로의 파일을 살피거나 상대 경로의 기준을 바꿀 때', features: ['cd inhere: 현재 경로 아래의 inhere로 이동하는 상대 경로', 'cd ..: 상위 디렉터리로 이동, cd .: 현재 위치를 그대로 유지', 'cd /home/bandit0: /부터 시작하는 절대 경로로 이동', 'cd ~: 현재 사용자의 홈 디렉터리로 이동', 'cd -: 직전에 있던 디렉터리로 되돌아감'], sourceLabel: 'GNU Bash Manual', source: 'https://www.gnu.org/software/bash/manual/bash.html' },
      ],
    },
    {
      kicker: '02 · 파일 읽기', title: '파일 형식과 내용', description: '확장자만 보지 않고 file로 형식을 확인한 뒤, 텍스트 파일을 읽습니다.',
      items: [
        { command: 'file', syntax: 'file [옵션] 파일...', summary: '파일 내용의 특징을 바탕으로 형식을 판별합니다.', level: '기본', when: '확장자 없이 제공된 파일이 텍스트인지, 실행 파일인지 구분할 때', features: ['file readme: readme 파일의 형식을 한 줄로 출력', '-b: 파일 이름을 빼고 형식 설명만 출력', '-i: 사람이 읽는 설명 대신 MIME 형식과 인코딩을 출력', '파일명 확장자가 아니라 파일 앞부분의 매직 값 등을 참고', '디렉터리는 directory로 표시'], sourceLabel: 'file(1) manual', source: 'https://man7.org/linux/man-pages/man1/file.1.html' },
        { command: 'cat', syntax: 'cat [옵션] 파일...', summary: '짧은 텍스트 파일의 내용을 표준 출력으로 보냅니다.', level: '기본', when: '형식을 확인한 짧은 텍스트 파일의 내용을 읽을 때', features: ['cat FLAG1.txt: 파일 내용을 그대로 출력', '-n: 빈 줄을 포함해 모든 출력 줄에 번호를 붙임', '-b: 비어 있지 않은 줄에만 번호를 붙임', '-A: 줄 끝, 탭처럼 보이지 않는 문자를 표시', '큰 파일은 한 번에 출력하지 말고 less, head, tail을 고려'], sourceLabel: 'GNU Coreutils · cat', source: 'https://www.gnu.org/software/coreutils/manual/html_node/cat-invocation.html' },
        { command: 'head / tail', syntax: 'head [옵션] 파일... · tail [옵션] 파일...', summary: '파일의 앞부분 또는 뒷부분만 확인합니다.', level: '기본', when: '로그 또는 큰 파일의 일부만 빠르게 볼 때', features: ['head 파일: 처음 10줄, tail 파일: 마지막 10줄을 표시', '-n N: 볼 줄 수를 N으로 지정. 예: tail -n 20 access.log', '-c N: 줄이 아니라 앞·뒤 N바이트를 표시', 'tail -f: 파일 끝에 새로 추가되는 내용을 계속 표시. 로그 확인에 사용하며 종료는 Ctrl+C'], sourceLabel: 'GNU Coreutils Manual', source: 'https://www.gnu.org/software/coreutils/manual/' },
        { command: 'man', syntax: 'man 명령어', summary: '설치된 명령어의 매뉴얼 페이지를 엽니다.', level: '습관', when: '옵션을 사용하기 전 공식 사용법을 확인할 때', features: ['NAME: 명령어의 한 줄 설명', 'SYNOPSIS: 기본 형식', 'DESCRIPTION / OPTIONS: 동작과 옵션'], sourceLabel: 'man(1) manual', source: 'https://man7.org/linux/man-pages/man1/man.1.html' },
      ],
    },
    {
      kicker: '03 · 탐색과 검색', title: '파일 경로와 문자열 검색', description: 'find로 후보 파일을 찾고 grep으로 필요한 줄을 좁힙니다.',
      items: [
        { command: 'find', syntax: 'find [시작 경로] [조건]', summary: '시작 경로 아래에서 조건에 맞는 파일을 찾습니다.', level: '핵심', when: '파일 이름을 모르거나 하위 디렉터리까지 후보를 찾아야 할 때', features: ['find . -type f: 현재 경로 아래의 일반 파일만 찾기', 'find . -type d: 디렉터리만 찾기', 'find . -name "*.txt": 이름 패턴으로 찾기. 따옴표는 셸이 *를 먼저 해석하지 않게 함', 'find . -maxdepth 2: 현재 위치에서 두 단계 아래까지만 탐색', 'find . -size +1M: 1MiB보다 큰 파일 찾기', '출력 결과는 다음 명령에 넘길 파일 경로 목록'], sourceLabel: 'GNU findutils Manual', source: 'https://www.gnu.org/software/findutils/manual/html_mono/find.html' },
        { command: 'grep', syntax: 'grep [옵션] 패턴 파일...', summary: '텍스트에서 패턴이 포함된 줄을 출력합니다.', level: '핵심', when: '로그·설정 파일에서 특정 키워드나 FLAG 형식의 문자열을 찾을 때', features: ['grep FLAG evidence.log: FLAG가 들어 있는 줄 찾기', '-i: 대소문자를 구분하지 않음', '-n: 일치한 줄 번호를 함께 표시', '-v: 패턴과 일치하지 않는 줄만 출력', '-r: 지정한 디렉터리 아래의 파일을 재귀적으로 검색', '-E: 확장 정규표현식을 사용. 예: grep -E "ERROR|WARN" app.log'], sourceLabel: 'GNU grep Manual', source: 'https://www.gnu.org/software/grep/manual/grep.html' },
        { command: '파이프', syntax: '명령1 | 명령2', summary: '앞 명령의 출력을 다음 명령의 입력으로 연결합니다.', level: '핵심', when: '목록이나 검색 결과를 추가로 좁힐 때', features: ['ls -la | grep FLAG: 목록에서 FLAG라는 이름만 찾기', '왼쪽 명령의 표준 출력이 오른쪽 명령의 표준 입력이 됨'], sourceLabel: 'GNU Bash · Pipelines', source: 'https://www.gnu.org/s/bash/manual/html_node/Pipelines.html' },
      ],
    },
  ],
  safety: ['처음에는 읽기 전용 명령어로 상태를 확인하고, 파일 변경 명령어는 의미를 이해한 뒤 사용한다.', '실습에서 찾은 비밀번호·토큰·키처럼 보이는 값은 공유 채널이나 AI 입력에 그대로 붙여 넣지 않는다.', '명령어 출력은 “어떤 파일에서, 어떤 명령으로, 언제 확인했는지”와 함께 블로그에 기록한다.', '권한 오류를 숨기기 위해 무조건 sudo를 쓰지 않고, 왜 권한이 필요한지 먼저 확인한다.'],
}
