export const reportSections = [
  { id: 'scope', label: '01. 대상과 범위', fields: ['findingId', 'title', 'status', 'severity', 'asset', 'endpoint', 'method', 'parameter', 'authPrerequisites', 'environment'] },
  { id: 'flow', label: '02. 데이터 흐름', fields: ['vulnerabilityType', 'source', 'transforms', 'sink', 'context', 'summary'] },
  { id: 'reproduce', label: '03. 재현과 증거', fields: ['prerequisites', 'reproductionSteps', 'request', 'response', 'poc', 'observedResult', 'expectedResult'] },
  { id: 'impact', label: '04. 영향과 원인', fields: ['technicalImpact', 'businessImpact', 'likelihoodRationale', 'impactScope', 'rootCause'] },
  { id: 'fix', label: '05. 개선과 재시험', fields: ['remediation', 'vulnerableCode', 'fixedCode', 'temporaryMitigation', 'retestProcedure', 'retestResult', 'references'] },
]

export const emptyReport = {
  id: 'local-xss-draft',
  findingId: 'W4-XSS-001',
  title: '',
  status: 'draft',
  severity: 'Medium',
  cvssVersion: '4.0',
  cvssVector: '',
  cvssScore: '',
  cwe: 'CWE-79',
  owaspMapping: 'WSTG-INPV-01',
  asset: 'Local Training App',
  endpoint: '/labs/xss/reflected-search',
  method: 'GET',
  parameter: 'q',
  authPrerequisites: '인증 불필요',
  environment: 'SecTrack 로컬 교육용 시뮬레이터 / Chromium 계열 브라우저',
  vulnerabilityType: 'Reflected XSS',
  source: 'URL query parameter q',
  transforms: '요청 파싱 → 서버 템플릿 렌더링',
  sink: 'escaping이 해제된 HTML 본문 출력',
  context: 'HTML body',
  summary: '',
  prerequisites: '학습자가 로컬 실습 Route에 접근할 수 있음',
  reproductionSteps: '',
  request: 'GET /labs/xss/reflected-search?q=UNIQUE_MARKER HTTP/1.1\nHost: training.local\nCookie: TRAINING_SESSION=[REDACTED]',
  response: '',
  poc: '고정된 교육용 문자열 표시 PoC만 사용',
  observedResult: '',
  expectedResult: '입력값이 텍스트로만 표시되고 HTML 또는 JavaScript로 해석되지 않아야 한다.',
  technicalImpact: '',
  businessImpact: '',
  likelihoodRationale: '',
  impactScope: '',
  rootCause: '',
  remediation: '',
  vulnerableCode: 'result.innerHTML = query;',
  fixedCode: 'result.textContent = query;',
  temporaryMitigation: '수정 배포 전 해당 출력 지점 비활성화와 CSP 모니터링을 검토한다. WAF만으로 종결하지 않는다.',
  retestProcedure: '',
  retestResult: '',
  references: 'OWASP XSS Prevention Cheat Sheet\nOWASP WSTG Testing for Reflected XSS',
  updatedAt: '',
}

export const completedExampleReport = {
  ...emptyReport,
  id: 'sample-w4-xss-001',
  title: '검색 결과의 q 파라미터가 HTML 본문에 인코딩 없이 반사되어 Reflected XSS 발생',
  summary: '검색어 q가 현재 응답의 HTML 본문에 텍스트 처리 없이 삽입되어 브라우저가 입력 일부를 마크업으로 해석합니다.',
  reproductionSteps: '1. 로컬 검색 실습 페이지에 접속한다.\n2. q에 고유 마커 UNIQUE_MARKER를 입력한다.\n3. 응답에서 마커가 HTML body 안에 반사되는 위치를 확인한다.\n4. 내장된 무해한 PoC를 선택해 실행 표시를 확인한다.\n5. 요청·응답·DOM과 취약 코드 줄을 증거로 저장한다.',
  response: 'HTTP/1.1 200 OK\nContent-Type: text/html; charset=utf-8\nContent-Security-Policy: default-src \'self\'\n\n<section id="result">UNIQUE_MARKER</section>',
  observedResult: 'q 값이 `<section id="result">` 내부에 인코딩 없이 들어가며, 실습용 실행 모드에서 고정 문자열이 DOM에 추가되었다.',
  technicalImpact: '피해자 브라우저에서 동일 Origin의 스크립트가 실행될 수 있어 DOM 데이터 읽기와 사용자 권한 내 동작 수행 가능성이 생긴다.',
  businessImpact: '관리 기능을 사용하는 운영자가 조작된 링크를 열 경우 화면 변조와 운영 기능 오용으로 이어질 수 있다.',
  likelihoodRationale: '인증 없이 조작된 링크를 만들 수 있지만 피해자의 링크 열기 동작이 필요하다. 실제 CSP와 사용자 역할에 따라 영향이 달라진다.',
  impactScope: '검색 결과 페이지를 열어 본 사용자. 저장되지 않으므로 해당 요청에 한정된다.',
  rootCause: '서버가 q 값을 HTML body 컨텍스트에 출력하면서 프레임워크의 기본 escaping을 해제했다.',
  remediation: '기본 auto-escape를 복구하고 HTML이 필요 없는 검색어는 텍스트 노드로 렌더링한다. CSP는 보조 통제로 유지한다.',
  retestProcedure: '동일한 마커와 실습용 PoC를 입력해 응답 소스와 DOM에서 인코딩된 텍스트로만 표시되는지 확인한다. 인접 검색 필터와 오류 메시지도 회귀 확인한다.',
  retestResult: '수정 버전에서 입력값이 텍스트로 표시되고 실행 표시가 발생하지 않음.',
  status: 'reviewed',
  updatedAt: '2026-07-11T09:00:00.000Z',
}

export const studentReportCases = [
  {
    id: 'student-stored-title',
    type: 'Stored XSS',
    title: '게시글 제목 저장 후 목록 열람 시 실행',
    location: '게시글 작성 → 제목 → 게시글 목록',
    source: '게시글 제목 입력',
    transform: 'DB 저장 → 목록 조회 → 템플릿 출력',
    sink: '게시글 목록의 escape 해제된 제목 출력',
    context: 'HTML body',
    discovery: '작성 화면에서 고유 마커를 제목에 저장한 뒤 목록 페이지에서 마커가 HTML 본문에 그대로 들어가는지 확인합니다.',
    scenario: '작성 시점이 아니라 제목이 저장된 게시글 목록을 다른 사용자가 열 때 반복 실행될 수 있습니다. 노출 대상과 사용자 역할을 영향 근거에 포함합니다.',
    rootCause: '저장된 제목을 목록 템플릿에 출력하면서 HTML 컨텍스트 인코딩을 적용하지 않음',
    remediation: '템플릿 기본 escaping을 유지하고 제목은 텍스트로만 렌더링합니다. 수정 후 기존 저장 데이터와 새 입력을 모두 재시험합니다.',
    evidence: ['작성 요청', '저장된 값의 재조회', '피해자 목록 DOM', '수정 전·후 코드'],
  },
  {
    id: 'student-reflected-search',
    type: 'Reflected XSS',
    title: '검색어가 GET URL을 통해 현재 응답에 반사',
    location: '검색 화면 → q query → 검색 결과',
    source: 'GET query q',
    transform: '요청 파싱 → 검색 결과 템플릿',
    sink: '검색 안내 문구의 escape 해제 출력',
    context: 'HTML body',
    discovery: '고유 마커를 검색어로 전송하고 요청 URL, 응답 소스, 실행 후 DOM에서 마커 위치를 차례로 확인합니다.',
    scenario: '조작된 검색 링크를 피해자가 열었을 때 해당 요청의 응답에서 실행됩니다. 저장되지 않는다는 점과 사용자 상호작용 조건을 기록합니다.',
    rootCause: 'q를 HTML 본문에 출력하면서 컨텍스트별 출력 인코딩을 적용하지 않음',
    remediation: '검색어를 텍스트 노드로 렌더링하고 프레임워크 auto-escape를 복구합니다.',
    evidence: ['원본 GET Request', '응답 반사 위치', 'DOM 실행 지점', '텍스트 렌더링 재시험'],
  },
  {
    id: 'student-reflected-placeholder',
    type: 'Reflected XSS · Attribute',
    title: '마이페이지 입력값이 placeholder 속성 위치에 반사',
    location: '마이페이지 → 입력 필드 placeholder',
    source: '프로필 query 또는 사용자 표시값',
    transform: '프로필 데이터 조회 → 속성 문자열 결합',
    sink: 'input placeholder 속성',
    context: 'HTML attribute',
    discovery: '마커를 넣은 뒤 Elements에서 값이 속성 따옴표 안에 있는지, 속성 경계를 벗어날 수 있는 출력 방식인지 확인합니다.',
    scenario: 'HTML 본문과 달리 속성의 따옴표와 속성 종류가 해석을 결정합니다. 정확한 DOM과 브라우저 파서 결과를 근거로 적습니다.',
    rootCause: '사용자 값을 따옴표 처리와 속성 컨텍스트 인코딩 없이 문자열로 결합함',
    remediation: 'DOM API로 안전한 속성에 값을 설정하고 프레임워크 속성 바인딩을 사용합니다.',
    evidence: ['입력 데이터', '응답 HTML', '실행 후 input DOM', '안전한 속성 바인딩 코드'],
  },
  {
    id: 'student-case-filter',
    type: 'Stored XSS · Filter failure',
    title: '소문자 script 문자열만 제거하는 블랙리스트',
    location: '게시글 저장 전 문자열 필터',
    source: '게시글 본문',
    transform: '특정 소문자 토큰 제거 → DB 저장',
    sink: '게시글 상세의 HTML 출력',
    context: 'HTML body',
    discovery: '필터가 어떤 문자열을 어느 시점에 바꾸는지 확인하고 브라우저가 실제로 해석하는 문법 범위와 비교합니다.',
    scenario: '특정 태그 문자열 하나를 차단해도 브라우저에는 여러 HTML·속성·URL 실행 문맥이 존재합니다. 우회 목록보다 구조적 실패를 설명합니다.',
    rootCause: '출력 컨텍스트에서 데이터를 코드와 분리하지 않고 불완전한 입력 블랙리스트에 의존함',
    remediation: '기본 escaping과 컨텍스트별 출력 처리를 적용하고 HTML 허용이 필요할 때만 검증된 Sanitizer를 사용합니다.',
    evidence: ['필터 전·후 값', '저장 값', '렌더링 컨텍스트', 'escaping 적용 재시험'],
  },
  {
    id: 'student-client-filter',
    type: 'Stored XSS · Trust boundary',
    title: '클라이언트 JavaScript 꺾쇠 필터만 적용',
    location: '게시글 작성 브라우저 검증',
    source: '게시글 본문 요청',
    transform: '브라우저 onSubmit 검사 → 서버 무검증 저장',
    sink: '게시글 상세 HTML 출력',
    context: 'HTML body',
    discovery: '브라우저 검증 코드와 서버가 받은 요청을 비교해 요청을 직접 만들었을 때 서버가 같은 검증을 수행하는지 확인합니다.',
    scenario: '클라이언트 코드는 사용자가 변경할 수 있으므로 서버의 신뢰 경계가 될 수 없습니다. 보고서에는 우회 도구보다 서버 검증 부재를 원인으로 씁니다.',
    rootCause: '변경 가능한 클라이언트 검증만 신뢰하고 서버 저장·출력 단계에 안전한 통제가 없음',
    remediation: '서버에서 데이터 정책을 검증하고 출력에서는 escaping 또는 Sanitization을 적용합니다.',
    evidence: ['브라우저 정상 요청', '내장 요청 편집기의 변경 요청', '서버 응답', '서버 검증 추가 코드'],
  },
  {
    id: 'student-login-error',
    type: 'Reflected XSS',
    title: '존재하지 않는 ID가 로그인 오류 메시지에 반사',
    location: '로그인 실패 → 오류 메시지',
    source: '로그인 ID',
    transform: '인증 실패 → 오류 메시지 문자열 결합',
    sink: '로그인 화면의 오류 HTML',
    context: 'HTML body 또는 attribute 확인 필요',
    discovery: '존재하지 않는 고유 ID를 보내고 오류 응답에서 어느 위치와 문법으로 돌아오는지 확인합니다.',
    scenario: '로그인 실패 경로도 일반 페이지와 같은 출력 보안이 필요합니다. 인증 전 접근 가능성과 오류 메시지의 사용자 열람 조건을 영향에 포함합니다.',
    rootCause: '오류 메시지에 사용자 입력을 직접 결합하면서 출력 컨텍스트 인코딩을 적용하지 않음',
    remediation: '고정된 오류 문구를 사용하거나 입력값을 텍스트로 렌더링하고 계정 존재 여부 노출도 함께 줄입니다.',
    evidence: ['로그인 POST Request', '실패 Response', '오류 DOM', '고정 문구 적용 재시험'],
  },
]

export const publicReportResources = [
  { title: 'OWASP Web Security Testing Guide', org: 'OWASP', use: '테스트 목적·단계·증거 구조', url: 'https://owasp.org/www-project-web-security-testing-guide/' },
  { title: 'XSS Prevention Cheat Sheet', org: 'OWASP', use: '컨텍스트별 방어 기준', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html' },
  { title: 'CVSS v4.0 Specification', org: 'FIRST', use: 'Vector와 심각도 근거', url: 'https://www.first.org/cvss/v4.0/specification-document' },
  { title: 'Public Pentest Reports', org: 'Cure53', use: 'Finding ID·Fix Note·재시험 표현', url: 'https://cure53.de/#publications' },
  { title: 'Public Security Reviews', org: 'Trail of Bits', use: '코드 근거·영향·개선안 배치', url: 'https://github.com/trailofbits/publications/tree/master/reviews' },
]

export const reportFieldMeta = {
  findingId: ['Finding ID', '예: W4-XSS-001'], title: ['제목', '취약 위치 + 유형 + 핵심 영향'], status: ['상태', ''], severity: ['심각도', ''],
  asset: ['영향받는 자산', '예: Local Training App'], endpoint: ['Endpoint·Route', '/labs/...'], method: ['HTTP Method', 'GET'], parameter: ['Parameter·Header·DOM Source', 'q'],
  authPrerequisites: ['인증·권한 전제', '누가 이 기능에 접근할 수 있는가'], environment: ['테스트 환경', '브라우저·도구·버전'], vulnerabilityType: ['취약점 유형', 'Reflected XSS'],
  source: ['Source', '데이터가 들어오는 지점'], transforms: ['Transform', '검증·디코딩·저장·렌더링 경로'], sink: ['Sink', '코드로 해석되는 출력 지점'], context: ['브라우저 컨텍스트', 'HTML body·attribute·JS string 등'],
  summary: ['요약', '무슨 입력이 어디에서 왜 코드로 해석되는가'], prerequisites: ['재현 전제조건', '테스트 계정·기능 상태'], reproductionSteps: ['재현 단계', '번호 순서로 한 단계씩 작성'],
  request: ['원본 HTTP Request', 'Cookie·Authorization은 반드시 마스킹'], response: ['원본 HTTP Response', '민감정보와 개인정보 마스킹'], poc: ['PoC', '무해한 교육용 동작만'],
  observedResult: ['관찰된 결과', '실제로 확인한 사실'], expectedResult: ['기대되는 안전한 결과', '수정 후 정상 동작'], technicalImpact: ['기술적 영향', '브라우저·세션·데이터 관점'],
  businessImpact: ['비즈니스 영향', '사용자·운영·규제 관점'], likelihoodRationale: ['공격 가능성 근거', '전제·상호작용·노출 범위'], impactScope: ['영향 범위', '어떤 사용자와 페이지'],
  rootCause: ['근본 원인', '입력·Sink·Context·빠진 통제'], remediation: ['개선 권고', '근본 수정과 보조 통제 구분'], vulnerableCode: ['취약 코드', '실행 지점이 보이게 작성'],
  fixedCode: ['수정 코드', '안전한 Sink·escaping·Sanitizer'], temporaryMitigation: ['임시 완화', '배포 전 단기 조치'], retestProcedure: ['재시험 절차', '동일 조건과 회귀 조건'],
  retestResult: ['재시험 결과', '날짜·버전·관찰 증거'], references: ['참고 자료', '표준·공식 문서·공개 보고서'],
}
